/*
  JSON → Go struct 產生引擎 —— 純函式、無 DOM 依賴,可在 Node 直接測試。
  貼上範例 JSON,推斷出對應的 Go 結構型別(含 `json:"..."` tag),巢狀物件用內嵌匿名 struct。
  陣列會合併所有元素的欄位(取聯集),型別衝突退成 interface{};整數→int、含小數→float64、
  null→interface{}。輸出可直接貼進 Go 程式(欄位對齊交給 gofmt)。
  與 json-to-ts(TypeScript)互補。全程在你的瀏覽器,不連網、不上傳。
*/

// 常見縮寫:作為獨立單字時整個大寫(符合 Go 命名慣例)
const INITIALISMS = new Set([
  'id', 'url', 'uri', 'api', 'html', 'json', 'http', 'https', 'sql', 'xml', 'uuid', 'cpu',
  'db', 'ip', 'ssh', 'tcp', 'udp', 'ascii', 'css', 'dns', 'eof', 'gpu', 'os', 'ram', 'toml',
  'ttl', 'ui', 'utf8', 'vm', 'xss', 'guid', 'sla', 'rpc', 'ssl', 'tls', 'jwt',
])

/** 把 JSON 鍵名轉成 Go 匯出欄位名(PascalCase,縮寫大寫)。 */
export function goFieldName(key: string): string {
  // 先把非英數換空白,再切 camelCase 與縮寫邊界
  let s = key.replace(/[^A-Za-z0-9]+/g, ' ')
  s = s.replace(/([a-z0-9])([A-Z])/g, '$1 $2')
  s = s.replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
  const words = s.split(/\s+/).filter(Boolean)
  if (words.length === 0) return '_'
  const mapped = words.map((w) =>
    INITIALISMS.has(w.toLowerCase()) ? w.toUpperCase() : w.charAt(0).toUpperCase() + w.slice(1),
  )
  let name = mapped.join('')
  if (/^[0-9]/.test(name)) name = '_' + name
  return name
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

function scalarType(v: unknown): string {
  if (v === null) return 'interface{}'
  if (typeof v === 'boolean') return 'bool'
  if (typeof v === 'number') return Number.isInteger(v) ? 'int' : 'float64'
  if (typeof v === 'string') return 'string'
  return 'interface{}'
}

/** 把多個值合併成單一 Go 型別字串(可能跨多行,用於陣列元素/欄位)。indent 為當前縮排層級。 */
function mergeValues(values: unknown[], indent: number): string {
  const vals = values.filter((v) => v !== undefined)
  const nonNull = vals.filter((v) => v !== null)
  if (nonNull.length === 0) return 'interface{}'

  // 全部是物件 → 合併成 struct
  if (nonNull.every(isPlainObject)) {
    const objs = nonNull as Record<string, unknown>[]
    const keyOrder: string[] = []
    const byKey = new Map<string, unknown[]>()
    for (const o of objs) {
      for (const k of Object.keys(o)) {
        if (!byKey.has(k)) {
          byKey.set(k, [])
          keyOrder.push(k)
        }
        byKey.get(k)!.push(o[k])
      }
    }
    const pad = '\t'.repeat(indent + 1)
    let s = 'struct {\n'
    for (const k of keyOrder) {
      const t = mergeValues(byKey.get(k)!, indent + 1)
      s += `${pad}${goFieldName(k)} ${t} \`json:"${k}"\`\n`
    }
    s += '\t'.repeat(indent) + '}'
    return s
  }

  // 全部是陣列 → 合併所有元素
  if (nonNull.every((v) => Array.isArray(v))) {
    const allElems = (nonNull as unknown[][]).flat()
    return '[]' + mergeValues(allElems, indent)
  }

  // 純量 / 混合
  const types = new Set(nonNull.map(scalarType))
  if (types.size === 1) return [...types][0]
  // int 與 float64 混合 → float64
  if ([...types].every((t) => t === 'int' || t === 'float64')) return 'float64'
  return 'interface{}'
}

/** 單一值 → Go 型別。 */
export function goType(value: unknown, indent = 0): string {
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]interface{}'
    return '[]' + mergeValues(value, indent)
  }
  if (isPlainObject(value)) return mergeValues([value], indent)
  return scalarType(value)
}

export interface GenerateResult {
  ok: boolean
  code: string
  error?: string
}

/** 主入口:JSON 文字 → Go 型別宣告。rootName 為頂層型別名稱。 */
export function generateGo(jsonText: string, rootName = 'AutoGenerated'): GenerateResult {
  const name = goFieldName(rootName) || 'AutoGenerated'
  let parsed: unknown
  try {
    parsed = JSON.parse(jsonText)
  } catch (e) {
    return { ok: false, code: '', error: (e as Error).message }
  }
  const t = goType(parsed, 0)
  return { ok: true, code: `type ${name} ${t}` }
}
