import type { Component } from 'vue'

/*
  ★ 單一事實來源 ★
  所有工具的 metadata 都註冊在這裡。
  導覽、搜尋、關鍵字導引(chatbot)、分類頁、路由,全部讀這一份。
  新增工具 = 在 src/tools/<id>/Index.vue 寫元件 + 在這裡加一筆。不改主程式。
*/
export interface ToolDef {
  id: string // kebab-case,= 路由 slug,= 資料夾名
  name: string
  category: string // 對應 categories.ts 的 id
  description: string
  keywords: string[] // 關鍵字導引比對用,含同義詞、口語說法
  icon: string
  loader: () => Promise<{ default: Component }>
}

export const tools: ToolDef[] = [
  {
    id: 'image-studio',
    name: '圖片工坊',
    category: 'workshop',
    description: '批次轉檔(JPG/PNG/WebP)、壓縮、縮放 —— 全程在你瀏覽器處理,不上傳、無廣告、自動清掉相片定位等中繼資料。',
    keywords: ['圖片', '照片', '轉檔', '格式', '壓縮', '縮小', '縮放', 'webp', 'jpg', 'png', '批次', '改大小', '去exif'],
    icon: '🖼️',
    loader: () => import('@/tools/image-studio/Index.vue'),
  },
  {
    id: 'pdf-studio',
    name: 'PDF 工坊',
    category: 'workshop',
    description: '合併、刪頁/重排、圖片↔PDF、取出文字、加浮水印、加頁碼、壓縮 —— 全程在你瀏覽器處理,不上傳機密文件、無廣告、不限檔數。',
    keywords: ['pdf', '合併', '分割', '刪頁', '重排', '頁面', '圖片轉pdf', 'pdf轉圖片', 'pdf轉jpg', '掃描', '轉檔', '擷取', '抽頁', '組合', '浮水印', '加註', '證件', '防盜用', 'watermark', '取出文字', '抽文字', '複製文字', '純文字', 'pdf轉文字', 'pdf轉文字檔', '文字層', '頁碼', '加頁碼', '編號', '頁數', '第幾頁', 'page number', '壓縮', '縮小', '減肥', '檔案太大', '太大', '寄不出去', 'compress', '變小'],
    icon: '📄',
    loader: () => import('@/tools/pdf-studio/Index.vue'),
  },
  {
    id: 'secure-box',
    name: '本機加密保險箱',
    category: 'workshop',
    description: '替文字或檔案上密碼(AES-GCM 256),把加密結果寄出、另以電話告知密碼,對方才解得開 —— 加密、解密、密碼全程在你瀏覽器,不上傳;線上加密網站可能偷記你的內容與密碼。',
    keywords: ['加密', '解密', '密碼', '保護', '機密', '檔案加密', '文字加密', 'aes', '加密檔案', '上密碼', 'encrypt', 'decrypt', '保險箱', '隱私', '安全傳檔'],
    icon: '🔐',
    loader: () => import('@/tools/secure-box/Index.vue'),
  },
  {
    id: 'heic-convert',
    name: 'HEIC 轉 JPG / PNG',
    category: 'workshop',
    description: 'iPhone 拍的 .heic 照片在 Windows、舊手機、很多網站都打不開?一鍵轉成 JPG/PNG —— 全程在你瀏覽器解碼,不上傳私密照片、無廣告、無浮水印、可批次。',
    keywords: ['heic', 'heif', 'iphone', '蘋果', '照片', '打不開', '無法開啟', '轉檔', '轉jpg', '轉png', '格式', 'jpg', 'png', '批次', '蘋果照片', '相片'],
    icon: '📷',
    loader: () => import('@/tools/heic-convert/Index.vue'),
  },
  {
    id: 'data-convert',
    name: '資料轉換工坊',
    category: 'workshop',
    description: 'CSV / JSON / Excel 三者互轉,直接讀寫 .xlsx —— 全程在你瀏覽器,不上傳名單訂單、無廣告、不限筆數。',
    keywords: ['csv', 'json', '轉換', '互轉', 'tsv', 'excel', 'xlsx', 'xls', '試算表', '資料', '表格', '逗號', '匯出', '格式轉換', '名單', '訂單'],
    icon: '🔄',
    loader: () => import('@/tools/data-convert/Index.vue'),
  },
  {
    id: 'zip-studio',
    name: 'ZIP 工坊',
    category: 'workshop',
    description: '把多個檔案打包成一個 .zip,或把收到的 .zip 在本機解開檢視/取檔 —— 全程在你瀏覽器,不上傳、無廣告、不限檔數大小。',
    keywords: ['zip', '壓縮', '解壓', '解壓縮', '打包', '封存', 'archive', 'compress', 'extract', 'unzip', '附件', '多檔', '資料夾', '合併檔案'],
    icon: '🗜️',
    loader: () => import('@/tools/zip-studio/Index.vue'),
  },
  {
    id: 'file-split',
    name: '檔案分割 / 合併',
    category: 'workshop',
    description: '大檔寄不出去?把任何檔案切成小份分批傳(email/LINE/雲端有大小限制),收到後再合併還原 —— 全程在你瀏覽器處理,不上傳、無廣告。用標準 .001 命名,對方也能用內建指令合併。',
    keywords: ['分割', '切割', '合併', '切檔', '分檔', '大檔', '檔案太大', '太大', '寄不出去', '上傳限制', '附件太大', 'split', 'join', 'merge', '001', 'hjsplit', '分卷', '拆檔', '影片太大', '備份'],
    icon: '🪓',
    loader: () => import('@/tools/file-split/Index.vue'),
  },
  {
    id: 'image-stitch',
    name: '圖片拼接(長圖)',
    category: 'workshop',
    description: '把多張截圖、收據、對話接成一張長圖或長條 —— 縱向/橫向、可調間距對齊,全程在你瀏覽器合成,不上傳、無廣告、無浮水印。',
    keywords: ['拼接', '拼圖', '長圖', '合併圖片', '接圖', '截圖', '對話', 'line對話', '收據', '併圖', '組圖', '直向', '橫向', '長截圖', '合成', 'stitch', '對比圖'],
    icon: '🧩',
    loader: () => import('@/tools/image-stitch/Index.vue'),
  },
  {
    id: 'image-crop',
    name: '圖片裁切 / 旋轉',
    category: 'workshop',
    description: '把拍歪的照片轉正、裁掉多餘背景或框出重點 —— 旋轉、翻轉、拖曳裁切,全程在你瀏覽器處理,不上傳、無廣告、無浮水印,可隨時復原。',
    keywords: ['裁切', '裁剪', '剪裁', '旋轉', '轉正', '翻轉', '鏡像', '剪掉', '去背景', '框選', '照片', '圖片', '相片', 'crop', 'rotate', '橫的', '直的', '拍歪'],
    icon: '✂️',
    loader: () => import('@/tools/image-crop/Index.vue'),
  },
  {
    id: 'id-photo',
    name: '證件照排版(4×6)',
    category: 'workshop',
    description: '把一張大頭照排成一張 4×6 相片紙的多張一吋/二吋證件照,300 DPI 可直接拿去沖洗 —— 全程在你瀏覽器處理,臉部照片不上傳、無廣告、無浮水印,免上傳到陌生網站或花錢請相館。',
    keywords: ['證件照', '大頭照', '一吋', '二吋', '證件', '護照照片', '身分證照片', '排版', '相片紙', '4x6', '4×6', '沖洗', '沖印', '大頭貼', '駕照照片', '履歷照', 'id photo', '證件相'],
    icon: '📸',
    loader: () => import('@/tools/id-photo/Index.vue'),
  },
  {
    id: 'favicon-gen',
    name: '網站圖示 / Favicon 產生器',
    category: 'workshop',
    description: '上傳一張圖,輸出 favicon.ico(內含 16/32/48 多尺寸)、apple-touch-icon 與 PWA 圖示(192/512),附可直接貼上的 HTML —— 全程在你瀏覽器處理,logo 不上傳、無廣告、不綁追蹤。',
    keywords: ['favicon', 'ico', '網站圖示', '圖示', 'icon', '網站小圖', '分頁圖示', 'apple-touch-icon', 'pwa', '網站logo', 'logo轉ico', '製作favicon', '圖轉ico', '網頁圖示'],
    icon: '🌐',
    loader: () => import('@/tools/favicon-gen/Index.vue'),
  },
  {
    id: 'subtitle-studio',
    name: '字幕工坊(SRT/VTT)',
    category: 'workshop',
    description: 'SRT ↔ WebVTT 互轉、整體平移對時(字幕快/慢幾秒)、速率縮放、自動重新編號 —— 全程在你瀏覽器處理,字幕內容不上傳、無廣告、免註冊。',
    keywords: ['字幕', 'srt', 'vtt', 'webvtt', '字幕轉檔', '字幕格式', '對時', '平移', '時間軸', '同步', '不同步', '快了', '慢了', '延遲', '影片字幕', '電影字幕', '轉換', '字幕檔'],
    icon: '🎬',
    loader: () => import('@/tools/subtitle-studio/Index.vue'),
  },
  {
    id: 'text-diff',
    name: '文字差異比對',
    category: 'workshop',
    description: '比對合約改版、條款、規格新舊兩版,逐行加逐字標出改了哪裡 —— 全程在你瀏覽器,不上傳機密文字、無廣告。',
    keywords: ['比對', '差異', '差別', '比較', 'diff', '兩份', '新舊', '改版', '版本', '合約', '條款', '對照', '哪裡不同', '逐字', '文字比對', 'compare', '異動'],
    icon: '📝',
    loader: () => import('@/tools/text-diff/Index.vue'),
  },
  {
    id: 'image-redact',
    name: '圖片遮蔽(塗黑/馬賽克)',
    category: 'workshop',
    description: '分享截圖前,把身分證、地址、帳號等個資塗黑或打馬賽克 —— 全程在你瀏覽器,不上傳、真的把像素塗掉、無廣告。',
    keywords: ['遮蔽', '塗黑', '馬賽克', '打碼', '去碼', '隱私', '個資', '截圖', '遮住', '隱藏', '模糊', '身分證', '帳號', '保護'],
    icon: '🌫️',
    loader: () => import('@/tools/image-redact/Index.vue'),
  },
  {
    id: 'text-redact',
    name: '文字個資遮蔽',
    category: 'anti-scam',
    description: '貼上對話/單據文字,自動找出身分證、手機、信用卡、Email 並打碼 —— 轉貼客服對話、分享截圖文字前先遮個資。全程在你瀏覽器以規則比對,不上傳;身分證/信用卡會驗證檢查碼避免誤判。',
    keywords: ['個資', '遮蔽', '打碼', '去識別', '隱私', '身分證', '手機', '信用卡', '卡號', 'email', '電子郵件', '遮個資', '對話', '客服', '截圖文字', '保護個資', '去除個資', '罩'],
    icon: '🕵️',
    loader: () => import('@/tools/text-redact/Index.vue'),
  },
  {
    id: 'image-watermark',
    name: '證件浮水印加註',
    category: 'workshop',
    description: '交付證件影本前,斜向重複加註用途(例:僅供開戶使用)防盜用 —— 全程在你瀏覽器,文字直接燒進像素、不上傳、無廣告、可批次。',
    keywords: ['浮水印', '證件', '影本', '加註', '防盜用', '身分證', '開戶', '門號', '租屋', '影印', '騎縫', '劃線', '保護', '批次', 'watermark'],
    icon: '🖋️',
    loader: () => import('@/tools/image-watermark/Index.vue'),
  },
  {
    id: 'qr-generate',
    name: 'QR Code 產生器',
    category: 'workshop',
    description: '把網址、WiFi 連線、聯絡資訊做成 QR Code,可下載 PNG —— 直接編碼你的原始內容,不像多數線上產生器偷塞追蹤短網址轉址。全程在你瀏覽器,不上傳。',
    keywords: ['qr', 'qrcode', 'qr code', '二維碼', '條碼', '產生', '製作', 'wifi', '無線網路', '聯絡', '名片', 'vcard', '網址', '連結', '掃描'],
    icon: '🔳',
    loader: () => import('@/tools/qr-generate/Index.vue'),
  },
  {
    id: 'text-clean',
    name: '文字清理工坊',
    category: 'workshop',
    description: '從 PDF/網頁/LINE 貼上的文字常夾帶看不見的零寬字元、全形英數、多餘空白 —— 一鍵清乾淨,即時統計字數。全程在你瀏覽器,不上傳、無廣告。',
    keywords: ['文字', '清理', '整理', '去空白', '空行', '零寬', '不可見字元', '全形', '半形', '大小寫', '字數統計', '字數', '計數', '去重', '貼上', '格式化'],
    icon: '🧹',
    loader: () => import('@/tools/text-clean/Index.vue'),
  },
  {
    id: 'exif-viewer',
    name: '照片隱私檢視器(EXIF)',
    category: 'anti-scam',
    description: '分享照片前先看它偷偷夾帶了什麼:拍攝時間、手機型號,甚至 GPS 拍攝地點 —— 含定位的照片會洩漏你家位置。全程在你瀏覽器解析,照片不上傳。',
    keywords: ['exif', '照片', '隱私', 'gps', '定位', '地點', '拍攝資訊', '中繼資料', 'metadata', '洩漏', '位置', '跟蹤', '相機', '型號', '去exif', '檢視'],
    icon: '📍',
    loader: () => import('@/tools/exif-viewer/Index.vue'),
  },
  {
    id: 'qr-decode',
    name: 'QR Code 解碼(看網址)',
    category: 'anti-scam',
    description: '把含 QR Code 的截圖或照片解出裡面的內容 —— 陌生 QR 直接掃容易被導到釣魚網站,先看清楚網址再決定要不要開。全程在你瀏覽器解碼,圖片不上傳。',
    keywords: ['qr', 'qrcode', 'qr code', '二維碼', '掃描', '解碼', '解析', '讀取', '讀qr', '看網址', '可疑', '釣魚', '停車單', '假帳單', 'decode', 'scan'],
    icon: '📷',
    loader: () => import('@/tools/qr-decode/Index.vue'),
  },
  {
    id: 'link-check',
    name: '可疑網址檢查器',
    category: 'anti-scam',
    description: '收到怪怪的連結?貼上來,馬上看出假冒網域、釣魚、短網址等詐騙特徵。',
    keywords: ['詐騙', '可疑', '網址', '連結', '釣魚', '假網站', '簡訊', '安全', '查證', '假冒', '釣魚網站'],
    icon: '🛡️',
    loader: () => import('@/tools/link-check/Index.vue'),
  },
  {
    id: 'sms-check',
    name: '詐騙簡訊檢查',
    category: 'anti-scam',
    description: '把可疑的簡訊或 LINE 訊息貼上來,辨識常見詐騙話術,並自動檢查裡面的連結。',
    keywords: ['詐騙', '簡訊', 'LINE', '訊息', '話術', '可疑', '假冒', '解除分期', '包裹', '中獎', '查證'],
    icon: '💬',
    loader: () => import('@/tools/sms-check/Index.vue'),
  },
  {
    id: 'email-check',
    name: '郵件來源檢視 / 防冒名',
    category: 'anti-scam',
    description: '貼上可疑信件的郵件原始碼/標頭,解析寄件網域、回覆地址與 SPF/DKIM/DMARC 驗證,標出冒名詐騙破綻。全程在你瀏覽器判讀、不上傳。',
    keywords: ['email', '郵件', '信件', '電子郵件', '標頭', 'header', '原始碼', '寄件者', '冒名', '偽冒', '釣魚', 'phishing', 'spf', 'dkim', 'dmarc', '網域', '退信', '回覆地址', '詐騙信', '假信'],
    icon: '📧',
    loader: () => import('@/tools/email-check/Index.vue'),
  },
  {
    id: 'scam-guide',
    name: '常見詐騙手法圖鑑',
    category: 'anti-scam',
    description: '解除分期、假投資、假檢警、包裹簡訊…一次看懂常見詐騙怎麼運作、破綻在哪、該怎麼做。轉給長輩看最有用。',
    keywords: ['詐騙', '手法', '圖鑑', '防詐', '反詐騙', '165', '假投資', '假檢警', '解除分期', '包裹', '一頁式', '假交友', '人頭帳戶', '懶人包', '長輩'],
    icon: '📖',
    loader: () => import('@/tools/scam-guide/Index.vue'),
  },
  {
    id: 'phone-check',
    name: '電話號碼檢視 / 防詐',
    category: 'anti-scam',
    description: '接到陌生來電?貼上號碼,看清楚它是手機、市話、免付費還是「付費語音」,並標出常見詐騙警訊(國際來電卻自稱國內機構、回撥被收高額費用等)。全程在你瀏覽器判讀、不上傳,附 165 官方查證連結。',
    keywords: ['電話', '號碼', '來電', '陌生來電', '可疑電話', '詐騙電話', '騷擾', '手機', '市話', '0204', '付費語音', '0800', '+886', '國際來電', '回撥', '查號', '165', '防詐'],
    icon: '📞',
    loader: () => import('@/tools/phone-check/Index.vue'),
  },
  {
    id: 'file-checksum',
    name: '檔案校驗碼 / 完整性驗證',
    category: 'anti-scam',
    description: '下載安裝檔後,算出 SHA-256/SHA-1/SHA-512 雜湊值,和官方公布的校驗碼比對,確認檔案沒被掉包或植入惡意程式 —— 全程在你瀏覽器計算,檔案不上傳。',
    keywords: ['校驗碼', '雜湊', 'hash', 'sha256', 'sha-256', 'sha1', 'sha512', '完整性', '驗證', '驗檔', '檔案指紋', '竄改', '掉包', '安裝檔', '校驗', 'checksum', '指紋', '比對'],
    icon: '🔐',
    loader: () => import('@/tools/file-checksum/Index.vue'),
  },
  {
    id: 'severance-pay',
    name: '資遣費試算',
    category: 'labor',
    description: '輸入年資與平均工資,算出新制/舊制資遣費,並標明法規依據。',
    keywords: ['資遣費', '資遣', '遣散費', '被資遣', '裁員', '解僱', '離職金', '勞退', '年資'],
    icon: '💼',
    loader: () => import('@/tools/severance-pay/Index.vue'),
  },
  {
    id: 'annual-leave',
    name: '特休天數計算',
    category: 'labor',
    description: '依到職日與年資,算出依勞基法第38條應有的特別休假天數。',
    keywords: ['特休', '特別休假', '年假', '休假天數', '可以休幾天', '年資', '勞基法38'],
    icon: '🏖️',
    loader: () => import('@/tools/annual-leave/Index.vue'),
  },
  {
    id: 'overtime-pay',
    name: '加班費計算',
    category: 'labor',
    description: '依勞基法第24條,計算平日與休息日加班的加給金額。',
    keywords: ['加班費', '加班', 'OT', '延長工時', '休息日加班', '時薪', '勞基法24'],
    icon: '⏰',
    loader: () => import('@/tools/overtime-pay/Index.vue'),
  },
  {
    id: 'leave-deduction',
    name: '請假扣薪試算',
    category: 'labor',
    description: '請事假、病假會被扣多少薪水?選假別、填天數,馬上算出應扣金額與仍可領的工資。',
    keywords: ['請假', '扣薪', '事假', '病假', '生理假', '婚假', '喪假', '特休', '家庭照顧假', '半薪', '無薪', '日薪', '時薪', '薪水'],
    icon: '🗓️',
    loader: () => import('@/tools/leave-deduction/Index.vue'),
  },
  {
    id: 'income-tax',
    name: '綜所稅速算',
    category: 'health-tax',
    description: '輸入綜合所得淨額,用財政部速算公式算出應納所得稅與有效稅率。',
    keywords: ['所得稅', '綜所稅', '報稅', '稅額', '級距', '速算', '繳稅', '綜合所得'],
    icon: '🧮',
    loader: () => import('@/tools/income-tax/Index.vue'),
  },
  {
    id: 'nhi-supplement',
    name: '二代健保補充保費',
    category: 'health-tax',
    description: '計算獎金、租金、股利、利息等收入要扣的二代健保補充保費。',
    keywords: ['二代健保', '補充保費', '健保', '獎金', '股利', '租金', '利息', '兼職'],
    icon: '🩺',
    loader: () => import('@/tools/nhi-supplement/Index.vue'),
  },
  {
    id: 'loan-calc',
    name: '貸款試算',
    category: 'finance',
    description: '房貸、車貸的每月應繳、總利息試算,支援本息/本金均攤與寬限期。',
    keywords: ['貸款', '房貸', '車貸', '利息', '每月還款', '月付', '本息均攤', '本金均攤', '寬限期'],
    icon: '🏠',
    loader: () => import('@/tools/loan-calc/Index.vue'),
  },
  {
    id: 'savings-interest',
    name: '定存複利試算',
    category: 'finance',
    description: '輸入本金、年利率、年數與複利次數,算出到期本利和與總利息。',
    keywords: ['定存', '複利', '利息', '存款', '本利和', '年利率', '理財', '單利'],
    icon: '🏦',
    loader: () => import('@/tools/savings-interest/Index.vue'),
  },
  {
    id: 'labor-pension-self',
    name: '勞退自提節稅試算',
    category: 'finance',
    description: '試算勞退自願提繳(上限 6%)金額,以及可省下的所得稅。',
    keywords: ['勞退', '自提', '自願提繳', '退休金', '節稅', '6%', '勞工退休金'],
    icon: '🐷',
    loader: () => import('@/tools/labor-pension-self/Index.vue'),
  },
  {
    id: 'labor-pension-annuity',
    name: '勞保老年年金試算',
    category: 'finance',
    description: '退休後勞保每月能領多少?輸入平均投保薪資與年資,兩式擇優算出月領金額,含提前/延後請領調整。',
    keywords: ['勞保', '老年年金', '退休金', '退休', '月退', '勞保年金', '請領', '投保薪資', '年資', '老年給付', '勞保老年'],
    icon: '👵',
    loader: () => import('@/tools/labor-pension-annuity/Index.vue'),
  },
  {
    id: 'installment-apr',
    name: '分期實際利率(APR)',
    category: 'finance',
    description: '「分期 0 利率」其實不便宜?輸入手續費,算出信用卡/分期付款的真實年利率。',
    keywords: ['分期', '利率', 'APR', '手續費', '信用卡', '免利率', '零利率', '實質利率', '年利率', '分期付款', '免息'],
    icon: '💳',
    loader: () => import('@/tools/installment-apr/Index.vue'),
  },
  {
    id: 'tw-id-check',
    name: '身分證字號檢核',
    category: 'life',
    description: '用內政部檢查碼規則驗算身分證字號是否格式正確,抓出打錯一碼或亂編的假號碼,並顯示初領縣市。全程本機計算、不上傳、不儲存。',
    keywords: ['身分證', '字號', '檢核', '驗證', '檢查碼', '格式', '真假', '假號碼', '初領', '縣市', 'id', '身份證', '檢查'],
    icon: '🪪',
    loader: () => import('@/tools/tw-id-check/Index.vue'),
  },
  {
    id: 'tw-vat-check',
    name: '統一編號檢核',
    category: 'life',
    description: '依財政部檢查碼規則,驗算公司統一編號(8 碼)是否正確 —— 抓出打錯一碼或亂編的假統編(假發票、人頭公司常見),可批次整理名單。全程本機計算、不上傳,並附財政部官方查詢連結。',
    keywords: ['統一編號', '統編', '營業稅籍', '公司', '行號', '檢核', '驗證', '檢查碼', '發票', '假發票', '人頭公司', '對帳', '廠商', 'vat', '8碼', '營利事業', '稅籍'],
    icon: '🏢',
    loader: () => import('@/tools/tw-vat-check/Index.vue'),
  },
  {
    id: 'password-gen',
    name: '本機密碼產生器',
    category: 'life',
    description: '用瀏覽器密碼學亂數產生高強度密碼,全程在你電腦、不連網、不記錄 —— 線上產生器可能偷偷記下你的密碼,這種工具就該在本機跑。',
    keywords: ['密碼', '產生', '產生器', '亂數', '隨機', 'password', '強密碼', '安全', '帳號', '兩步驟', '隨機密碼', '長密碼'],
    icon: '🔑',
    loader: () => import('@/tools/password-gen/Index.vue'),
  },
  {
    id: 'bmi',
    name: 'BMI 計算',
    category: 'life',
    description: '輸入身高體重,算出 BMI 與國健署體位分級,並給理想體重範圍。',
    keywords: ['bmi', '身體質量指數', '體重', '身高', '肥胖', '過重', '理想體重', '健康'],
    icon: '⚖️',
    loader: () => import('@/tools/bmi/Index.vue'),
  },
  {
    id: 'tdee',
    name: '每日熱量需求(TDEE)',
    category: 'life',
    description: '依身高體重年齡活動量,用 Mifflin-St Jeor 公式算出基礎代謝與每日該吃多少熱量。',
    keywords: ['熱量', 'tdee', 'bmr', '基礎代謝', '減重', '減肥', '卡路里', '大卡', '增肌', '飲食', '代謝率'],
    icon: '🔥',
    loader: () => import('@/tools/tdee/Index.vue'),
  },
  {
    id: 'unit-convert',
    name: '單位換算',
    category: 'life',
    description: '長度、重量、面積、溫度換算,含台灣常用的坪、台斤、台尺。',
    keywords: ['單位', '換算', '坪', '平方公尺', '台斤', '台尺', '公斤', '公里', '溫度', '攝氏', '華氏'],
    icon: '📐',
    loader: () => import('@/tools/unit-convert/Index.vue'),
  },
  {
    id: 'due-date',
    name: '預產期計算',
    category: 'life',
    description: '輸入最後一次月經第一天(LMP),推算預產期與目前懷孕週數。',
    keywords: ['預產期', '懷孕', '週數', '生產', 'LMP', '末次月經', '孕期'],
    icon: '🤰',
    loader: () => import('@/tools/due-date/Index.vue'),
  },
  {
    id: 'fuel-cost',
    name: '油錢試算',
    category: 'life',
    description: '輸入距離、油耗、油價,算出整趟油錢,還能直接除以人數算每人分攤。',
    keywords: ['油錢', '油費', '汽油', '加油', '里程', '油耗', '旅程', '開車', '分攤', '高速公路', '電車', '電費'],
    icon: '⛽',
    loader: () => import('@/tools/fuel-cost/Index.vue'),
  },
  {
    id: 'split-bill',
    name: '旅費分帳',
    category: 'life',
    description: '聚餐、旅遊一筆錢幾個人均分,可加服務費,馬上算出每人該付多少。',
    keywords: ['分帳', '均分', '平分', 'AA', '聚餐', '旅遊', '服務費', '每人', '攤錢'],
    icon: '🧮',
    loader: () => import('@/tools/split-bill/Index.vue'),
  },
  {
    id: 'invoice-lottery',
    name: '發票對獎',
    category: 'life',
    description: '輸入發票號碼,比對統一發票中獎號碼,自動算出中獎金額。',
    keywords: ['發票', '對獎', '中獎', '統一發票', '雲端發票', '對發票', '幾獎'],
    icon: '🧾',
    loader: () => import('@/tools/invoice-lottery/Index.vue'),
  },
  {
    id: 'age-calc',
    name: '年齡計算',
    category: 'datetime',
    description: '輸入出生日期,算出實歲、虛歲、人壽保險年齡,還有已活天數與生日倒數。',
    keywords: ['年齡', '幾歲', '實歲', '足歲', '虛歲', '保險年齡', '生日', '倒數', '出生', '活了幾天', '歲數'],
    icon: '🎂',
    loader: () => import('@/tools/age-calc/Index.vue'),
  },
  {
    id: 'roc-year',
    name: '民國年換算',
    category: 'datetime',
    description: '民國年、西元年、日本年號(令和/平成/昭和)即時互換。',
    keywords: ['民國', '西元', '年份', '換算', '日本年號', '令和', '平成', '昭和', '幾年'],
    icon: '📆',
    loader: () => import('@/tools/roc-year/Index.vue'),
  },
]

export const toolMap: Record<string, ToolDef> = Object.fromEntries(
  tools.map((t) => [t.id, t]),
)

export function toolsByCategory(categoryId: string): ToolDef[] {
  return tools.filter((t) => t.category === categoryId)
}
