import type { Component } from 'vue'

/*
  ★ 單一事實來源 ★
  所有工具的 metadata 都註冊在這裡。
  導覽、搜尋、關鍵字導引(chatbot)、分類頁、路由,全部讀這一份。
  新增工具 = 在 src/tools/<id>/Index.vue 寫元件 + 在這裡加一筆。不改主程式。
*/
export interface ToolDef {
  id: string // kebab-case,= 路由 slug,= 資料夾名
  name: string
  category: string // 對應 categories.ts 的 id
  description: string
  keywords: string[] // 關鍵字導引比對用,含同義詞、口語說法
  icon: string
  loader: () => Promise<{ default: Component }>
}

export const tools: ToolDef[] = [
  {
    id: 'image-studio',
    name: '圖片工坊',
    category: 'workshop',
    description: '批次轉檔(JPG/PNG/WebP)、壓縮、縮放 —— 全程在你瀏覽器處理,不上傳、無廣告、自動清掉相片定位等中繼資料。',
    keywords: ['圖片', '照片', '轉檔', '格式', '壓縮', '縮小', '縮放', 'webp', 'jpg', 'png', '批次', '改大小', '去exif'],
    icon: '🖼️',
    loader: () => import('@/tools/image-studio/Index.vue'),
  },
  {
    id: 'text-card',
    name: '社群文字卡 / 語錄圖',
    category: 'workshop',
    description: '把一段文字做成漂亮的圖片卡片(IG 貼文/限動、Threads、FB、公告、金句)—— 字級自動填滿版面、中英自動斷行,選好尺寸即套各社群版位。全程在你瀏覽器繪製,文字不上傳、無廣告、無浮水印、免開 Canva。',
    keywords: ['文字卡', '語錄', '語錄圖', '金句', '金句圖', '文字圖', '文字轉圖片', '文字卡片', '圖卡', '貼文圖', '公告圖', '海報', 'ig', 'instagram', '限動', 'threads', 'facebook', '社群', '引言', 'quote', 'text image', '做圖', '排版', '標語'],
    icon: '🗯️',
    loader: () => import('@/tools/text-card/Index.vue'),
  },
  {
    id: 'signature-maker',
    name: '手寫簽名製作',
    category: 'workshop',
    description: '在螢幕上簽名,匯出透明背景 PNG,直接貼進 PDF/Word/簡報電子簽名,免印出再掃 —— 全程在你瀏覽器,簽名不上傳。',
    keywords: ['簽名', '手寫', '電子簽名', '簽章', '簽名檔', '透明背景', 'png', '簽文件', '簽合約', 'signature', '簽名製作'],
    icon: '✍️',
    loader: () => import('@/tools/signature-maker/Index.vue'),
  },
  {
    id: 'color-tools',
    name: '色彩工坊',
    category: 'workshop',
    description: 'HEX/RGB/HSL 色碼互轉,還能從上傳的照片或 logo 抽出主色調色盤 —— 全程在你瀏覽器,圖片不上傳。',
    keywords: ['顏色', '色碼', '色彩', 'hex', 'rgb', 'hsl', '調色盤', '配色', '取色', '吸管', '主色', 'logo', '色票', 'color'],
    icon: '🎨',
    loader: () => import('@/tools/color-tools/Index.vue'),
  },
  {
    id: 'gradient-maker',
    name: 'CSS 漸層產生器',
    category: 'workshop',
    description: '視覺化調出線性 / 放射 / 圓錐漸層,多色標、角度、圓心位置即時預覽,一鍵複製可直接用的 CSS —— 全程在你瀏覽器計算,不連網、不上傳。與色彩工坊、色階產生器互補。',
    keywords: ['漸層', '漸變', 'gradient', 'css漸層', 'linear-gradient', 'radial-gradient', 'conic-gradient', '線性漸層', '放射漸層', '圓錐漸層', '背景', 'background', '配色', '色標', '色彩', 'css', '網頁', '按鈕', '漸層背景', '產生器'],
    icon: '🌈',
    loader: () => import('@/tools/gradient-maker/Index.vue'),
  },
  {
    id: 'contrast-check',
    name: '顏色可讀性檢測',
    category: 'workshop',
    description: '輸入文字色與背景色,依國際無障礙標準(WCAG)算出對比比值,判斷在一般字/大字下清不清楚、達不達 AA/AAA —— 做簡報、海報、網頁、長輩友善文件選色用。全程在你瀏覽器計算,不上傳。',
    keywords: ['對比', '對比度', '色彩對比', '顏色對比', '可讀性', '看不清楚', 'wcag', 'aa', 'aaa', '無障礙', '配色', '文字顏色', '背景色', '對比比值', 'contrast', 'a11y', '長輩', '弱視', '簡報配色'],
    icon: '🌗',
    loader: () => import('@/tools/contrast-check/Index.vue'),
  },
  {
    id: 'color-blind',
    name: '色盲友善檢測',
    category: 'workshop',
    description: '上傳圖表、簡報、網頁截圖,模擬色盲/色弱使用者看到的樣子,檢查紅綠配色是否還分得出來 —— 全程在你瀏覽器處理,圖片不上傳。',
    keywords: ['色盲', '色弱', '色覺', '紅綠色盲', '色覺障礙', '色盲模擬', '色盲友善', '無障礙', 'a11y', '配色', '圖表配色', '簡報配色', '色彩', 'deuteranopia', 'protanopia', 'tritanopia', '色盲檢測', '色盲測試', 'colorblind', '色弱模擬'],
    icon: '👁️',
    loader: () => import('@/tools/color-blind/Index.vue'),
  },
  {
    id: 'gif-studio',
    name: '動圖工坊',
    category: 'workshop',
    description: '把多張圖片做成會動的 GIF,可調速度、尺寸、循環 —— 全程在你瀏覽器編碼,不上傳、無廣告、無浮水印(線上 GIF 站多半要上傳照片又加浮水印)。',
    keywords: ['gif', '動圖', '動畫', '會動的圖', '動態圖', '圖片變動畫', '製作gif', '做gif', '連續圖', '逐格', '動態貼圖', 'animated', '影格', '動圖製作'],
    icon: '🎞️',
    loader: () => import('@/tools/gif-studio/Index.vue'),
  },
  {
    id: 'video-gif',
    name: '影片轉 GIF',
    category: 'workshop',
    description: '把一小段影片(MP4/WebM/MOV)轉成會動的 GIF,可裁時間區間、調速度尺寸 —— 全程在你瀏覽器解碼編碼,影片不上傳、無廣告、無浮水印、不限時長(線上轉 GIF 站要上傳又加浮水印)。',
    keywords: ['影片轉gif', '影片轉動圖', 'video to gif', 'gif', '動圖', '動畫', 'mp4轉gif', '影片', '截短片', '片段', '做gif', '貼圖', '動態圖', 'webm', 'mov', '轉檔', '影片轉檔'],
    icon: '🎥',
    loader: () => import('@/tools/video-gif/Index.vue'),
  },
  {
    id: 'image-ocr',
    name: '圖片文字辨識(OCR)',
    category: 'workshop',
    description: '把截圖、照片、掃描檔裡的文字抓成可編輯文字,支援繁中+英 —— 全程在你瀏覽器辨識,圖片不上傳(一般 OCR 網站都要你上傳)。',
    keywords: ['ocr', '文字辨識', '圖片轉文字', '截圖轉文字', '照片轉文字', '掃描', '辨識', '抓文字', '擷取文字', '圖轉文字', '繁體', '辨識文字', 'image to text'],
    icon: '🔠',
    loader: () => import('@/tools/image-ocr/Index.vue'),
  },
  {
    id: 'random-picker',
    name: '抽籤 / 分組',
    category: 'life',
    description: '貼上名單,隨機抽出、隨機分組或隨機排序 —— 用加密級亂數,比一般網頁公平。聚餐誰請客、分組、抽獎都好用,名單不上傳。',
    keywords: ['抽籤', '抽獎', '尾牙', '中獎', '分組', '隨機', '洗牌', '排序', '誰請客', '決定', '做決定', '隨機選', '分隊', '抽人', '點名', '亂數', '公平', 'random', 'draw', '抽號碼', '轉盤'],
    icon: '🎲',
    loader: () => import('@/tools/random-picker/Index.vue'),
  },
  {
    id: 'image-annotate',
    name: '圖片標註編輯器',
    category: 'workshop',
    description: '在截圖/照片上畫箭頭、框重點、畫筆、打字,做教學步驟、回報問題、圈重點 —— 全程在你瀏覽器,圖片不上傳。',
    keywords: ['標註', '截圖', '畫箭頭', '框起來', '圈重點', '畫重點', '註記', '打字', '畫筆', '編輯圖片', '線上編圖', '修圖', '教學', '說明圖', 'annotate', 'markup', '圖片編輯'],
    icon: '🖍️',
    loader: () => import('@/tools/image-annotate/Index.vue'),
  },
  {
    id: 'timezone',
    name: '時區換算 / 世界時鐘',
    category: 'life',
    description: '看現在各地幾點,或把某地某時間換算到全球各時區 —— 自動處理日光節約,跟國外家人朋友、客戶約時間不算錯。純前端。',
    keywords: ['時區', '時差', '世界時鐘', '換算', '幾點', '國外時間', '日光節約', '約時間', '會議', 'utc', 'gmt', '紐約', '東京', '倫敦', '美國時間', 'timezone'],
    icon: '🌏',
    loader: () => import('@/tools/timezone/Index.vue'),
  },
  {
    id: 'find-replace',
    name: '尋找取代工坊',
    category: 'workshop',
    description: '批次尋找/取代文字,支援正規表達式與忽略大小寫,可用 $1 引用群組 —— 整理名單、批次改格式很快,全程在你瀏覽器,文字不上傳。',
    keywords: ['尋找', '取代', '替換', '搜尋取代', 'find', 'replace', '批次', '正則', '正規表達式', 'regex', '文字處理', '整理', '取代字串', '換字'],
    icon: '🔁',
    loader: () => import('@/tools/find-replace/Index.vue'),
  },
  {
    id: 'screen-record',
    name: '螢幕錄影',
    category: 'workshop',
    description: '錄製整個螢幕、視窗或分頁成影片(可含聲音),做操作教學、把畫面問題錄給人看 —— 全程在你電腦錄製,影片不上傳、無浮水印、不限時長。',
    keywords: ['螢幕錄影', '錄影', '錄製', '錄螢幕', '畫面錄製', '教學錄影', '錄畫面', 'screen record', 'recorder', '錄製教學', '操作錄影', '螢幕錄製'],
    icon: '⏺️',
    loader: () => import('@/tools/screen-record/Index.vue'),
  },
  {
    id: 'voice-recorder',
    name: '錄音機',
    category: 'workshop',
    description: '用麥克風錄語音備忘、訪談、會議、長輩口述,可暫停/繼續、試聽後下載音檔 —— 全程在你的裝置錄製,聲音不上傳、無廣告、不限時長、免註冊。與螢幕錄影互補(這支只錄聲音)。',
    keywords: ['錄音', '錄音機', '語音', '麥克風', '收音', '語音備忘', '訪談', '會議', '口述', '錄聲音', '配音', 'voice', 'recorder', 'audio', '音檔', '錄製聲音', '線上錄音'],
    icon: '🎙️',
    loader: () => import('@/tools/voice-recorder/Index.vue'),
  },
  {
    id: 'bg-remove',
    name: '圖片去背',
    category: 'workshop',
    description: '自動去掉照片背景、輸出透明 PNG,做商品圖、大頭貼最方便 —— 全程在你瀏覽器用 AI 處理,照片不上傳;remove.bg 等服務要付費又要上傳。',
    keywords: ['去背', '去背景', '退底', '透明背景', '摳圖', '商品圖', '大頭貼', 'removebg', 'remove bg', '背景移除', '人像去背', 'png', '退地'],
    icon: '🪄',
    loader: () => import('@/tools/bg-remove/Index.vue'),
  },
  {
    id: 'pdf-studio',
    name: 'PDF 工坊',
    category: 'workshop',
    description: '合併、刪頁/重排、圖片↔PDF、取出文字、簽名/蓋章、加浮水印、加頁碼、併頁省紙、壓縮 —— 全程在你瀏覽器處理,不上傳機密文件、無廣告、不限檔數。',
    keywords: ['pdf', '合併', '分割', '刪頁', '重排', '旋轉', '轉正', '轉向', '歪斜', '頁面', '圖片轉pdf', 'pdf轉圖片', 'pdf轉jpg', '掃描', '轉檔', '擷取', '抽頁', '組合', '簽名', '簽署', '簽章', '蓋章', '用印', '印章', '簽合約', '在pdf上簽名', 'sign', '浮水印', '加註', '證件', '防盜用', 'watermark', '取出文字', '抽文字', '複製文字', '純文字', 'pdf轉文字', 'pdf轉文字檔', '文字層', '頁碼', '加頁碼', '編號', '頁數', '第幾頁', 'page number', '併頁', '省紙', '一頁多頁', '2合1', '4合1', '多合一', '講義', '印講義', 'n-up', 'nup', '節省紙張', '壓縮', '縮小', '減肥', '檔案太大', '太大', '寄不出去', 'compress', '變小'],
    icon: '📄',
    loader: () => import('@/tools/pdf-studio/Index.vue'),
  },
  {
    id: 'doc-scan',
    name: '文件掃描美化',
    category: 'workshop',
    description: '把手機拍的文件照片變成像掃描機掃出來的乾淨檔 —— 自動拉對比、提亮背景,可轉黑白/灰階,合併成 PDF —— 全程在你瀏覽器處理,合約單據不上傳、無廣告、無浮水印(CamScanner 等要付費又加浮水印)。',
    keywords: ['掃描', '文件掃描', '掃描器', '拍文件', '文件變掃描', 'camscanner', '掃描app', '合約', '單據', '收據', '筆記', '白板', '黑白', '自適應', '二值化', '提亮', '對比', '拍照轉pdf', '照片轉pdf', '文件轉pdf', 'scan', 'scanner', '去背景', '紙變白'],
    icon: '🖨️',
    loader: () => import('@/tools/doc-scan/Index.vue'),
  },
  {
    id: 'secure-box',
    name: '本機加密保險箱',
    category: 'workshop',
    description: '替文字或檔案上密碼(AES-GCM 256),把加密結果寄出、另以電話告知密碼,對方才解得開 —— 加密、解密、密碼全程在你瀏覽器,不上傳;線上加密網站可能偷記你的內容與密碼。',
    keywords: ['加密', '解密', '密碼', '保護', '機密', '檔案加密', '文字加密', 'aes', '加密檔案', '上密碼', 'encrypt', 'decrypt', '保險箱', '隱私', '安全傳檔'],
    icon: '🔐',
    loader: () => import('@/tools/secure-box/Index.vue'),
  },
  {
    id: 'image-fit-size',
    name: '照片壓到指定大小(KB)',
    category: 'workshop',
    description: '報名/考試/上傳系統限制「照片不得超過 ○○ KB」?自動壓到上限內、畫質最高,可一併限制最長邊 —— 全程在你瀏覽器處理,照片不上傳、無廣告、可批次。',
    keywords: ['壓縮', '縮小', '照片', '大頭照', '證件照', 'kb', '大小限制', '檔案太大', '上傳', '報名', '考試', '國考', '學測', '限制大小', '不超過', '壓到', '指定大小', '2mb', '100kb', '500kb', '減肥', '縮檔', 'compress', '上傳照片'],
    icon: '🗜️',
    loader: () => import('@/tools/image-fit-size/Index.vue'),
  },
  {
    id: 'heic-convert',
    name: 'HEIC 轉 JPG / PNG',
    category: 'workshop',
    description: 'iPhone 拍的 .heic 照片在 Windows、舊手機、很多網站都打不開?一鍵轉成 JPG/PNG —— 全程在你瀏覽器解碼,不上傳私密照片、無廣告、無浮水印、可批次。',
    keywords: ['heic', 'heif', 'iphone', '蘋果', '照片', '打不開', '無法開啟', '轉檔', '轉jpg', '轉png', '格式', 'jpg', 'png', '批次', '蘋果照片', '相片'],
    icon: '📷',
    loader: () => import('@/tools/heic-convert/Index.vue'),
  },
  {
    id: 'data-convert',
    name: '資料轉換工坊',
    category: 'workshop',
    description: 'CSV / JSON / Excel 三者互轉,直接讀寫 .xlsx —— 全程在你瀏覽器,不上傳名單訂單、無廣告、不限筆數。',
    keywords: ['csv', 'json', '轉換', '互轉', 'tsv', 'excel', 'xlsx', 'xls', '試算表', '資料', '表格', '逗號', '匯出', '格式轉換', '名單', '訂單'],
    icon: '🔄',
    loader: () => import('@/tools/data-convert/Index.vue'),
  },
  {
    id: 'sql-insert',
    name: 'SQL 語法產生器',
    category: 'workshop',
    description: '把 Excel / CSV / 試算表資料一鍵轉成 INSERT(可一併 CREATE TABLE)—— 自動跳脫引號、空欄轉 NULL、前導 0 的電話統編保留為文字,支援 MySQL/PostgreSQL/SQLite。全程在你瀏覽器,資料不上傳。',
    keywords: ['sql', 'insert', 'create table', '資料庫', 'mysql', 'postgresql', 'postgres', 'sqlite', '匯入', 'csv轉sql', 'excel轉sql', '建表', '語法', '產生', '塞資料', 'seed', '匯入資料庫', 'db', 'tsv'],
    icon: '🗄️',
    loader: () => import('@/tools/sql-insert/Index.vue'),
  },
  {
    id: 'cron-explain',
    name: 'Cron 表達式解讀',
    category: 'workshop',
    description: '排程那串「30 9 * * 1-5」到底多久跑一次?用白話中文說明,還直接算出接下來 5 次執行時間 —— 設 crontab/GitHub Actions/排程不再猜。全程在你瀏覽器計算,不上傳。',
    keywords: ['cron', 'crontab', '排程', '定時', '定時任務', 'schedule', '表達式', '解讀', '翻譯', '下次執行', 'github actions', 'cronjob', '每天', '每小時', '每分鐘', '週期', '定期'],
    icon: '⏰',
    loader: () => import('@/tools/cron-explain/Index.vue'),
  },
  {
    id: 'json-diff',
    name: 'JSON 結構比對',
    category: 'workshop',
    description: '貼上兩份 JSON,列出新增/刪除/變更的欄位與路徑 —— 物件鍵不分順序、排版差異自動忽略,比逐行 diff 更準。比對兩次 API 回應或兩版設定檔超實用。全程在你瀏覽器,含密鑰資料不上傳。',
    keywords: ['json', '比對', '比較', 'diff', '差異', '差別', '結構', 'compare', 'api', '回應', '設定檔', '版本', '變更', '哪裡不一樣', '物件', '欄位差異'],
    icon: '🔬',
    loader: () => import('@/tools/json-diff/Index.vue'),
  },
  {
    id: 'json-to-ts',
    name: 'JSON 轉 TypeScript 型別',
    category: 'workshop',
    description: '貼上 API 回應或任何 JSON,自動推斷出對應的 TypeScript interface —— 巢狀物件具名、陣列合併欄位、缺漏鍵標可選。寫前端/Node 免手刻型別。全程在你瀏覽器,含密鑰回應不上傳。',
    keywords: ['json', 'typescript', 'ts', '型別', 'interface', 'type', '轉型別', 'json轉ts', '產生型別', 'api', '回應', '定義', 'd.ts', '前端', 'node', '型別定義'],
    icon: '🧬',
    loader: () => import('@/tools/json-to-ts/Index.vue'),
  },
  {
    id: 'big5-convert',
    name: 'Big5 ↔ UTF-8 文字檔轉換',
    category: 'workshop',
    description: '早年 Windows 記事本存的 Big5/ANSI .txt 在 Mac、手機、網頁變亂碼?一鍵轉成 UTF-8(或反向轉回 Big5)—— 自動判斷來源編碼,全程在你瀏覽器轉換,檔案不上傳。',
    keywords: ['big5', 'utf-8', 'utf8', 'ansi', '編碼', '亂碼', '轉碼', '文字檔', 'txt', '記事本', '繁體', '中文亂碼', '檔案亂碼', '轉換', '編碼轉換', 'big5轉utf8', 'utf8轉big5', '舊檔', 'mac', '打不開', 'csv亂碼', 'srt亂碼'],
    icon: '🈯',
    loader: () => import('@/tools/big5-convert/Index.vue'),
  },
  {
    id: 'mojibake-fix',
    name: '亂碼修復',
    category: 'workshop',
    description: '把「中文變成 ä¸­æ–‡、é 變 Ã©」這類 UTF-8 被誤當西歐編碼的亂碼還原成正常文字 —— 全程在你瀏覽器,文字不上傳。',
    keywords: ['亂碼', '亂碼修復', '解碼', '編碼', 'utf-8', 'utf8', 'big5', 'latin', 'ansi', '問號', '火星文', '錯字', 'æ', 'ä', 'Ã', 'mojibake', '中文亂碼', '匯出亂碼', 'csv 亂碼'],
    icon: '🔣',
    loader: () => import('@/tools/mojibake-fix/Index.vue'),
  },
  {
    id: 'markdown-table',
    name: 'CSV ↔ Markdown 表格',
    category: 'workshop',
    description: '把 CSV/Excel 表格轉成 GitHub/Notion 風格的 Markdown 表格(欄位自動對齊),或把 Markdown 表格轉回 CSV —— 全程在你瀏覽器,不上傳。',
    keywords: ['markdown', 'md', '表格', 'table', 'csv轉markdown', 'markdown表格', 'github', 'notion', 'hackmd', 'readme', '文件', '對齊', '管線', 'pipe', '轉表格'],
    icon: '📋',
    loader: () => import('@/tools/markdown-table/Index.vue'),
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 預覽 / 轉 HTML',
    category: 'workshop',
    description: '即時把 Markdown 渲染成畫面與乾淨 HTML,可複製成 Word/Email 格式化內容、下載 .html(再列印成 PDF)—— 全程在你瀏覽器,不必貼到線上編輯器、不上傳。',
    keywords: ['markdown', 'md', '預覽', 'preview', '渲染', '轉html', 'markdown轉html', 'md轉html', 'readme', '筆記', 'notion', 'hackmd', '編輯器', 'editor', '排版', '轉pdf', '格式化', '所見即所得'],
    icon: '📝',
    loader: () => import('@/tools/markdown-preview/Index.vue'),
  },
  {
    id: 'regex-tester',
    name: '正規表達式測試器',
    category: 'workshop',
    description: '即時標示正規表達式比對到哪些文字,並把那串符號逐段翻成白話中文 —— 看懂、驗證、抓擷取群組。全程在你瀏覽器,測試文字不上傳。',
    keywords: ['正規表達式', '正則', '正規式', 'regex', 'regexp', '規則', '比對', '測試', '解讀', '說明', '驗證', '擷取', '群組', '比對文字', 'pattern', '樣式', '字串比對', '匹配', '正則表達式', '正規表示式'],
    icon: '🔤',
    loader: () => import('@/tools/regex-tester/Index.vue'),
  },
  {
    id: 'base-convert',
    name: '進位轉換器',
    category: 'workshop',
    description: '二進位、八進位、十進位、十六進位一次互轉,還支援任意 2–36 進位 —— 用 BigInt 運算,64 位元以上超大整數也不失真。全程在你瀏覽器計算,不上傳。',
    keywords: ['進位', '進位轉換', '二進位', '十六進位', '八進位', '十進位', 'binary', 'hex', 'hexadecimal', 'octal', 'decimal', 'bin', 'oct', 'dec', '0x', '0b', 'base', '基底', '位元', 'bit', '轉換', '進制', '進制轉換', '36進位', 'base36', 'base32'],
    icon: '🔢',
    loader: () => import('@/tools/base-convert/Index.vue'),
  },
  {
    id: 'hex-view',
    name: 'Hex 檢視器',
    category: 'workshop',
    description: '把檔案或文字攤開成「位移 + 十六進位 + ASCII」三欄,像 xxd / hexdump,看清檔頭魔術位元組、編碼、夾帶內容;也能把十六進位字串還原成文字。全程在你瀏覽器讀取排版,不上傳。',
    keywords: ['hex', 'hexdump', 'xxd', '十六進位', '檢視', '檢視器', 'hex viewer', 'hex editor', '位元組', 'byte', 'bytes', '檔頭', '魔術位元組', 'magic', 'binary', '二進位檔', 'ascii', 'dump', '十六進位還原', '看檔案', '原始位元組', 'raw'],
    icon: '🔣',
    loader: () => import('@/tools/hex-view/Index.vue'),
  },
  {
    id: 'text-hash',
    name: '文字雜湊值',
    category: 'workshop',
    description: '把一段文字算出 MD5 / SHA-1 / SHA-256 / SHA-384 / SHA-512 / CRC32 —— MD5、CRC32 也能離線算(瀏覽器內建加密不提供)。比對內容、產生識別碼用;全程在你瀏覽器,連密碼也不上傳。',
    keywords: ['雜湊', '雜湊值', 'hash', 'md5', 'sha', 'sha1', 'sha256', 'sha512', 'sha-256', 'crc32', 'crc', '校驗', '檢查碼', 'checksum', '加密', '摘要', 'digest', '指紋', 'fingerprint', '文字雜湊', '比對', 'etag'],
    icon: '#️⃣',
    loader: () => import('@/tools/text-hash/Index.vue'),
  },
  {
    id: 'cidr-calc',
    name: 'CIDR / 子網計算機',
    category: 'workshop',
    description: '輸入 IPv4 CIDR(如 192.168.1.10/24),立刻算出網路位址、廣播位址、可用主機範圍、子網路遮罩、萬用遮罩、主機數量,並判斷私有位址與等級。設定路由器/防火牆/伺服器必備;全程在你瀏覽器計算,不上傳。',
    keywords: ['cidr', '子網', '子網路', '網段', 'subnet', '遮罩', '子網路遮罩', 'netmask', 'mask', 'ip', 'ipv4', '網路位址', '廣播位址', 'broadcast', 'network', '主機數', 'wildcard', '萬用遮罩', '網路計算', 'ip計算', '/24', '私有ip', 'rfc1918'],
    icon: '🌐',
    loader: () => import('@/tools/cidr-calc/Index.vue'),
  },
  {
    id: 'chmod-calc',
    name: 'chmod 權限計算機',
    category: 'workshop',
    description: '把 Unix 檔案權限的八進位(755)和符號表示(rwxr-xr-x)雙向對照,勾選讀/寫/執行即時看到指令,支援 setuid/setgid/sticky 並附白話說明。不必死背 chmod 數字;全程在你瀏覽器計算,不上傳。',
    keywords: ['chmod', '權限', '檔案權限', 'permission', 'permissions', 'rwx', '755', '644', 'octal', '八進位', '符號', 'symbolic', 'setuid', 'setgid', 'sticky', 'umask', 'linux', 'unix', 'ls -l', '讀寫執行', 'mode'],
    icon: '🔐',
    loader: () => import('@/tools/chmod-calc/Index.vue'),
  },
  {
    id: 'json-schema',
    name: 'JSON Schema 產生器',
    category: 'workshop',
    description: '貼上範例 JSON,自動推斷出 JSON Schema(draft-07)—— 陣列合併所有元素結構、物件 required 取交集、可偵測 email/date/uri/uuid 格式。用於 API 合約與資料驗證;全程在你瀏覽器,不上傳。',
    keywords: ['json schema', 'jsonschema', 'schema', '結構', '驗證', 'validation', 'draft-07', 'api', '合約', 'contract', 'json', '產生 schema', '推斷', 'infer', 'openapi', '資料驗證', 'json 轉 schema'],
    icon: '📐',
    loader: () => import('@/tools/json-schema/Index.vue'),
  },
  {
    id: 'totp',
    name: 'TOTP 兩步驟驗證碼',
    category: 'workshop',
    description: '輸入 2FA 設定金鑰(base32)或 otpauth:// 連結,在本機算出當下的一次性驗證碼與倒數秒數(RFC 6238,等同 Google Authenticator)。手機不在身邊時臨時登入用 —— 密鑰是高度敏感資訊,本工具全程在你瀏覽器計算、不連網、不上傳、不儲存。',
    keywords: ['totp', '2fa', '兩步驟', '兩步驟驗證', '二階段驗證', '驗證碼', '一次性密碼', 'otp', 'hotp', 'google authenticator', 'authenticator', 'authy', 'otpauth', '動態密碼', 'mfa', '雙重認證', 'rfc6238', '驗證器', 'base32'],
    icon: '🔑',
    loader: () => import('@/tools/totp/Index.vue'),
  },
  {
    id: 'hmac',
    name: 'HMAC / Webhook 簽章驗證',
    category: 'workshop',
    description: '用密鑰對訊息算 HMAC-SHA1/256/512(十六進位 + Base64),驗證 webhook 是否真的來自服務方(GitHub / Stripe / LINE)。可貼收到的簽章定時比對,自動處理 sha256= 前綴。全程在你瀏覽器,密鑰與內容不上傳。',
    keywords: ['hmac', 'webhook', '簽章', '驗章', 'signature', '驗證', 'x-hub-signature', 'github', 'stripe', 'line', '簽名', 'sign', 'sha256', 'mac', '訊息鑑別', '密鑰雜湊', 'secret', '驗簽'],
    icon: '🔏',
    loader: () => import('@/tools/hmac/Index.vue'),
  },
  {
    id: 'url-parse',
    name: '網址解析 / 查詢字串編輯',
    category: 'workshop',
    description: '把網址拆成協定、主機、路徑、查詢參數,參數自動解碼列成表格可直接編輯,改完即時組回 —— 一鍵清掉 utm/fbclid 等追蹤碼。全程在你瀏覽器解析,不連網、不上傳。',
    keywords: ['網址', 'url', '解析', '查詢字串', 'query string', '參數', 'parameter', 'querystring', '編碼', '解碼', 'urldecode', 'urlencode', 'utm', 'fbclid', 'gclid', '追蹤碼', '拆解', '網址參數', '編輯', '組網址', 'parse'],
    icon: '🔗',
    loader: () => import('@/tools/url-parse/Index.vue'),
  },
  {
    id: 'escape-text',
    name: '文字跳脫 / 還原',
    category: 'workshop',
    description: '把含換行、引號的文字轉成可貼進 JSON/程式碼的跳脫字串,或把含 \\n、\\uXXXX、\\xXX 的字串還原成原文 —— 全程在你瀏覽器,不連網、不上傳。',
    keywords: ['跳脫', '逸出', 'escape', 'unescape', '還原', 'json字串', '字串跳脫', '反斜線', '換行', '\\n', '\\uxxxx', 'unicode跳脫', 'unicode escape', '\\xxx', '碼位', 'codepoint', '轉跳脫', '解跳脫', '字串編碼', 'stringify'],
    icon: '⌨️',
    loader: () => import('@/tools/escape-text/Index.vue'),
  },
  {
    id: 'html-to-text',
    name: 'HTML 轉純文字',
    category: 'workshop',
    description: '把從網頁、HTML 電子報複製來的內容去掉標籤、解開 &amp;amp; 等實體,保留段落換行,洗成乾淨純文字 —— 全程在你瀏覽器,不連網、不上傳。',
    keywords: ['html', '純文字', '去標籤', '去除html', '移除標籤', 'strip', 'tag', '網頁轉文字', 'html轉文字', '實體', 'entity', '解碼', '電子報', '清理', '貼上', 'plain text', '抓文字', '去html', '原始碼'],
    icon: '📰',
    loader: () => import('@/tools/html-to-text/Index.vue'),
  },
  {
    id: 'id-gen',
    name: '隨機 ID 產生器',
    category: 'workshop',
    description: 'UUID v4、ULID(含時間可排序)、Nano ID 一次大量產生,用密碼學等級亂數 —— 全程在本機產生,不連網、不上傳、不記錄(線上產生器可能偷記你的 ID)。',
    keywords: ['uuid', 'guid', 'ulid', 'nanoid', 'nano id', 'id', '識別碼', '唯一識別碼', '隨機id', '產生id', '主鍵', 'primary key', '訂單編號', '亂數id', 'v4', '識別字串', 'token', '隨機字串', '產生器'],
    icon: '🆔',
    loader: () => import('@/tools/id-gen/Index.vue'),
  },
  {
    id: 'duration',
    name: '時間長度轉換',
    category: 'workshop',
    description: '在人話(1天2小時30分)、時鐘(01:30:00)、ISO 8601(PT1H30M)、總秒/分/時之間互轉 —— 影片時長、工時、計時換算用。全程在你瀏覽器計算,不上傳。',
    keywords: ['時間長度', '時長', '時間轉換', '秒', '分鐘', '小時', '時:分:秒', 'hh:mm:ss', 'iso8601', 'duration', 'pt1h30m', '影片長度', '工時', '通話時間', '計時', '換算秒數', '幾分鐘', '幾小時', '總秒數', '時分秒'],
    icon: '⏳',
    loader: () => import('@/tools/duration/Index.vue'),
  },
  {
    id: 'timestamp-convert',
    name: 'Unix 時間戳記轉換',
    category: 'workshop',
    description: '把 log/資料庫/API 裡的 Unix 時間戳記(自動分辨秒/毫秒/微秒)轉成看得懂的日期,同時給台灣時間、UTC、ISO 8601 與相對時間 —— 全程在你瀏覽器,不上傳。',
    keywords: ['unix', 'timestamp', '時間戳記', '時間戳', 'epoch', '紀元', '秒數', '毫秒', '微秒', '時間轉換', '日期轉換', '轉時間', 'iso8601', 'iso 8601', 'utc', '時間轉日期', '日期轉時間', 'log時間', '1970', '時區'],
    icon: '🕐',
    loader: () => import('@/tools/timestamp-convert/Index.vue'),
  },
  {
    id: 'jwt-decode',
    name: 'JWT 解碼 / 檢視',
    category: 'workshop',
    description: '把 JSON Web Token 解開看標頭與內容、判斷是否過期,並可用密鑰在本機驗證 HMAC 簽章 —— 別再把正式環境的 token 貼到 jwt.io 等線上網站(等於外洩登入憑證),這支全程在你瀏覽器、不上傳。',
    keywords: ['jwt', 'json web token', 'token', '權杖', '解碼', '解析', '檢視', 'decode', 'oauth', 'bearer', '登入', '授權', 'access token', 'id token', 'payload', 'header', '簽章', 'hmac', 'hs256', 'rs256', 'exp', '過期', '驗證', 'jwt解碼', 'jwt.io'],
    icon: '🪙',
    loader: () => import('@/tools/jwt-decode/Index.vue'),
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML 互轉',
    category: 'workshop',
    description: 'JSON 與 YAML 雙向互轉,k8s / docker-compose / GitHub Actions 等設定檔常含密鑰 —— 全程在你瀏覽器轉換,不上傳機密設定、無廣告。',
    keywords: ['json', 'yaml', 'yml', '轉換', '互轉', '設定檔', 'config', 'kubernetes', 'k8s', 'docker', 'docker-compose', 'compose', 'github actions', 'ci', '密鑰', '金鑰', '格式轉換', 'json轉yaml', 'yaml轉json'],
    icon: '🧾',
    loader: () => import('@/tools/json-yaml/Index.vue'),
  },
  {
    id: 'data-extract',
    name: '文字資料抽取',
    category: 'workshop',
    description: '從一大段文字裡一次抓出所有 Email、網址、台灣手機、有效統一編號(統編經檢查碼驗證),自動去重 —— 全程在你瀏覽器,不上傳。',
    keywords: ['抽取', '擷取', '抓', 'email', '信箱', '電子郵件', '網址', 'url', '連結', '手機', '電話', '統編', '統一編號', '名單', '整理', '撈', 'extract', '蒐集'],
    icon: '🧲',
    loader: () => import('@/tools/data-extract/Index.vue'),
  },
  {
    id: 'json-flatten',
    name: 'JSON 攤平轉表格',
    category: 'workshop',
    description: '把巢狀 JSON(物件裡有物件、陣列)壓平成路徑欄位(addr.city、tags[0]),一列一筆轉成 CSV 丟進 Excel —— 全程在你瀏覽器,不上傳。',
    keywords: ['json', '攤平', '扁平化', 'flatten', '巢狀', 'json轉csv', 'json轉excel', 'json轉表格', 'api', '展開', '結構', '轉表格', 'unnest'],
    icon: '🪺',
    loader: () => import('@/tools/json-flatten/Index.vue'),
  },
  {
    id: 'table-stats',
    name: '表格統計 / 樞紐',
    category: 'workshop',
    description: '依某欄分組,馬上算出各組的筆數、加總、平均、最大最小 —— 等同 Excel 樞紐分析,免拉樞紐表;全程在你瀏覽器,資料不上傳。',
    keywords: ['樞紐', '樞紐分析', '統計', '分組', 'group by', '加總', '小計', '平均', '計數', '筆數', '彙總', '彙整', 'pivot', 'sum', 'count', 'csv', 'excel', '業績', '報表'],
    icon: '📊',
    loader: () => import('@/tools/table-stats/Index.vue'),
  },
  {
    id: 'table-merge',
    name: '表格合併 / VLOOKUP',
    category: 'workshop',
    description: '把兩份名單依共同欄位(Email、學號、統編)對起來併成一張,等同 Excel VLOOKUP,免寫公式 —— 全程在你瀏覽器,含個資的名單不上傳。',
    keywords: ['表格合併', '合併', 'vlookup', 'join', '對應', '比對合併', '兩個表格', '兩張表', 'csv', 'excel', '名單', '對起來', '查表', 'lookup', 'merge', '關聯'],
    icon: '🔗',
    loader: () => import('@/tools/table-merge/Index.vue'),
  },
  {
    id: 'table-clean',
    name: '表格清理工坊',
    category: 'workshop',
    description: '貼上 CSV/Excel 名單,一鍵去重複、刪空白列、篩選、排序、只留需要的欄,再匯出 CSV/JSON —— 全程在你瀏覽器,含個資的名單不上傳。',
    keywords: ['表格', '清理', 'csv', 'tsv', 'excel', '名單', '去重複', '重複', '篩選', '排序', '刪欄', '選欄', '整理', '去空白', '空列', '資料清理', 'dedupe', 'clean'],
    icon: '🧹',
    loader: () => import('@/tools/table-clean/Index.vue'),
  },
  {
    id: 'table-split',
    name: '表格拆分',
    category: 'workshop',
    description: '把一份大 CSV/Excel 名單拆成多份:按每 N 列平均切,或按某欄的值分組(依區域、業務、月份各自一份)—— 打包成 ZIP 或匯出單一多工作表 Excel。全程在你瀏覽器,含個資的名單不上傳。',
    keywords: ['表格', '拆分', '分割', '切割', '拆開', '分檔', '分組', '分群', 'csv', 'excel', 'xlsx', '名單', '訂單', '按欄位', '依欄位', '分區', '分業務', '每n列', '切成多份', 'split', '大檔', '分批'],
    icon: '📑',
    loader: () => import('@/tools/table-split/Index.vue'),
  },
  {
    id: 'list-compare',
    name: '名單比對 / 去重',
    category: 'workshop',
    description: '一份名單去重(找出重複幾次),或比對兩份名單的交集 / 差集 —— 對帳、找「誰還沒繳」最實用。全程在你瀏覽器,不上傳含個資的名單。',
    keywords: ['名單', '去重', '重複', '比對', '比較', '交集', '差集', '聯集', '對帳', '清單', 'email', '去除重複', '兩份', '找不同', '差異', '誰沒繳', '核對', 'dedupe', 'diff', '集合'],
    icon: '🗂️',
    loader: () => import('@/tools/list-compare/Index.vue'),
  },
  {
    id: 'vcard-maker',
    name: 'vCard 聯絡人產生器',
    category: 'workshop',
    description: '把單筆聯絡人,或一份 Excel/CSV 通訊錄,做成 .vcf 檔,直接匯入 iPhone / Android / Google / Apple / Outlook 聯絡人 —— 線上轉換器要你上傳含姓名電話的個資名單,本工具全程在你瀏覽器處理、不上傳。',
    keywords: ['vcard', 'vcf', '聯絡人', '通訊錄', '名片', '電話簿', '匯入聯絡人', 'contacts', '聯絡資訊', '匯入手機', 'google聯絡人', 'iphone聯絡人', 'csv轉vcard', 'excel轉聯絡人', '批次', '名單', '電話', '同學會', '社團'],
    icon: '👤',
    loader: () => import('@/tools/vcard-maker/Index.vue'),
  },
  {
    id: 'fake-data',
    name: '測試假資料產生器',
    category: 'workshop',
    description: '一鍵產生大量「擬真但完全虛構」的台灣個資(姓名、身分證、統編、手機、地址、Email…),身分證/統編檢查碼正確、能過格式驗證,但不對應任何真人 —— 開發測試別再拿真客戶資料,全程在你瀏覽器產生、不上傳,可指定種子重現、匯出 CSV/JSON。',
    keywords: ['假資料', '測試資料', '假個資', '假身分證', '假統編', '隨機資料', '範例資料', '示範資料', '亂數姓名', '產生器', '填表測試', 'mock', 'fake', 'dummy', 'test data', 'sample', '身分證產生', '假名單', '塞資料', '測資'],
    icon: '🧪',
    loader: () => import('@/tools/fake-data/Index.vue'),
  },
  {
    id: 'mail-merge',
    name: '合併列印 / 套印',
    category: 'workshop',
    description: '一份範本({{姓名}} 等佔位符)+ 一份名單,幫每個人各產生一段填好內容的文字 —— 年節祝福、開會通知、繳費提醒、邀請函不用一個個改名字。可直接貼 Excel,全程在你瀏覽器,名單不上傳。',
    keywords: ['合併列印', '套印', '範本', '樣板', '佔位符', '群發', '批次', '通知', '祝福', '邀請函', '名單', '客製', 'mail merge', 'template', '個人化', '繳費提醒', 'excel'],
    icon: '📨',
    loader: () => import('@/tools/mail-merge/Index.vue'),
  },
  {
    id: 'zip-studio',
    name: 'ZIP 工坊',
    category: 'workshop',
    description: '把多個檔案打包成一個 .zip,或把收到的 .zip 在本機解開檢視/取檔 —— 全程在你瀏覽器,不上傳、無廣告、不限檔數大小。',
    keywords: ['zip', '壓縮', '解壓', '解壓縮', '打包', '封存', 'archive', 'compress', 'extract', 'unzip', '附件', '多檔', '資料夾', '合併檔案'],
    icon: '🗜️',
    loader: () => import('@/tools/zip-studio/Index.vue'),
  },
  {
    id: 'batch-rename',
    name: '批次檔案改名',
    category: 'workshop',
    description: '一次替整批照片/文件改名:加前後綴、流水號(可補零)、改大小寫、把檔名裡某段文字換掉 —— 即時預覽舊→新,打包成 ZIP 下載。全程在你瀏覽器,檔案不上傳。',
    keywords: ['改名', '重新命名', '批次改名', '檔名', '重命名', '改檔名', '流水號', '編號', '序號', '前綴', '後綴', '取代', '大小寫', '照片改名', 'rename', 'batch', '一次改', '整批', '相片命名'],
    icon: '🔤',
    loader: () => import('@/tools/batch-rename/Index.vue'),
  },
  {
    id: 'file-split',
    name: '檔案分割 / 合併',
    category: 'workshop',
    description: '大檔寄不出去?把任何檔案切成小份分批傳(email/LINE/雲端有大小限制),收到後再合併還原 —— 全程在你瀏覽器處理,不上傳、無廣告。用標準 .001 命名,對方也能用內建指令合併。',
    keywords: ['分割', '切割', '合併', '切檔', '分檔', '大檔', '檔案太大', '太大', '寄不出去', '上傳限制', '附件太大', 'split', 'join', 'merge', '001', 'hjsplit', '分卷', '拆檔', '影片太大', '備份'],
    icon: '🪓',
    loader: () => import('@/tools/file-split/Index.vue'),
  },
  {
    id: 'screenshot-beautify',
    name: '截圖美化',
    category: 'workshop',
    description: '幫螢幕截圖加上漸層背景、圓角、陰影與 Mac 風格視窗列,貼進簡報、社群、部落格立刻變專業 —— 可直接 Ctrl+V 貼上,選好輸出比例(IG/YT 縮圖)。全程在你瀏覽器合成,圖片不上傳、無廣告、無浮水印。',
    keywords: ['截圖', '美化', '截圖美化', '背景', '漸層', '圓角', '陰影', '視窗列', '產品圖', '社群', 'ig', 'instagram', '簡報', '封面', '縮圖', 'mockup', 'beautify', 'screenshot', '加背景', '邊框', '截圖加框'],
    icon: '🖼️',
    loader: () => import('@/tools/screenshot-beautify/Index.vue'),
  },
  {
    id: 'image-stitch',
    name: '圖片拼接(長圖)',
    category: 'workshop',
    description: '把多張截圖、收據、對話接成一張長圖或長條 —— 縱向/橫向、可調間距對齊,全程在你瀏覽器合成,不上傳、無廣告、無浮水印。',
    keywords: ['拼接', '拼圖', '長圖', '合併圖片', '接圖', '截圖', '對話', 'line對話', '收據', '併圖', '組圖', '直向', '橫向', '長截圖', '合成', 'stitch', '對比圖'],
    icon: '🧩',
    loader: () => import('@/tools/image-stitch/Index.vue'),
  },
  {
    id: 'image-crop',
    name: '圖片裁切 / 旋轉',
    category: 'workshop',
    description: '把拍歪的照片轉正、裁掉多餘背景或框出重點 —— 旋轉、翻轉、拖曳裁切,全程在你瀏覽器處理,不上傳、無廣告、無浮水印,可隨時復原。',
    keywords: ['裁切', '裁剪', '剪裁', '旋轉', '轉正', '翻轉', '鏡像', '剪掉', '去背景', '框選', '照片', '圖片', '相片', 'crop', 'rotate', '橫的', '直的', '拍歪'],
    icon: '✂️',
    loader: () => import('@/tools/image-crop/Index.vue'),
  },
  {
    id: 'image-grid',
    name: 'IG 九宮格切圖',
    category: 'workshop',
    description: '把一張大圖切成九宮格,依序發到 Instagram 主頁就拼成一整張大圖牆 —— 自動算好發文順序、置中裁切,全程在你瀏覽器處理,圖片不上傳、無廣告、無浮水印。',
    keywords: ['九宮格', '切圖', '切割', 'ig', 'instagram', '主頁', '大圖', 'banner', '拼圖', '網格', 'grid', '分割圖片', '一張切多張', '版面', '個人檔案', '照片牆', '切九宮格'],
    icon: '⊞',
    loader: () => import('@/tools/image-grid/Index.vue'),
  },
  {
    id: 'id-photo',
    name: '證件照排版(4×6)',
    category: 'workshop',
    description: '把一張大頭照排成一張 4×6 相片紙的多張一吋/二吋證件照,300 DPI 可直接拿去沖洗 —— 全程在你瀏覽器處理,臉部照片不上傳、無廣告、無浮水印,免上傳到陌生網站或花錢請相館。',
    keywords: ['證件照', '大頭照', '一吋', '二吋', '證件', '護照照片', '身分證照片', '排版', '相片紙', '4x6', '4×6', '沖洗', '沖印', '大頭貼', '駕照照片', '履歷照', 'id photo', '證件相'],
    icon: '📸',
    loader: () => import('@/tools/id-photo/Index.vue'),
  },
  {
    id: 'text-table',
    name: '等寬純文字表格',
    category: 'workshop',
    description: '把 CSV/TSV(可從 Excel 整塊複製貼上)轉成在等寬字型下對齊的純文字表格(框線 / ASCII / 簡潔),貼進純文字 email、程式碼註解、Slack、README —— 純前端,不上傳。',
    keywords: ['純文字表格', 'ascii表格', 'ascii table', '等寬表格', '對齊', '文字表格', 'box drawing', '框線表格', 'plain text', 'csv轉表格', 'tsv', '程式碼註解', 'slack表格', 'readme', '終端機', '表格對齊'],
    icon: '📐',
    loader: () => import('@/tools/text-table/Index.vue'),
  },
  {
    id: 'dup-photos',
    name: '重複 / 相似照片偵測',
    category: 'workshop',
    description: '一次選多張照片,用感知雜湊找出重複或近似(改過尺寸、重新存檔、輕微壓縮)的照片,幫你清理相簿 —— 全程在你瀏覽器比對,照片不上傳。',
    keywords: ['重複照片', '相似照片', '找重複', '重複圖片', '清理相簿', '整理照片', '去重', '重複檔案', 'duplicate', '近似圖', '感知雜湊', 'phash', 'dhash', '相似度', '照片整理', '釋放空間'],
    icon: '🖼️',
    loader: () => import('@/tools/dup-photos/Index.vue'),
  },
  {
    id: 'ini-convert',
    name: 'INI / 設定檔 ↔ JSON',
    category: 'workshop',
    description: '把 INI 設定檔(含區段、註解)轉成 JSON,或把 JSON 物件倒成 INI —— 設定常含金鑰密碼,全程在你瀏覽器處理,不上傳。',
    keywords: ['ini', '設定檔', 'config', 'conf', '組態', '區段', 'section', 'json', '互轉', '轉換', '金鑰', '密碼', '設定轉json', 'desktop entry', 'cfg'],
    icon: '⚙️',
    loader: () => import('@/tools/ini-convert/Index.vue'),
  },
  {
    id: 'dotenv-convert',
    name: '.env ↔ JSON / shell 轉換',
    category: 'workshop',
    description: '把 .env 設定檔轉成 JSON 物件或 shell export,反之亦然;支援註解、引號與跳脫 —— .env 常含金鑰密碼,全程在你瀏覽器處理,不上傳。',
    keywords: ['env', '.env', 'dotenv', '環境變數', 'environment', 'json', 'shell', 'export', '設定檔', 'config', '金鑰', '密碼', 'ci', '互轉', '轉換'],
    icon: '🔑',
    loader: () => import('@/tools/dotenv-convert/Index.vue'),
  },
  {
    id: 'bg-color-key',
    name: '去純色背景 → 透明',
    category: 'workshop',
    description: '點一下背景色,把白底、綠幕、純色背景變透明,輸出透明 PNG —— 即時、免下載 AI 模型,最適合 logo、掃描的簽名/印章、線稿。全程在你瀏覽器,圖片不上傳。',
    keywords: ['去背', '去白底', '去背景', '純色去背', '綠幕', '去綠幕', '透明背景', '退底', '摳圖', 'logo去背', '簽名去背', '印章', '線稿', 'chroma', 'png', '背景變透明', '吸色'],
    icon: '🪄',
    loader: () => import('@/tools/bg-color-key/Index.vue'),
  },
  {
    id: 'color-scale',
    name: '色階產生器',
    category: 'workshop',
    description: '從一個主色生出 50~950 的明暗色階(設計系統色板),一鍵複製成 CSS 變數 / Tailwind 設定 / JSON —— 純前端計算,不連網、不上傳。',
    keywords: ['色階', '色板', '配色', '調色盤', 'palette', 'shade', 'tint', 'color scale', '主題色', '設計系統', 'tailwind', 'css變數', '深淺', '色票', '明暗', '50 900', 'design system'],
    icon: '🌈',
    loader: () => import('@/tools/color-scale/Index.vue'),
  },
  {
    id: 'svg-to-png',
    name: 'SVG → PNG / 點陣圖匯出',
    category: 'workshop',
    description: '把向量 SVG 在任意解析度轉成 PNG / JPG / WebP,可指定寬高、背景與品質 —— 全程在你瀏覽器用 canvas 繪製,SVG 不上傳、無廣告、無浮水印。',
    keywords: ['svg', 'svg轉png', 'svg轉圖', '向量轉點陣', '向量轉圖', 'png', 'jpg', 'webp', 'svg轉檔', 'svg匯出', '高解析', '放大不模糊', 'rasterize', '圖示轉png', 'logo轉png', 'icon'],
    icon: '🖌️',
    loader: () => import('@/tools/svg-to-png/Index.vue'),
  },
  {
    id: 'image-base64',
    name: 'Base64 / Data URI 圖片互轉',
    category: 'workshop',
    description: '把圖片轉成 Base64 / Data URI 字串(內嵌進 HTML/CSS/Markdown,附現成片段),或把 Data URI / Base64 還原成可下載的圖片 —— 全程在你瀏覽器,圖片不上傳。',
    keywords: ['base64', 'data uri', 'datauri', 'data url', '圖片轉base64', 'base64轉圖片', '內嵌圖片', '圖片編碼', '圖片解碼', '轉字串', 'img', 'css background', 'inline image', '簽名檔', 'email圖片', '編碼', '解碼'],
    icon: '🔤',
    loader: () => import('@/tools/image-base64/Index.vue'),
  },
  {
    id: 'favicon-gen',
    name: '網站圖示 / Favicon 產生器',
    category: 'workshop',
    description: '上傳一張圖,輸出 favicon.ico(內含 16/32/48 多尺寸)、apple-touch-icon 與 PWA 圖示(192/512),附可直接貼上的 HTML —— 全程在你瀏覽器處理,logo 不上傳、無廣告、不綁追蹤。',
    keywords: ['favicon', 'ico', '網站圖示', '圖示', 'icon', '網站小圖', '分頁圖示', 'apple-touch-icon', 'pwa', '網站logo', 'logo轉ico', '製作favicon', '圖轉ico', '網頁圖示'],
    icon: '🌐',
    loader: () => import('@/tools/favicon-gen/Index.vue'),
  },
  {
    id: 'audio-studio',
    name: '音訊工坊',
    category: 'workshop',
    description: '載入音檔,裁剪片段(做鈴聲)、淡入淡出、調音量、轉單聲道,匯出無失真 WAV —— 全程在你瀏覽器,音檔不上傳、無廣告、無浮水印、不限時長。',
    keywords: ['音訊', '音樂', '音檔', '聲音', '剪輯', '裁剪', '剪音樂', '剪歌', '鈴聲', '來電鈴聲', '截取', '淡入', '淡出', '音量', '正規化', '轉單聲道', 'mp3', 'wav', 'm4a', '剪音訊', '音訊剪輯', 'audio', 'trim'],
    icon: '🎵',
    loader: () => import('@/tools/audio-studio/Index.vue'),
  },
  {
    id: 'subtitle-studio',
    name: '字幕工坊(SRT/VTT)',
    category: 'workshop',
    description: 'SRT ↔ WebVTT 互轉、整體平移對時(字幕快/慢幾秒)、速率縮放、自動重新編號 —— 全程在你瀏覽器處理,字幕內容不上傳、無廣告、免註冊。',
    keywords: ['字幕', 'srt', 'vtt', 'webvtt', '字幕轉檔', '字幕格式', '對時', '平移', '時間軸', '同步', '不同步', '快了', '慢了', '延遲', '影片字幕', '電影字幕', '轉換', '字幕檔'],
    icon: '🎬',
    loader: () => import('@/tools/subtitle-studio/Index.vue'),
  },
  {
    id: 'text-diff',
    name: '文字差異比對',
    category: 'workshop',
    description: '比對合約改版、條款、規格新舊兩版,逐行加逐字標出改了哪裡 —— 全程在你瀏覽器,不上傳機密文字、無廣告。',
    keywords: ['比對', '差異', '差別', '比較', 'diff', '兩份', '新舊', '改版', '版本', '合約', '條款', '對照', '哪裡不同', '逐字', '文字比對', 'compare', '異動'],
    icon: '📝',
    loader: () => import('@/tools/text-diff/Index.vue'),
  },
  {
    id: 'image-redact',
    name: '圖片遮蔽(塗黑/馬賽克)',
    category: 'workshop',
    description: '分享截圖前,把身分證、地址、帳號等個資塗黑或打馬賽克 —— 全程在你瀏覽器,不上傳、真的把像素塗掉、無廣告。',
    keywords: ['遮蔽', '塗黑', '馬賽克', '打碼', '去碼', '隱私', '個資', '截圖', '遮住', '隱藏', '模糊', '身分證', '帳號', '保護'],
    icon: '🌫️',
    loader: () => import('@/tools/image-redact/Index.vue'),
  },
  {
    id: 'text-redact',
    name: '文字個資遮蔽',
    category: 'anti-scam',
    description: '貼上對話/單據文字,自動找出身分證、手機、信用卡、Email 並打碼 —— 轉貼客服對話、分享截圖文字前先遮個資。全程在你瀏覽器以規則比對,不上傳;身分證/信用卡會驗證檢查碼避免誤判。',
    keywords: ['個資', '遮蔽', '打碼', '去識別', '隱私', '身分證', '手機', '信用卡', '卡號', 'email', '電子郵件', '遮個資', '對話', '客服', '截圖文字', '保護個資', '去除個資', '罩'],
    icon: '🕵️',
    loader: () => import('@/tools/text-redact/Index.vue'),
  },
  {
    id: 'image-watermark',
    name: '證件浮水印加註',
    category: 'workshop',
    description: '交付證件影本前,斜向重複加註用途(例:僅供開戶使用)防盜用 —— 全程在你瀏覽器,文字直接燒進像素、不上傳、無廣告、可批次。',
    keywords: ['浮水印', '證件', '影本', '加註', '防盜用', '身分證', '開戶', '門號', '租屋', '影印', '騎縫', '劃線', '保護', '批次', 'watermark'],
    icon: '🖋️',
    loader: () => import('@/tools/image-watermark/Index.vue'),
  },
  {
    id: 'qr-generate',
    name: 'QR Code 產生器',
    category: 'workshop',
    description: '把網址、WiFi 連線、聯絡資訊做成 QR Code,可下載 PNG —— 直接編碼你的原始內容,不像多數線上產生器偷塞追蹤短網址轉址。全程在你瀏覽器,不上傳。',
    keywords: ['qr', 'qrcode', 'qr code', '二維碼', '條碼', '產生', '製作', 'wifi', '無線網路', '聯絡', '名片', 'vcard', '網址', '連結', '掃描'],
    icon: '🔳',
    loader: () => import('@/tools/qr-generate/Index.vue'),
  },
  {
    id: 'qr-batch',
    name: '批次 QR Code',
    category: 'workshop',
    description: '一份清單一次做成很多個 QR Code(每行一筆),打包成 ZIP 圖片或排成可直接列印的 A4 標籤頁 —— 活動桌號、財產編號、商品連結用。全程在你瀏覽器產生,清單不上傳、不轉址、不追蹤。',
    keywords: ['qr', 'qrcode', 'qr code', '二維碼', '批次', '大量', '一次', '清單', '名單', '桌號', '座位', '財產編號', '標籤', '列印', 'a4', '貼紙', '菜單', '問卷', 'batch', '多個', '產生'],
    icon: '🔳',
    loader: () => import('@/tools/qr-batch/Index.vue'),
  },
  {
    id: 'barcode-generate',
    name: '條碼產生器',
    category: 'workshop',
    description: '把料號、商品編號、書本 ISBN 做成一維條碼(CODE128 / EAN-13 / EAN-8 / UPC / CODE39 / ITF-14),可下載向量 SVG 或高解析 PNG 印標籤 —— 全程在你瀏覽器產生,不上傳、無廣告、不偷塞追蹤,輸入少打檢查碼自動補上。',
    keywords: ['條碼', '一維條碼', 'barcode', 'code128', 'ean', 'ean13', 'ean-13', 'ean8', 'upc', 'code39', 'itf', '商品條碼', '料號', '貨號', '標籤', '印標籤', 'isbn', '書號', '產生條碼', '製作條碼', '檢查碼'],
    icon: '🏷️',
    loader: () => import('@/tools/barcode-generate/Index.vue'),
  },
  {
    id: 'text-clean',
    name: '文字清理工坊',
    category: 'workshop',
    description: '從 PDF/網頁/LINE 貼上的文字常夾帶看不見的零寬字元、全形英數、多餘空白 —— 一鍵清乾淨,即時統計字數。全程在你瀏覽器,不上傳、無廣告。',
    keywords: ['文字', '清理', '整理', '去空白', '空行', '零寬', '不可見字元', '全形', '半形', '大小寫', '字數統計', '字數', '計數', '去重', '貼上', '格式化'],
    icon: '🧹',
    loader: () => import('@/tools/text-clean/Index.vue'),
  },
  {
    id: 'char-inspect',
    name: '隱形字元 / Unicode 檢視器',
    category: 'workshop',
    description: '貼上文字,逐字揪出看不見的零寬字元、異常空白、文字方向控制字元,以及長得像 ASCII 的形近字(釣魚網址、假冒帳號常用)—— 解決「兩個字串看起來一樣卻不相等」,也能防冒名。全程在你瀏覽器,不上傳。',
    keywords: ['隱形字元', '看不見的字元', '零寬', 'zero width', '零寬字元', 'unicode', '碼位', 'codepoint', '字元', '形近字', '混淆', 'confusable', '同形異字', 'homograph', '釣魚', '假冒', '冒名', '方向字元', 'bidi', 'rlo', '亂碼', '比對', '不相等', '隱藏字元', '全形空格', 'nbsp', '不斷行空格', '字數', '檢視', '檢測'],
    icon: '🔎',
    loader: () => import('@/tools/char-inspect/Index.vue'),
  },
  {
    id: 'text-stats',
    name: '文字統計 / 字數統計',
    category: 'workshop',
    description: '貼上文章,正確算出中文字數(逐字計,不像多數工具用空白切詞而把中文算錯)、英文單字、字元、行/段/句、UTF-8 位元組與預估閱讀時間,還能設字數上限即時倒數 —— 作文、自傳、書審、貼文字數限制好用。全程在你瀏覽器,不上傳。',
    keywords: ['字數', '字數統計', '文字統計', '算字數', '計字數', '幾個字', '字數限制', '字數上限', '中文字數', '英文單字', 'word count', '字元數', '行數', '段落', '句數', '閱讀時間', '作文', '自傳', '書審', '報告', '貼文', '字數計算', '統計字數'],
    icon: '🔢',
    loader: () => import('@/tools/text-stats/Index.vue'),
  },
  {
    id: 'line-tools',
    name: '清單加工(每行轉清單)',
    category: 'workshop',
    description: '把貼上的一欄資料(每行一筆,常從 Excel 複製)變成可直接貼用的清單:SQL IN 清單 (\'a\',\'b\')、逗號清單、JSON 字串陣列、Markdown/編號清單 —— 可去空白行、去重、加引號(自動逸出)、加前後綴。全程在你瀏覽器,不上傳內部名單/ID。',
    keywords: ['清單', '每行', '一欄', '逗號清單', 'sql in', 'in 清單', '陣列', 'json 陣列', '加引號', '前綴', '後綴', '編號', 'markdown 清單', '去重', '換行', '串成一行', '逗號分隔', '一行一筆', '貼上', '加工', 'list'],
    icon: '📋',
    loader: () => import('@/tools/line-tools/Index.vue'),
  },
  {
    id: 'case-convert',
    name: '命名格式轉換(camelCase/snake_case)',
    category: 'workshop',
    description:
      '把變數名/欄位名/詞句在 camelCase、PascalCase、snake_case、CONSTANT_CASE、kebab-case、Title Case 等命名慣例之間互轉,自動辨識原本格式並拆字;支援多行批次(每行一筆),一次轉一整欄。全程在你瀏覽器,不上傳。',
    keywords: [
      '命名',
      '命名慣例',
      '命名規則',
      '大小寫',
      '大小寫轉換',
      'camelCase',
      '駝峰',
      '小駝峰',
      '大駝峰',
      'PascalCase',
      'snake_case',
      '蛇形',
      '底線命名',
      'kebab-case',
      '連字號',
      'CONSTANT_CASE',
      '常數命名',
      '全大寫',
      'Title Case',
      '變數名',
      '欄位名',
      'case converter',
      '格式轉換',
    ],
    icon: '🔡',
    loader: () => import('@/tools/case-convert/Index.vue'),
  },
  {
    id: 'lorem-ipsum',
    name: '假文 / Lorem Ipsum 產生器',
    category: 'workshop',
    description:
      '做版面/設計稿時要填的「假內文」—— 拉丁 Lorem Ipsum(可選經典開頭)＋中文假文(多數線上工具只有拉丁文,這裡能產生中文版面用的佔位文字)。可選段落/句子/字數量,固定種子可重現同一批。全程在你瀏覽器,不上傳。',
    keywords: [
      '假文',
      '假內文',
      '佔位文字',
      '佔位符',
      'placeholder',
      'lorem',
      'lorem ipsum',
      '亂數文字',
      '範例文字',
      '填充文字',
      '中文假文',
      '排版',
      '版面',
      '設計稿',
      'mockup',
      'dummy text',
      'filler',
      '亂文',
    ],
    icon: '📃',
    loader: () => import('@/tools/lorem-ipsum/Index.vue'),
  },
  {
    id: 'box-shadow',
    name: 'CSS 陰影產生器(box-shadow)',
    category: 'workshop',
    description:
      '視覺化調出 CSS box-shadow —— 多層陰影、X/Y 位移、模糊、擴散、顏色＋透明度、內陰影(inset),即時預覽方塊效果,一鍵複製可直接貼用的 CSS。附柔和卡片/懸浮/內凹/霓虹範本。補齊漸層/色階視覺工坊系列。全程在你瀏覽器,不上傳。',
    keywords: [
      'box-shadow',
      '陰影',
      'css 陰影',
      '投影',
      '陰影產生器',
      'shadow',
      'drop shadow',
      'inset',
      '內陰影',
      '霓虹',
      '光暈',
      'glow',
      '卡片陰影',
      '懸浮',
      'css 產生器',
      '前端',
      'ui',
    ],
    icon: '🌒',
    loader: () => import('@/tools/box-shadow/Index.vue'),
  },
  {
    id: 'slugify',
    name: '網址代稱 / Slug 產生器',
    category: 'workshop',
    description:
      '把文章標題/任意文字洗成適合放進網址的 slug —— 去除重音符號(café→cafe)、標點空白轉連字號、收斂去頭尾,可選小寫、保留中文、長度上限。部落格/CMS 文章網址、錨點 id 用。支援多行批次。全程在你瀏覽器,不上傳。',
    keywords: [
      'slug',
      'slugify',
      '網址代稱',
      '網址友善',
      '網址',
      'url',
      '永久連結',
      'permalink',
      '錨點',
      'anchor',
      'id',
      '文章網址',
      '部落格',
      'cms',
      '去重音',
      '標題轉網址',
      'seo',
      '連字號',
    ],
    icon: '🔗',
    loader: () => import('@/tools/slugify/Index.vue'),
  },
  {
    id: 'pangu-spacing',
    name: '中文排版(中英自動加空格)',
    category: 'workshop',
    description:
      '在中日韓文字與英文字母/數字之間自動補上半形空格(俗稱「盤古之白」),讓中英混排的文章、貼文、文件更易讀 —— 「在GitHub上有100顆星」→「在 GitHub 上有 100 顆星」。可重複套用結果不變、保留標點與換行。全程在你瀏覽器,不上傳。',
    keywords: [
      '盤古之白',
      '盤古',
      'pangu',
      '中英空格',
      '中英文空格',
      '加空格',
      '空格',
      '中文排版',
      '排版',
      '中英混排',
      '中英文',
      '自動空格',
      '中文英文之間',
      '可讀性',
      '文案',
      '貼文',
      '盤古之白加空格',
    ],
    icon: '🈳',
    loader: () => import('@/tools/pangu-spacing/Index.vue'),
  },
  {
    id: 'text-speech',
    name: '文字朗讀',
    category: 'life',
    description: '把貼上的文字用語音唸出來,給視力不便、眼睛累或想「用聽的」的長輩與家人 —— 用瀏覽器內建語音,全程在你的裝置發聲,文字不上傳、免帳號。速度音調可調。',
    keywords: ['朗讀', '唸出來', '念出來', '語音', '讀文章', '聽', '文字轉語音', 'tts', '報讀', '視障', '老花', '長輩', '念', '發音', 'speak', 'text to speech', '有聲'],
    icon: '🔊',
    loader: () => import('@/tools/text-speech/Index.vue'),
  },
  {
    id: 'exif-viewer',
    name: '照片隱私檢視器(EXIF)',
    category: 'anti-scam',
    description: '分享照片前先看它偷偷夾帶了什麼:拍攝時間、手機型號,甚至 GPS 拍攝地點 —— 含定位的照片會洩漏你家位置。全程在你瀏覽器解析,照片不上傳。',
    keywords: ['exif', '照片', '隱私', 'gps', '定位', '地點', '拍攝資訊', '中繼資料', 'metadata', '洩漏', '位置', '跟蹤', '相機', '型號', '去exif', '檢視'],
    icon: '📍',
    loader: () => import('@/tools/exif-viewer/Index.vue'),
  },
  {
    id: 'exif-strip',
    name: '照片個資清除(去 EXIF)',
    category: 'anti-scam',
    description: '不重新壓縮、畫質完全不變,直接移除照片夾帶的 EXIF/GPS 定位/拍攝時間/相機型號 —— 上傳社群或二手交易前先清掉,避免洩漏住家位置。全程在你瀏覽器處理,照片不上傳、可批次。',
    keywords: ['exif', '去exif', '去除exif', '個資', '隱私', 'gps', '定位', '位置', '住家', '中繼資料', 'metadata', '拍攝資訊', '清除', '移除', '照片', '相片', 'jpg', 'png', '二手', '社群', '洩漏', 'xmp', '不壓縮', '畫質不變', '批次'],
    icon: '🧹',
    loader: () => import('@/tools/exif-strip/Index.vue'),
  },
  {
    id: 'qr-decode',
    name: 'QR Code 解碼(看網址)',
    category: 'anti-scam',
    description: '把含 QR Code 的截圖或照片解出裡面的內容 —— 陌生 QR 直接掃容易被導到釣魚網站,先看清楚網址再決定要不要開。全程在你瀏覽器解碼,圖片不上傳。',
    keywords: ['qr', 'qrcode', 'qr code', '二維碼', '掃描', '解碼', '解析', '讀取', '讀qr', '看網址', '可疑', '釣魚', '停車單', '假帳單', 'decode', 'scan'],
    icon: '📷',
    loader: () => import('@/tools/qr-decode/Index.vue'),
  },
  {
    id: 'link-check',
    name: '可疑網址檢查器',
    category: 'anti-scam',
    description: '收到怪怪的連結?貼上來,馬上看出假冒網域、釣魚、短網址等詐騙特徵。',
    keywords: ['詐騙', '可疑', '網址', '連結', '釣魚', '假網站', '簡訊', '安全', '查證', '假冒', '釣魚網站'],
    icon: '🛡️',
    loader: () => import('@/tools/link-check/Index.vue'),
  },
  {
    id: 'url-clean',
    name: '網址清理 / 看穿轉址',
    category: 'anti-scam',
    description: '把 google.com/url、Facebook l.php、Outlook safelinks 等「轉址包裝」一層層拆開,先看清楚連結最後連去哪;順手清掉 utm、fbclid 等追蹤參數讓分享連結更乾淨。全程在你瀏覽器,不連網、不上傳。',
    keywords: ['網址', '連結', '轉址', '跳轉', '重新導向', '看穿', '真正連到', '追蹤', '追蹤碼', 'utm', 'fbclid', 'gclid', '清理', '乾淨', '縮網址', '展開', '參數', '隱私', 'redirect', '釣魚', '安全連結'],
    icon: '🔗',
    loader: () => import('@/tools/url-clean/Index.vue'),
  },
  {
    id: 'punycode',
    name: 'Punycode / IDN 網域檢視',
    category: 'anti-scam',
    description: '把 xn-- 開頭的網域解回真正顯示的文字,揪出用西里爾/希臘字母假冒英文(例 apple→аpple)的形近字釣魚網域 —— 全程在你瀏覽器解析,不連網、不上傳。',
    keywords: ['punycode', 'idn', 'xn--', '網域', '網址', '釣魚', '假網站', '假冒', '形近字', '同形異字', 'homograph', '西里爾', 'cyrillic', '混淆', 'confusable', '國際化網域', '解碼', '看穿', '假網域', '詐騙網址', 'idna'],
    icon: '🌐',
    loader: () => import('@/tools/punycode/Index.vue'),
  },
  {
    id: 'sms-check',
    name: '詐騙簡訊檢查',
    category: 'anti-scam',
    description: '把可疑的簡訊或 LINE 訊息貼上來,辨識常見詐騙話術,並自動檢查裡面的連結。',
    keywords: ['詐騙', '簡訊', 'LINE', '訊息', '話術', '可疑', '假冒', '解除分期', '包裹', '中獎', '查證'],
    icon: '💬',
    loader: () => import('@/tools/sms-check/Index.vue'),
  },
  {
    id: 'email-check',
    name: '郵件來源檢視 / 防冒名',
    category: 'anti-scam',
    description: '貼上可疑信件的郵件原始碼/標頭,解析寄件網域、回覆地址與 SPF/DKIM/DMARC 驗證,標出冒名詐騙破綻。全程在你瀏覽器判讀、不上傳。',
    keywords: ['email', '郵件', '信件', '電子郵件', '標頭', 'header', '原始碼', '寄件者', '冒名', '偽冒', '釣魚', 'phishing', 'spf', 'dkim', 'dmarc', '網域', '退信', '回覆地址', '詐騙信', '假信'],
    icon: '📧',
    loader: () => import('@/tools/email-check/Index.vue'),
  },
  {
    id: 'scam-guide',
    name: '常見詐騙手法圖鑑',
    category: 'anti-scam',
    description: '解除分期、假投資、假檢警、包裹簡訊…一次看懂常見詐騙怎麼運作、破綻在哪、該怎麼做。轉給長輩看最有用。',
    keywords: ['詐騙', '手法', '圖鑑', '防詐', '反詐騙', '165', '假投資', '假檢警', '解除分期', '包裹', '一頁式', '假交友', '人頭帳戶', '懶人包', '長輩'],
    icon: '📖',
    loader: () => import('@/tools/scam-guide/Index.vue'),
  },
  {
    id: 'phone-check',
    name: '電話號碼檢視 / 防詐',
    category: 'anti-scam',
    description: '接到陌生來電?貼上號碼,看清楚它是手機、市話、免付費還是「付費語音」,並標出常見詐騙警訊(國際來電卻自稱國內機構、回撥被收高額費用等)。全程在你瀏覽器判讀、不上傳,附 165 官方查證連結。',
    keywords: ['電話', '號碼', '來電', '陌生來電', '可疑電話', '詐騙電話', '騷擾', '手機', '市話', '0204', '付費語音', '0800', '+886', '國際來電', '回撥', '查號', '165', '防詐'],
    icon: '📞',
    loader: () => import('@/tools/phone-check/Index.vue'),
  },
  {
    id: 'file-type',
    name: '檔案真實類型檢測',
    category: 'anti-scam',
    description: '讀檔頭「魔術位元組」判斷檔案實際是什麼格式,並和副檔名比對 —— 抓出把惡意程式改名成 .jpg、.pdf 的偽裝(詐騙常見手法)。副檔名能亂改,檔頭騙不了人。全程在你瀏覽器讀取,不上傳檔案。',
    keywords: ['檔案類型', '副檔名', '偽裝', '假檔', '惡意程式', '病毒', 'exe', '改副檔名', '魔術位元組', 'magic number', '真實格式', '附件', '可疑檔案', '掉包', '騙', '辨識檔案', 'file type'],
    icon: '🔬',
    loader: () => import('@/tools/file-type/Index.vue'),
  },
  {
    id: 'file-checksum',
    name: '檔案校驗碼 / 完整性驗證',
    category: 'anti-scam',
    description: '下載安裝檔後,算出 SHA-256/SHA-1/SHA-512 雜湊值,和官方公布的校驗碼比對,確認檔案沒被掉包或植入惡意程式 —— 全程在你瀏覽器計算,檔案不上傳。',
    keywords: ['校驗碼', '雜湊', 'hash', 'sha256', 'sha-256', 'sha1', 'sha512', '完整性', '驗證', '驗檔', '檔案指紋', '竄改', '掉包', '安裝檔', '校驗', 'checksum', '指紋', '比對'],
    icon: '🔐',
    loader: () => import('@/tools/file-checksum/Index.vue'),
  },
  {
    id: 'card-check',
    name: '信用卡卡號檢核',
    category: 'anti-scam',
    description: '用 Luhn 檢查碼驗證信用卡/金融卡卡號有沒有打對(抓少打、多打、錯一碼),並判斷發卡組織(Visa/Mastercard/JCB…)。全程本機計算、不上傳、不儲存,並提醒卡號+期限+末三碼湊齊就會被盜刷。',
    keywords: ['信用卡', '卡號', '金融卡', '檢核', '驗證', 'luhn', '檢查碼', '打錯', 'visa', 'mastercard', '萬事達', 'jcb', '美國運通', 'amex', '銀聯', 'unionpay', '卡別', '盜刷', '發卡組織', 'card'],
    icon: '💳',
    loader: () => import('@/tools/card-check/Index.vue'),
  },
  {
    id: 'severance-pay',
    name: '資遣費試算',
    category: 'labor',
    description: '輸入年資與平均工資,算出新制/舊制資遣費,並標明法規依據。',
    keywords: ['資遣費', '資遣', '遣散費', '被資遣', '裁員', '解僱', '離職金', '勞退', '年資'],
    icon: '💼',
    loader: () => import('@/tools/severance-pay/Index.vue'),
  },
  {
    id: 'annual-leave',
    name: '特休天數計算',
    category: 'labor',
    description: '依到職日與年資,算出依勞基法第38條應有的特別休假天數。',
    keywords: ['特休', '特別休假', '年假', '休假天數', '可以休幾天', '年資', '勞基法38'],
    icon: '🏖️',
    loader: () => import('@/tools/annual-leave/Index.vue'),
  },
  {
    id: 'overtime-pay',
    name: '加班費計算',
    category: 'labor',
    description: '依勞基法第24條,計算平日與休息日加班的加給金額。',
    keywords: ['加班費', '加班', 'OT', '延長工時', '休息日加班', '時薪', '勞基法24'],
    icon: '⏰',
    loader: () => import('@/tools/overtime-pay/Index.vue'),
  },
  {
    id: 'work-hours',
    name: '工時時數表',
    category: 'labor',
    description: '加總多段班別的工時,自動處理跨午夜夜班、扣除休息時間,可選填時薪估算原始工資 —— 打工/排班族對帳薪資、報工時用。全程在你瀏覽器計算,不上傳班表。',
    keywords: ['工時', '時數', '上班時間', '打卡', '排班', '班表', '加總', '幾小時', '夜班', '跨午夜', '休息', '打工', '兼職', '時薪', '報工時', '上班', '下班', '工作時間'],
    icon: '⏱️',
    loader: () => import('@/tools/work-hours/Index.vue'),
  },
  {
    id: 'leave-deduction',
    name: '請假扣薪試算',
    category: 'labor',
    description: '請事假、病假會被扣多少薪水?選假別、填天數,馬上算出應扣金額與仍可領的工資。',
    keywords: ['請假', '扣薪', '事假', '病假', '生理假', '婚假', '喪假', '特休', '家庭照顧假', '半薪', '無薪', '日薪', '時薪', '薪水'],
    icon: '🗓️',
    loader: () => import('@/tools/leave-deduction/Index.vue'),
  },
  {
    id: 'income-tax',
    name: '綜所稅速算',
    category: 'health-tax',
    description: '輸入綜合所得淨額,用財政部速算公式算出應納所得稅與有效稅率。',
    keywords: ['所得稅', '綜所稅', '報稅', '稅額', '級距', '速算', '繳稅', '綜合所得'],
    icon: '🧮',
    loader: () => import('@/tools/income-tax/Index.vue'),
  },
  {
    id: 'nhi-supplement',
    name: '二代健保補充保費',
    category: 'health-tax',
    description: '計算獎金、租金、股利、利息等收入要扣的二代健保補充保費。',
    keywords: ['二代健保', '補充保費', '健保', '獎金', '股利', '租金', '利息', '兼職'],
    icon: '🩺',
    loader: () => import('@/tools/nhi-supplement/Index.vue'),
  },
  {
    id: 'loan-calc',
    name: '貸款試算',
    category: 'finance',
    description: '房貸、車貸的每月應繳、總利息試算,支援本息/本金均攤與寬限期。',
    keywords: ['貸款', '房貸', '車貸', '利息', '每月還款', '月付', '本息均攤', '本金均攤', '寬限期'],
    icon: '🏠',
    loader: () => import('@/tools/loan-calc/Index.vue'),
  },
  {
    id: 'savings-interest',
    name: '定存複利試算',
    category: 'finance',
    description: '輸入本金、年利率、年數與複利次數,算出到期本利和與總利息。',
    keywords: ['定存', '複利', '利息', '存款', '本利和', '年利率', '理財', '單利'],
    icon: '🏦',
    loader: () => import('@/tools/savings-interest/Index.vue'),
  },
  {
    id: 'labor-pension-self',
    name: '勞退自提節稅試算',
    category: 'finance',
    description: '試算勞退自願提繳(上限 6%)金額,以及可省下的所得稅。',
    keywords: ['勞退', '自提', '自願提繳', '退休金', '節稅', '6%', '勞工退休金'],
    icon: '🐷',
    loader: () => import('@/tools/labor-pension-self/Index.vue'),
  },
  {
    id: 'labor-pension-annuity',
    name: '勞保老年年金試算',
    category: 'finance',
    description: '退休後勞保每月能領多少?輸入平均投保薪資與年資,兩式擇優算出月領金額,含提前/延後請領調整。',
    keywords: ['勞保', '老年年金', '退休金', '退休', '月退', '勞保年金', '請領', '投保薪資', '年資', '老年給付', '勞保老年'],
    icon: '👵',
    loader: () => import('@/tools/labor-pension-annuity/Index.vue'),
  },
  {
    id: 'installment-apr',
    name: '分期實際利率(APR)',
    category: 'finance',
    description: '「分期 0 利率」其實不便宜?輸入手續費,算出信用卡/分期付款的真實年利率。',
    keywords: ['分期', '利率', 'APR', '手續費', '信用卡', '免利率', '零利率', '實質利率', '年利率', '分期付款', '免息'],
    icon: '💳',
    loader: () => import('@/tools/installment-apr/Index.vue'),
  },
  {
    id: 'tw-id-check',
    name: '身分證字號檢核',
    category: 'life',
    description: '用內政部檢查碼規則驗算身分證字號是否格式正確,抓出打錯一碼或亂編的假號碼,並顯示初領縣市。全程本機計算、不上傳、不儲存。',
    keywords: ['身分證', '字號', '檢核', '驗證', '檢查碼', '格式', '真假', '假號碼', '初領', '縣市', 'id', '身份證', '檢查'],
    icon: '🪪',
    loader: () => import('@/tools/tw-id-check/Index.vue'),
  },
  {
    id: 'tw-vat-check',
    name: '統一編號檢核',
    category: 'life',
    description: '依財政部檢查碼規則,驗算公司統一編號(8 碼)是否正確 —— 抓出打錯一碼或亂編的假統編(假發票、人頭公司常見),可批次整理名單。全程本機計算、不上傳,並附財政部官方查詢連結。',
    keywords: ['統一編號', '統編', '營業稅籍', '公司', '行號', '檢核', '驗證', '檢查碼', '發票', '假發票', '人頭公司', '對帳', '廠商', 'vat', '8碼', '營利事業', '稅籍'],
    icon: '🏢',
    loader: () => import('@/tools/tw-vat-check/Index.vue'),
  },
  {
    id: 'password-gen',
    name: '本機密碼產生器',
    category: 'life',
    description: '用瀏覽器密碼學亂數產生高強度密碼,全程在你電腦、不連網、不記錄 —— 線上產生器可能偷偷記下你的密碼,這種工具就該在本機跑。',
    keywords: ['密碼', '產生', '產生器', '亂數', '隨機', 'password', '強密碼', '安全', '帳號', '兩步驟', '隨機密碼', '長密碼'],
    icon: '🔑',
    loader: () => import('@/tools/password-gen/Index.vue'),
  },
  {
    id: 'bmi',
    name: 'BMI 計算',
    category: 'life',
    description: '輸入身高體重,算出 BMI 與國健署體位分級,並給理想體重範圍。',
    keywords: ['bmi', '身體質量指數', '體重', '身高', '肥胖', '過重', '理想體重', '健康'],
    icon: '⚖️',
    loader: () => import('@/tools/bmi/Index.vue'),
  },
  {
    id: 'tdee',
    name: '每日熱量需求(TDEE)',
    category: 'life',
    description: '依身高體重年齡活動量,用 Mifflin-St Jeor 公式算出基礎代謝與每日該吃多少熱量。',
    keywords: ['熱量', 'tdee', 'bmr', '基礎代謝', '減重', '減肥', '卡路里', '大卡', '增肌', '飲食', '代謝率'],
    icon: '🔥',
    loader: () => import('@/tools/tdee/Index.vue'),
  },
  {
    id: 'unit-convert',
    name: '單位換算',
    category: 'life',
    description: '長度、重量、面積、溫度換算,含台灣常用的坪、台斤、台尺。',
    keywords: ['單位', '換算', '坪', '平方公尺', '台斤', '台尺', '公斤', '公里', '溫度', '攝氏', '華氏'],
    icon: '📐',
    loader: () => import('@/tools/unit-convert/Index.vue'),
  },
  {
    id: 'due-date',
    name: '預產期計算',
    category: 'life',
    description: '輸入最後一次月經第一天(LMP),推算預產期與目前懷孕週數。',
    keywords: ['預產期', '懷孕', '週數', '生產', 'LMP', '末次月經', '孕期'],
    icon: '🤰',
    loader: () => import('@/tools/due-date/Index.vue'),
  },
  {
    id: 'fuel-cost',
    name: '油錢試算',
    category: 'life',
    description: '輸入距離、油耗、油價,算出整趟油錢,還能直接除以人數算每人分攤。',
    keywords: ['油錢', '油費', '汽油', '加油', '里程', '油耗', '旅程', '開車', '分攤', '高速公路', '電車', '電費'],
    icon: '⛽',
    loader: () => import('@/tools/fuel-cost/Index.vue'),
  },
  {
    id: 'split-bill',
    name: '旅費分帳',
    category: 'life',
    description: '聚餐、旅遊一筆錢幾個人均分,可加服務費,馬上算出每人該付多少。',
    keywords: ['分帳', '均分', '平分', 'AA', '聚餐', '旅遊', '服務費', '每人', '攤錢'],
    icon: '🧮',
    loader: () => import('@/tools/split-bill/Index.vue'),
  },
  {
    id: 'invoice-lottery',
    name: '發票對獎',
    category: 'life',
    description: '輸入發票號碼,比對統一發票中獎號碼,自動算出中獎金額。',
    keywords: ['發票', '對獎', '中獎', '統一發票', '雲端發票', '對發票', '幾獎'],
    icon: '🧾',
    loader: () => import('@/tools/invoice-lottery/Index.vue'),
  },
  {
    id: 'num-to-chinese',
    name: '金額大寫互轉',
    category: 'life',
    description: '阿拉伯數字 ↔ 中文大寫雙向轉換:數字轉壹貳參…元角分整(支票/合約防竄改),也能把中文大寫金額反查回阿拉伯數字核對。全程在你瀏覽器換算,不上傳。',
    keywords: ['大寫', '國字', '金額', '數字轉中文', '中文數字', '中文轉數字', '大寫轉數字', '支票', '本票', '合約', '收據', '壹貳參', '元角分', '整', '銀行', '票據', '萬', '億', '阿拉伯數字', '核對', 'capital'],
    icon: '💴',
    loader: () => import('@/tools/num-to-chinese/Index.vue'),
  },
  {
    id: 'amount-english',
    name: '英文金額大寫',
    category: 'life',
    description: '把金額轉成英文文字寫法(例:USD ONE THOUSAND TWO HUNDRED THIRTY-FOUR AND 56/100 ONLY),供外銷發票、外幣支票、信用狀、英文合約使用 —— 與中文金額大寫互補。全程在你瀏覽器換算,不上傳。',
    keywords: ['英文金額', '金額英文', '大寫', '支票', 'cheque', 'check', '發票', 'invoice', '外銷', '出口', '信用狀', 'lc', '英文合約', 'dollars', 'cents', 'usd', '美金', '數字轉英文', 'amount in words', 'say', 'only'],
    icon: '💵',
    loader: () => import('@/tools/amount-english/Index.vue'),
  },
  {
    id: 'event-ics',
    name: '行事曆事件產生',
    category: 'life',
    description: '填好活動時間地點,下載 .ics 檔直接匯入 Google / Apple / Outlook 行事曆 —— 不必授權任何 App 存取你的行事曆。全程在你瀏覽器產生,不上傳。',
    keywords: ['行事曆', '日曆', '活動', '事件', 'ics', 'icalendar', '提醒', '邀請', 'google calendar', 'outlook', '匯入', '加到行事曆', '約會', '會議', '生日', '備忘', 'event', 'calendar'],
    icon: '📅',
    loader: () => import('@/tools/event-ics/Index.vue'),
  },
  {
    id: 'age-calc',
    name: '年齡計算',
    category: 'datetime',
    description: '輸入出生日期,算出實歲、虛歲、人壽保險年齡,還有已活天數與生日倒數。',
    keywords: ['年齡', '幾歲', '實歲', '足歲', '虛歲', '保險年齡', '生日', '倒數', '出生', '活了幾天', '歲數'],
    icon: '🎂',
    loader: () => import('@/tools/age-calc/Index.vue'),
  },
  {
    id: 'roc-year',
    name: '民國年換算',
    category: 'datetime',
    description: '民國年、西元年、日本年號(令和/平成/昭和)即時互換。',
    keywords: ['民國', '西元', '年份', '換算', '日本年號', '令和', '平成', '昭和', '幾年'],
    icon: '📆',
    loader: () => import('@/tools/roc-year/Index.vue'),
  },
  {
    id: 'date-calc',
    name: '日期計算機',
    category: 'datetime',
    description: '算兩個日期相差幾天、從某天加減 N 天是哪天(可只算工作日)、兩日期間有幾個上班日 —— 契約、退貨鑑賞期、繳費、交期、請款到期日推算。工作日可自填國定假日/公司休假與補班日,把工作天算準。全程在你瀏覽器計算,不上傳。',
    keywords: ['日期', '天數', '相差', '幾天', '倒數', '到期日', '加天數', '減天數', '工作日', '工作天', '營業日', '上班日', '週末', '國定假日', '假日', '補班', '交期', '請款', '契約', '退貨', '鑑賞期', '繳費期限', '幾天後', '幾天前', 'date', '日數', '推算'],
    icon: '🗓️',
    loader: () => import('@/tools/date-calc/Index.vue'),
  },
]

export const toolMap: Record<string, ToolDef> = Object.fromEntries(
  tools.map((t) => [t.id, t]),
)

export function toolsByCategory(categoryId: string): ToolDef[] {
  return tools.filter((t) => t.category === categoryId)
}
