import type { Component } from 'vue'

/*
  ★ 單一事實來源 ★
  所有工具的 metadata 都註冊在這裡。
  導覽、搜尋、關鍵字導引(chatbot)、分類頁、路由,全部讀這一份。
  新增工具 = 在 src/tools/<id>/Index.vue 寫元件 + 在這裡加一筆。不改主程式。
*/
export interface ToolDef {
  id: string // kebab-case,= 路由 slug,= 資料夾名
  name: string
  category: string // 對應 categories.ts 的 id
  description: string
  keywords: string[] // 關鍵字導引比對用,含同義詞、口語說法
  icon: string
  loader: () => Promise<{ default: Component }>
}

export const tools: ToolDef[] = [
  {
    id: 'image-studio',
    name: '圖片工坊',
    category: 'workshop',
    description: '批次轉檔(JPG/PNG/WebP)、壓縮、縮放 —— 全程在你瀏覽器處理,不上傳、無廣告、自動清掉相片定位等中繼資料。',
    keywords: ['圖片', '照片', '轉檔', '格式', '壓縮', '縮小', '縮放', 'webp', 'jpg', 'png', '批次', '改大小', '去exif'],
    icon: '🖼️',
    loader: () => import('@/tools/image-studio/Index.vue'),
  },
  {
    id: 'text-card',
    name: '社群文字卡 / 語錄圖',
    category: 'workshop',
    description: '把一段文字做成漂亮的圖片卡片(IG 貼文/限動、Threads、FB、公告、金句)—— 字級自動填滿版面、中英自動斷行,選好尺寸即套各社群版位。全程在你瀏覽器繪製,文字不上傳、無廣告、無浮水印、免開 Canva。',
    keywords: ['文字卡', '語錄', '語錄圖', '金句', '金句圖', '文字圖', '文字轉圖片', '文字卡片', '圖卡', '貼文圖', '公告圖', '海報', 'ig', 'instagram', '限動', 'threads', 'facebook', '社群', '引言', 'quote', 'text image', '做圖', '排版', '標語'],
    icon: '🗯️',
    loader: () => import('@/tools/text-card/Index.vue'),
  },
  {
    id: 'signature-maker',
    name: '手寫簽名製作',
    category: 'workshop',
    description: '在螢幕上簽名,匯出透明背景 PNG,直接貼進 PDF/Word/簡報電子簽名,免印出再掃 —— 全程在你瀏覽器,簽名不上傳。',
    keywords: ['簽名', '手寫', '電子簽名', '簽章', '簽名檔', '透明背景', 'png', '簽文件', '簽合約', 'signature', '簽名製作'],
    icon: '✍️',
    loader: () => import('@/tools/signature-maker/Index.vue'),
  },
  {
    id: 'color-tools',
    name: '色彩工坊',
    category: 'workshop',
    description: 'HEX/RGB/HSL 色碼互轉,還能從上傳的照片或 logo 抽出主色調色盤 —— 全程在你瀏覽器,圖片不上傳。',
    keywords: ['顏色', '色碼', '色彩', 'hex', 'rgb', 'hsl', '調色盤', '配色', '取色', '吸管', '主色', 'logo', '色票', 'color'],
    icon: '🎨',
    loader: () => import('@/tools/color-tools/Index.vue'),
  },
  {
    id: 'gradient-maker',
    name: 'CSS 漸層產生器',
    category: 'workshop',
    description: '視覺化調出線性 / 放射 / 圓錐漸層,多色標、角度、圓心位置即時預覽,一鍵複製可直接用的 CSS —— 全程在你瀏覽器計算,不連網、不上傳。與色彩工坊、色階產生器互補。',
    keywords: ['漸層', '漸變', 'gradient', 'css漸層', 'linear-gradient', 'radial-gradient', 'conic-gradient', '線性漸層', '放射漸層', '圓錐漸層', '背景', 'background', '配色', '色標', '色彩', 'css', '網頁', '按鈕', '漸層背景', '產生器'],
    icon: '🌈',
    loader: () => import('@/tools/gradient-maker/Index.vue'),
  },
  {
    id: 'contrast-check',
    name: '顏色可讀性檢測',
    category: 'workshop',
    description: '輸入文字色與背景色,依國際無障礙標準(WCAG)算出對比比值,判斷在一般字/大字下清不清楚、達不達 AA/AAA —— 做簡報、海報、網頁、長輩友善文件選色用。全程在你瀏覽器計算,不上傳。',
    keywords: ['對比', '對比度', '色彩對比', '顏色對比', '可讀性', '看不清楚', 'wcag', 'aa', 'aaa', '無障礙', '配色', '文字顏色', '背景色', '對比比值', 'contrast', 'a11y', '長輩', '弱視', '簡報配色'],
    icon: '🌗',
    loader: () => import('@/tools/contrast-check/Index.vue'),
  },
  {
    id: 'color-blind',
    name: '色盲友善檢測',
    category: 'workshop',
    description: '上傳圖表、簡報、網頁截圖,模擬色盲/色弱使用者看到的樣子,檢查紅綠配色是否還分得出來 —— 全程在你瀏覽器處理,圖片不上傳。',
    keywords: ['色盲', '色弱', '色覺', '紅綠色盲', '色覺障礙', '色盲模擬', '色盲友善', '無障礙', 'a11y', '配色', '圖表配色', '簡報配色', '色彩', 'deuteranopia', 'protanopia', 'tritanopia', '色盲檢測', '色盲測試', 'colorblind', '色弱模擬'],
    icon: '👁️',
    loader: () => import('@/tools/color-blind/Index.vue'),
  },
  {
    id: 'gif-studio',
    name: '動圖工坊',
    category: 'workshop',
    description: '把多張圖片做成會動的 GIF,可調速度、尺寸、循環 —— 全程在你瀏覽器編碼,不上傳、無廣告、無浮水印(線上 GIF 站多半要上傳照片又加浮水印)。',
    keywords: ['gif', '動圖', '動畫', '會動的圖', '動態圖', '圖片變動畫', '製作gif', '做gif', '連續圖', '逐格', '動態貼圖', 'animated', '影格', '動圖製作'],
    icon: '🎞️',
    loader: () => import('@/tools/gif-studio/Index.vue'),
  },
  {
    id: 'video-gif',
    name: '影片轉 GIF',
    category: 'workshop',
    description: '把一小段影片(MP4/WebM/MOV)轉成會動的 GIF,可裁時間區間、調速度尺寸 —— 全程在你瀏覽器解碼編碼,影片不上傳、無廣告、無浮水印、不限時長(線上轉 GIF 站要上傳又加浮水印)。',
    keywords: ['影片轉gif', '影片轉動圖', 'video to gif', 'gif', '動圖', '動畫', 'mp4轉gif', '影片', '截短片', '片段', '做gif', '貼圖', '動態圖', 'webm', 'mov', '轉檔', '影片轉檔'],
    icon: '🎥',
    loader: () => import('@/tools/video-gif/Index.vue'),
  },
  {
    id: 'image-ocr',
    name: '圖片文字辨識(OCR)',
    category: 'workshop',
    description: '把截圖、照片、掃描檔裡的文字抓成可編輯文字,支援繁中+英 —— 全程在你瀏覽器辨識,圖片不上傳(一般 OCR 網站都要你上傳)。',
    keywords: ['ocr', '文字辨識', '圖片轉文字', '截圖轉文字', '照片轉文字', '掃描', '辨識', '抓文字', '擷取文字', '圖轉文字', '繁體', '辨識文字', 'image to text'],
    icon: '🔠',
    loader: () => import('@/tools/image-ocr/Index.vue'),
  },
  {
    id: 'random-picker',
    name: '抽籤 / 分組',
    category: 'life',
    description: '貼上名單,隨機抽出、隨機分組或隨機排序 —— 用加密級亂數,比一般網頁公平。聚餐誰請客、分組、抽獎都好用,名單不上傳。',
    keywords: ['抽籤', '抽獎', '尾牙', '中獎', '分組', '隨機', '洗牌', '排序', '誰請客', '決定', '做決定', '隨機選', '分隊', '抽人', '點名', '亂數', '公平', 'random', 'draw', '抽號碼', '轉盤'],
    icon: '🎲',
    loader: () => import('@/tools/random-picker/Index.vue'),
  },
  {
    id: 'image-annotate',
    name: '圖片標註編輯器',
    category: 'workshop',
    description: '在截圖/照片上畫箭頭、框重點、畫筆、打字,做教學步驟、回報問題、圈重點 —— 全程在你瀏覽器,圖片不上傳。',
    keywords: ['標註', '截圖', '畫箭頭', '框起來', '圈重點', '畫重點', '註記', '打字', '畫筆', '編輯圖片', '線上編圖', '修圖', '教學', '說明圖', 'annotate', 'markup', '圖片編輯'],
    icon: '🖍️',
    loader: () => import('@/tools/image-annotate/Index.vue'),
  },
  {
    id: 'timezone',
    name: '時區換算 / 世界時鐘',
    category: 'life',
    description: '看現在各地幾點,或把某地某時間換算到全球各時區 —— 自動處理日光節約,跟國外家人朋友、客戶約時間不算錯。純前端。',
    keywords: ['時區', '時差', '世界時鐘', '換算', '幾點', '國外時間', '日光節約', '約時間', '會議', 'utc', 'gmt', '紐約', '東京', '倫敦', '美國時間', 'timezone'],
    icon: '🌏',
    loader: () => import('@/tools/timezone/Index.vue'),
  },
  {
    id: 'find-replace',
    name: '尋找取代工坊',
    category: 'workshop',
    description: '批次尋找/取代文字,支援正規表達式與忽略大小寫,可用 $1 引用群組 —— 整理名單、批次改格式很快,全程在你瀏覽器,文字不上傳。',
    keywords: ['尋找', '取代', '替換', '搜尋取代', 'find', 'replace', '批次', '正則', '正規表達式', 'regex', '文字處理', '整理', '取代字串', '換字'],
    icon: '🔁',
    loader: () => import('@/tools/find-replace/Index.vue'),
  },
  {
    id: 'screen-record',
    name: '螢幕錄影',
    category: 'workshop',
    description: '錄製整個螢幕、視窗或分頁成影片(可含聲音),做操作教學、把畫面問題錄給人看 —— 全程在你電腦錄製,影片不上傳、無浮水印、不限時長。',
    keywords: ['螢幕錄影', '錄影', '錄製', '錄螢幕', '畫面錄製', '教學錄影', '錄畫面', 'screen record', 'recorder', '錄製教學', '操作錄影', '螢幕錄製'],
    icon: '⏺️',
    loader: () => import('@/tools/screen-record/Index.vue'),
  },
  {
    id: 'voice-recorder',
    name: '錄音機',
    category: 'workshop',
    description: '用麥克風錄語音備忘、訪談、會議、長輩口述,可暫停/繼續、試聽後下載音檔 —— 全程在你的裝置錄製,聲音不上傳、無廣告、不限時長、免註冊。與螢幕錄影互補(這支只錄聲音)。',
    keywords: ['錄音', '錄音機', '語音', '麥克風', '收音', '語音備忘', '訪談', '會議', '口述', '錄聲音', '配音', 'voice', 'recorder', 'audio', '音檔', '錄製聲音', '線上錄音'],
    icon: '🎙️',
    loader: () => import('@/tools/voice-recorder/Index.vue'),
  },
  {
    id: 'bg-remove',
    name: '圖片去背',
    category: 'workshop',
    description: '自動去掉照片背景、輸出透明 PNG,做商品圖、大頭貼最方便 —— 全程在你瀏覽器用 AI 處理,照片不上傳;remove.bg 等服務要付費又要上傳。',
    keywords: ['去背', '去背景', '退底', '透明背景', '摳圖', '商品圖', '大頭貼', 'removebg', 'remove bg', '背景移除', '人像去背', 'png', '退地'],
    icon: '🪄',
    loader: () => import('@/tools/bg-remove/Index.vue'),
  },
  {
    id: 'pdf-studio',
    name: 'PDF 工坊',
    category: 'workshop',
    description: '合併、刪頁/重排、圖片↔PDF、取出文字、簽名/蓋章、加浮水印、加頁碼、併頁省紙、壓縮 —— 全程在你瀏覽器處理,不上傳機密文件、無廣告、不限檔數。',
    keywords: ['pdf', '合併', '分割', '刪頁', '重排', '旋轉', '轉正', '轉向', '歪斜', '頁面', '圖片轉pdf', 'pdf轉圖片', 'pdf轉jpg', '掃描', '轉檔', '擷取', '抽頁', '組合', '簽名', '簽署', '簽章', '蓋章', '用印', '印章', '簽合約', '在pdf上簽名', 'sign', '浮水印', '加註', '證件', '防盜用', 'watermark', '取出文字', '抽文字', '複製文字', '純文字', 'pdf轉文字', 'pdf轉文字檔', '文字層', '頁碼', '加頁碼', '編號', '頁數', '第幾頁', 'page number', '併頁', '省紙', '一頁多頁', '2合1', '4合1', '多合一', '講義', '印講義', 'n-up', 'nup', '節省紙張', '壓縮', '縮小', '減肥', '檔案太大', '太大', '寄不出去', 'compress', '變小'],
    icon: '📄',
    loader: () => import('@/tools/pdf-studio/Index.vue'),
  },
  {
    id: 'doc-scan',
    name: '文件掃描美化',
    category: 'workshop',
    description: '把手機拍的文件照片變成像掃描機掃出來的乾淨檔 —— 自動拉對比、提亮背景,可轉黑白/灰階,合併成 PDF —— 全程在你瀏覽器處理,合約單據不上傳、無廣告、無浮水印(CamScanner 等要付費又加浮水印)。',
    keywords: ['掃描', '文件掃描', '掃描器', '拍文件', '文件變掃描', 'camscanner', '掃描app', '合約', '單據', '收據', '筆記', '白板', '黑白', '自適應', '二值化', '提亮', '對比', '拍照轉pdf', '照片轉pdf', '文件轉pdf', 'scan', 'scanner', '去背景', '紙變白'],
    icon: '🖨️',
    loader: () => import('@/tools/doc-scan/Index.vue'),
  },
  {
    id: 'secure-box',
    name: '本機加密保險箱',
    category: 'workshop',
    description: '替文字或檔案上密碼(AES-GCM 256),把加密結果寄出、另以電話告知密碼,對方才解得開 —— 加密、解密、密碼全程在你瀏覽器,不上傳;線上加密網站可能偷記你的內容與密碼。',
    keywords: ['加密', '解密', '密碼', '保護', '機密', '檔案加密', '文字加密', 'aes', '加密檔案', '上密碼', 'encrypt', 'decrypt', '保險箱', '隱私', '安全傳檔'],
    icon: '🔐',
    loader: () => import('@/tools/secure-box/Index.vue'),
  },
  {
    id: 'image-fit-size',
    name: '照片壓到指定大小(KB)',
    category: 'workshop',
    description: '報名/考試/上傳系統限制「照片不得超過 ○○ KB」?自動壓到上限內、畫質最高,可一併限制最長邊 —— 全程在你瀏覽器處理,照片不上傳、無廣告、可批次。',
    keywords: ['壓縮', '縮小', '照片', '大頭照', '證件照', 'kb', '大小限制', '檔案太大', '上傳', '報名', '考試', '國考', '學測', '限制大小', '不超過', '壓到', '指定大小', '2mb', '100kb', '500kb', '減肥', '縮檔', 'compress', '上傳照片'],
    icon: '🗜️',
    loader: () => import('@/tools/image-fit-size/Index.vue'),
  },
  {
    id: 'data-size',
    name: '資料大小與下載時間換算',
    category: 'workshop',
    description: 'KB/MB/GB(1000)對照系統實際顯示的 KiB/MiB/GiB(1024)—— 搞懂「1TB 硬碟為何只剩 931GB」;bit/byte 換算、輸入頻寬估下載/上傳要多久。純數學計算、不上傳。',
    keywords: ['資料大小', '檔案大小', 'kb', 'mb', 'gb', 'tb', 'kib', 'mib', 'gib', '位元組', 'byte', 'bit', '位元', '1024', '1000', '硬碟容量', '931gb', '頻寬', '下載時間', '傳輸時間', 'mbps', '網速', 'bytes', 'megabyte', 'gigabyte'],
    icon: '💾',
    loader: () => import('@/tools/data-size/Index.vue'),
  },
  {
    id: 'css-units',
    name: 'CSS 單位換算',
    category: 'workshop',
    description: 'px / rem / em / pt / pc / in / cm / mm / % 一次互轉,可自訂根字級(rem)與脈絡字級(em、%)—— 網頁與印刷排版常用,96dpi 的 px↔pt↔mm 換算不再記錯。純數學計算、不上傳。',
    keywords: ['css', '單位', 'px', 'rem', 'em', 'pt', 'pc', 'cm', 'mm', 'inch', '英吋', '點數', '字級', '根字級', 'root font-size', '排版', '網頁', '前端', 'pixel', 'point', '換算', 'px轉rem', 'rem轉px'],
    icon: '🔡',
    loader: () => import('@/tools/css-units/Index.vue'),
  },
  {
    id: 'aspect-ratio',
    name: '長寬比與尺寸計算',
    category: 'workshop',
    description: '算出寬高是幾比幾(16:9、4:3…)、維持比例放大縮小求另一邊、把圖塞進外框(contain/cover)會縮成多大 —— 做設計/剪片/印刷/響應式圖片必備,純數學計算、不上傳。',
    keywords: ['長寬比', '比例', '寬高比', '16:9', '4:3', '21:9', '尺寸', '解析度', '縮放', '等比例', '放大', '縮小', '百萬像素', 'megapixel', 'aspect ratio', 'resize', 'contain', 'cover', '影片尺寸', '螢幕比例', '相片比例'],
    icon: '📏',
    loader: () => import('@/tools/aspect-ratio/Index.vue'),
  },
  {
    id: 'ppi-calc',
    name: '螢幕像素密度(PPI)計算',
    category: 'workshop',
    description: '輸入解析度與螢幕對角線英吋,算出每英吋像素(PPI)、點距、實體尺寸,並依觀看距離判定是否達「視網膜」清晰度 —— 買螢幕/手機、決定列印解析度時好用。純數學計算、不上傳。',
    keywords: ['ppi', 'dpi', '像素密度', '解析度', '螢幕', '對角線', '英吋', '點距', 'dot pitch', '視網膜', 'retina', '清晰度', '買螢幕', '手機螢幕', '列印解析度', 'pixel density', '畫質', 'ppcm'],
    icon: '🖥️',
    loader: () => import('@/tools/ppi-calc/Index.vue'),
  },
  {
    id: 'paper-size',
    name: '紙張尺寸與列印像素',
    category: 'workshop',
    description: 'A4/A3/B5… 與美規紙張到底幾 mm?在 300 DPI 要做幾 × 幾像素?一次給 mm/cm/英吋與指定 DPI 的像素尺寸(A4@300dpi=2480×3508px),含直橫式 —— 做海報、印刷稿、報名表免再到處查。純查表計算、不上傳。',
    keywords: ['紙張', '尺寸', 'a4', 'a3', 'a5', 'b4', 'b5', 'letter', '海報', '印刷', '列印', 'dpi', '像素', 'px', 'mm', '公分', '英吋', 'iso 216', '出血', '解析度', '300dpi', 'a4幾px', 'a4像素', 'print size'],
    icon: '📄',
    loader: () => import('@/tools/paper-size/Index.vue'),
  },
  {
    id: 'image-diff',
    name: '圖片差異比對',
    category: 'workshop',
    description: '上傳兩張同尺寸的圖(例:改版前後的截圖),逐像素用 YIQ 感知色差標出哪裡變了、變化比例多少。做 UI 改版核對、找出兩張圖差異(大家來找碴)用,可調容忍度忽略壓縮雜訊、抗鋸齒。差異圖可下載 —— 全程在你瀏覽器以 canvas 運算,圖片不上傳、不連網。',
    keywords: ['圖片比對', '圖片差異', '比較圖片', 'image diff', 'diff', 'pixelmatch', '找不同', '大家來找碴', '截圖比對', 'ui 改版', '視覺回歸', 'visual diff', 'compare images', '差異', '像素比對', '兩張圖', '改版前後', '比對'],
    icon: '🔬',
    loader: () => import('@/tools/image-diff/Index.vue'),
  },
  {
    id: 'heic-convert',
    name: 'HEIC 轉 JPG / PNG',
    category: 'workshop',
    description: 'iPhone 拍的 .heic 照片在 Windows、舊手機、很多網站都打不開?一鍵轉成 JPG/PNG —— 全程在你瀏覽器解碼,不上傳私密照片、無廣告、無浮水印、可批次。',
    keywords: ['heic', 'heif', 'iphone', '蘋果', '照片', '打不開', '無法開啟', '轉檔', '轉jpg', '轉png', '格式', 'jpg', 'png', '批次', '蘋果照片', '相片'],
    icon: '📷',
    loader: () => import('@/tools/heic-convert/Index.vue'),
  },
  {
    id: 'data-convert',
    name: '資料轉換工坊',
    category: 'workshop',
    description: 'CSV / JSON / Excel 三者互轉,直接讀寫 .xlsx —— 全程在你瀏覽器,不上傳名單訂單、無廣告、不限筆數。',
    keywords: ['csv', 'json', '轉換', '互轉', 'tsv', 'excel', 'xlsx', 'xls', '試算表', '資料', '表格', '逗號', '匯出', '格式轉換', '名單', '訂單'],
    icon: '🔄',
    loader: () => import('@/tools/data-convert/Index.vue'),
  },
  {
    id: 'sql-insert',
    name: 'SQL 語法產生器',
    category: 'workshop',
    description: '把 Excel / CSV / 試算表資料一鍵轉成 INSERT(可一併 CREATE TABLE)—— 自動跳脫引號、空欄轉 NULL、前導 0 的電話統編保留為文字,支援 MySQL/PostgreSQL/SQLite。全程在你瀏覽器,資料不上傳。',
    keywords: ['sql', 'insert', 'create table', '資料庫', 'mysql', 'postgresql', 'postgres', 'sqlite', '匯入', 'csv轉sql', 'excel轉sql', '建表', '語法', '產生', '塞資料', 'seed', '匯入資料庫', 'db', 'tsv'],
    icon: '🗄️',
    loader: () => import('@/tools/sql-insert/Index.vue'),
  },
  {
    id: 'sql-format',
    name: 'SQL 格式化 / 美化',
    category: 'workshop',
    description:
      '把擠成一行或排版凌亂的 SQL 整理成可讀格式(主要子句換行、欄位與條件縮排),或反向壓成單行 —— 關鍵字大小寫可選,正確處理子查詢、JOIN、CREATE TABLE,字串與註解原樣保留。查詢常含資料表/欄位名與參數值,全程在你瀏覽器處理、不上傳。',
    keywords: [
      'sql',
      'sql格式化',
      'sql美化',
      '格式化',
      '美化',
      'format',
      'formatter',
      'beautify',
      'pretty',
      '排版',
      '對齊',
      '縮排',
      '壓縮',
      'minify',
      '單行',
      '查詢',
      'query',
      'select',
      '可讀',
      'mysql',
      'postgresql',
      'sqlite',
      '整理sql',
    ],
    icon: '✨',
    loader: () => import('@/tools/sql-format/Index.vue'),
  },
  {
    id: 'xml-format',
    name: 'XML 格式化 / 壓縮',
    category: 'workshop',
    description:
      '把擠成一行的 XML / SVG / RSS / pom.xml / 設定檔重新縮排成可讀格式,或反向壓成單行 —— 註解、CDATA、宣告與屬性值原樣保留,縮排 2/4 可選。XML 設定常含連線字串、密鑰,全程在你瀏覽器處理、不上傳。',
    keywords: [
      'xml',
      'xml格式化',
      'xml美化',
      'xml排版',
      '格式化',
      '美化',
      '排版',
      '縮排',
      'format',
      'formatter',
      'beautify',
      'pretty',
      '壓縮',
      'minify',
      '單行',
      'svg',
      'rss',
      'atom',
      'pom.xml',
      'maven',
      'soap',
      'sitemap',
      '設定檔',
      'config',
      '整理xml',
    ],
    icon: '📰',
    loader: () => import('@/tools/xml-format/Index.vue'),
  },
  {
    id: 'css-format',
    name: 'CSS 格式化 / 壓縮',
    category: 'workshop',
    description:
      '把擠成一行或排版凌亂的 CSS 整理成可讀格式(每條宣告獨立一行、選擇器逗號各自成行、巢狀 @media 縮排),或反向壓成單行 —— 字串、註解與 url() 內的 data URI 都正確保留,a:hover 偽類冒號不會被誤判。全程在你瀏覽器處理、不上傳。',
    keywords: [
      'css',
      'css格式化',
      'css美化',
      'css壓縮',
      '格式化',
      '美化',
      '排版',
      '縮排',
      'format',
      'formatter',
      'beautify',
      'pretty',
      '壓縮',
      'minify',
      'minify css',
      '單行',
      '樣式',
      'stylesheet',
      'scss',
      'less',
      '整理css',
      '前端',
    ],
    icon: '🎨',
    loader: () => import('@/tools/css-format/Index.vue'),
  },
  {
    id: 'cron-explain',
    name: 'Cron 表達式解讀',
    category: 'workshop',
    description: '排程那串「30 9 * * 1-5」到底多久跑一次?用白話中文說明,還直接算出接下來 5 次執行時間 —— 設 crontab/GitHub Actions/排程不再猜。全程在你瀏覽器計算,不上傳。',
    keywords: ['cron', 'crontab', '排程', '定時', '定時任務', 'schedule', '表達式', '解讀', '翻譯', '下次執行', 'github actions', 'cronjob', '每天', '每小時', '每分鐘', '週期', '定期'],
    icon: '⏰',
    loader: () => import('@/tools/cron-explain/Index.vue'),
  },
  {
    id: 'rrule-explain',
    name: 'RRULE 行事曆重複規則解讀',
    category: 'workshop',
    description:
      '貼上行事曆 .ics 檔裡那串看不懂的 RRULE(例 FREQ=MONTHLY;BYDAY=-1FR),用白話中文說明「多久發生一次」,並依開始時間直接算出接下來幾次的實際日期 —— 設定每月最後一個週五、每隔一週開會、每年第 4 個週四等規則時不再猜。支援 FREQ/INTERVAL/COUNT/UNTIL/BYMONTH/BYMONTHDAY/BYDAY/BYSETPOS/WKST。與 cron 解讀、.ics 事件產生器互補;全程在你瀏覽器計算,不連網、不上傳。',
    keywords: [
      'rrule',
      'recurrence',
      '重複規則',
      '重複事件',
      'ical',
      'ics',
      'icalendar',
      'rfc 5545',
      'rfc5545',
      '行事曆',
      '日曆',
      '週期',
      '定期',
      '重複',
      'freq',
      'byday',
      'bymonthday',
      'bysetpos',
      'wkst',
      '每月最後一個',
      '每隔一週',
      'google 日曆',
      'outlook',
      '重複行程',
      '解讀',
    ],
    icon: '🔁',
    loader: () => import('@/tools/rrule-explain/Index.vue'),
  },
  {
    id: 'ics-viewer',
    name: '.ics 行事曆檢視器',
    category: 'workshop',
    description:
      '貼上或開啟收到的 .ics 會議邀請 / 訂閱行事曆檔,直接列出每筆事件 —— 摘要、起訖時間、地點、主辦人、說明,重複事件還會把 RRULE 翻成白話並列出接下來幾次發生。別人寄來的 .ics 用記事本開全是亂碼般的欄位,線上檢視器又要你上傳含行程隱私的檔案;這支全程在你瀏覽器解析,不連網、不上傳。與 .ics 事件產生器、RRULE 解讀互補。',
    keywords: [
      'ics',
      'ical',
      'icalendar',
      '行事曆',
      '日曆',
      '行事曆檔',
      '會議邀請',
      '邀請檔',
      'invite',
      'vevent',
      'rfc 5545',
      '開啟 ics',
      '檢視 ics',
      '看 ics',
      'ics 內容',
      '行程',
      '訂閱行事曆',
      'google 日曆',
      'outlook',
      'apple 行事曆',
      '解析',
    ],
    icon: '📅',
    loader: () => import('@/tools/ics-viewer/Index.vue'),
  },
  {
    id: 'geo-coord',
    name: 'GPS 座標轉換 / 距離',
    category: 'workshop',
    description:
      '十進位度(Google 地圖那種 25.0337, 121.5645)與度分秒(DMS,25°02\'01"N)、度分(DM)之間互轉,並算兩個座標間的直線(大圓)距離 —— 導航機、登山地圖、相片 GPS、地政常用,半球字母與負號都能解析。全程在你瀏覽器計算,不連網、不上傳;只有你主動點才會把座標帶到 Google 地圖。',
    keywords: [
      'gps',
      '座標',
      '坐標',
      '經緯度',
      '緯度',
      '經度',
      '十進位度',
      '度分秒',
      'dms',
      'dd',
      'decimal degrees',
      '座標轉換',
      'coordinate',
      'lat',
      'lon',
      'latitude',
      'longitude',
      '距離',
      '兩點距離',
      'haversine',
      '大圓距離',
      'google 地圖',
      '地圖座標',
      '登山',
      '定位',
    ],
    icon: '🧭',
    loader: () => import('@/tools/geo-coord/Index.vue'),
  },
  {
    id: 'text-similarity',
    name: '文字相似度比對',
    category: 'workshop',
    description:
      '算兩段文字有多像 —— Levenshtein 編輯距離(要改幾步)、字元級相似度百分比,以及以「詞」為單位的 Jaccard / Dice 係數與共同詞、各自獨有的詞。判斷兩筆地址/姓名是否同一個(台 vs 臺、半形空白)、找近似重複的標題、看文章改寫幅度、清名單時設相似度門檻都好用。全程在你瀏覽器計算,不連網、不上傳。',
    keywords: [
      '相似度',
      '文字相似',
      '相似',
      '比對',
      '比較',
      '編輯距離',
      'levenshtein',
      '萊文斯坦',
      'jaccard',
      'dice',
      '相似度百分比',
      '近似',
      '重複',
      '去重',
      '抄襲',
      '改寫',
      '比對文字',
      'similarity',
      'fuzzy',
      '模糊比對',
      '字串相似',
      '名稱比對',
      '地址比對',
    ],
    icon: '📊',
    loader: () => import('@/tools/text-similarity/Index.vue'),
  },
  {
    id: 'json-diff',
    name: 'JSON 結構比對',
    category: 'workshop',
    description: '貼上兩份 JSON,列出新增/刪除/變更的欄位與路徑 —— 物件鍵不分順序、排版差異自動忽略,比逐行 diff 更準。比對兩次 API 回應或兩版設定檔超實用。全程在你瀏覽器,含密鑰資料不上傳。',
    keywords: ['json', '比對', '比較', 'diff', '差異', '差別', '結構', 'compare', 'api', '回應', '設定檔', '版本', '變更', '哪裡不一樣', '物件', '欄位差異'],
    icon: '🔬',
    loader: () => import('@/tools/json-diff/Index.vue'),
  },
  {
    id: 'json-patch',
    name: 'JSON Patch(RFC 6902)',
    category: 'workshop',
    description:
      '兩種模式:① 套用——把一份 JSON Patch(add/remove/replace/move/copy/test)套用到 JSON 文件看結果;② 比較——丟兩份 JSON 自動產生轉換用的 patch。路徑採 JSON Pointer(/foo/0/bar)。做 API 局部更新(HTTP PATCH)、設定版控必備。與 json-diff(視覺對照)互補,這支產出可機器套用的標準 patch。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'json patch',
      'rfc 6902',
      'json pointer',
      'rfc 6901',
      'patch',
      'json',
      'http patch',
      '局部更新',
      'add',
      'remove',
      'replace',
      'move',
      'copy',
      'test',
      'diff',
      '差異',
      'api',
      '開發',
    ],
    icon: '🩹',
    loader: () => import('@/tools/json-patch/Index.vue'),
  },
  {
    id: 'json-to-ts',
    name: 'JSON 轉 TypeScript 型別',
    category: 'workshop',
    description: '貼上 API 回應或任何 JSON,自動推斷出對應的 TypeScript interface —— 巢狀物件具名、陣列合併欄位、缺漏鍵標可選。寫前端/Node 免手刻型別。全程在你瀏覽器,含密鑰回應不上傳。',
    keywords: ['json', 'typescript', 'ts', '型別', 'interface', 'type', '轉型別', 'json轉ts', '產生型別', 'api', '回應', '定義', 'd.ts', '前端', 'node', '型別定義'],
    icon: '🧬',
    loader: () => import('@/tools/json-to-ts/Index.vue'),
  },
  {
    id: 'json-to-go',
    name: 'JSON 轉 Go struct',
    category: 'workshop',
    description:
      '貼上 API 回應或任何 JSON,自動推斷出對應的 Go struct(含 json tag)—— 巢狀物件用內嵌匿名 struct、陣列合併欄位取聯集、欄位名轉 PascalCase 且常見縮寫(ID/URL/API)大寫。寫 Go 後端免手刻型別。與 JSON 轉 TypeScript 互補。全程在你瀏覽器,含密鑰回應不上傳。',
    keywords: [
      'json',
      'go',
      'golang',
      'struct',
      '型別',
      'json轉go',
      'json to go',
      '產生型別',
      'json tag',
      'api',
      '回應',
      '後端',
      'marshal',
      'unmarshal',
      'pascalcase',
      '結構',
    ],
    icon: '🐹',
    loader: () => import('@/tools/json-to-go/Index.vue'),
  },
  {
    id: 'json-to-python',
    name: 'JSON 轉 Python',
    category: 'workshop',
    description: '貼上 API 回應或任何 JSON,自動推斷出 Python 類別 —— 可選 dataclass / TypedDict / Pydantic 三種樣式,巢狀物件各自成類別、陣列合併欄位、缺鍵或 null 自動 Optional。寫 Python 後端免手刻型別。與 JSON 轉 TypeScript / Go 互補;全程在你瀏覽器,含密鑰回應不上傳。',
    keywords: ['json', 'python', 'dataclass', 'typeddict', 'pydantic', 'basemodel', '型別', 'type', 'json轉python', 'json to python', '產生類別', 'class', 'api', '回應', '後端', 'annotation', 'typing', 'optional', '資料類別'],
    icon: '🐍',
    loader: () => import('@/tools/json-to-python/Index.vue'),
  },
  {
    id: 'big5-convert',
    name: 'Big5 ↔ UTF-8 文字檔轉換',
    category: 'workshop',
    description: '早年 Windows 記事本存的 Big5/ANSI .txt 在 Mac、手機、網頁變亂碼?一鍵轉成 UTF-8(或反向轉回 Big5)—— 自動判斷來源編碼,全程在你瀏覽器轉換,檔案不上傳。',
    keywords: ['big5', 'utf-8', 'utf8', 'ansi', '編碼', '亂碼', '轉碼', '文字檔', 'txt', '記事本', '繁體', '中文亂碼', '檔案亂碼', '轉換', '編碼轉換', 'big5轉utf8', 'utf8轉big5', '舊檔', 'mac', '打不開', 'csv亂碼', 'srt亂碼'],
    icon: '🈯',
    loader: () => import('@/tools/big5-convert/Index.vue'),
  },
  {
    id: 'mojibake-fix',
    name: '亂碼修復',
    category: 'workshop',
    description: '把「中文變成 ä¸­æ–‡、é 變 Ã©」這類 UTF-8 被誤當西歐編碼的亂碼還原成正常文字 —— 全程在你瀏覽器,文字不上傳。',
    keywords: ['亂碼', '亂碼修復', '解碼', '編碼', 'utf-8', 'utf8', 'big5', 'latin', 'ansi', '問號', '火星文', '錯字', 'æ', 'ä', 'Ã', 'mojibake', '中文亂碼', '匯出亂碼', 'csv 亂碼'],
    icon: '🔣',
    loader: () => import('@/tools/mojibake-fix/Index.vue'),
  },
  {
    id: 'encoded-word',
    name: 'Email 亂碼主旨還原',
    category: 'workshop',
    description:
      '把 email 主旨 / 寄件者 / 附件檔名裡 =?UTF-8?B?...?= 或 =?Big5?Q?...?= 這類 RFC 2047 編碼亂碼還原成可讀文字,逐段標出字元集與編碼方式。支援 UTF-8 / Big5 / ISO-8859-1 / Shift_JIS / GBK。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'email 亂碼',
      '主旨亂碼',
      '信件亂碼',
      '郵件亂碼',
      'encoded word',
      'encoded-word',
      'rfc 2047',
      'mime',
      'mime header',
      '=?utf-8?b?',
      '=?big5?',
      'base64 主旨',
      'quoted printable',
      '附件檔名亂碼',
      '寄件者亂碼',
      '解碼主旨',
      'subject decode',
    ],
    icon: '✉️',
    loader: () => import('@/tools/encoded-word/Index.vue'),
  },
  {
    id: 'markdown-table',
    name: 'CSV ↔ Markdown 表格',
    category: 'workshop',
    description: '把 CSV/Excel 表格轉成 GitHub/Notion 風格的 Markdown 表格(欄位自動對齊),或把 Markdown 表格轉回 CSV —— 全程在你瀏覽器,不上傳。',
    keywords: ['markdown', 'md', '表格', 'table', 'csv轉markdown', 'markdown表格', 'github', 'notion', 'hackmd', 'readme', '文件', '對齊', '管線', 'pipe', '轉表格'],
    icon: '📋',
    loader: () => import('@/tools/markdown-table/Index.vue'),
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 預覽 / 轉 HTML',
    category: 'workshop',
    description: '即時把 Markdown 渲染成畫面與乾淨 HTML,可複製成 Word/Email 格式化內容、下載 .html(再列印成 PDF)—— 全程在你瀏覽器,不必貼到線上編輯器、不上傳。',
    keywords: ['markdown', 'md', '預覽', 'preview', '渲染', '轉html', 'markdown轉html', 'md轉html', 'readme', '筆記', 'notion', 'hackmd', '編輯器', 'editor', '排版', '轉pdf', '格式化', '所見即所得'],
    icon: '📝',
    loader: () => import('@/tools/markdown-preview/Index.vue'),
  },
  {
    id: 'regex-tester',
    name: '正規表達式測試器',
    category: 'workshop',
    description: '即時標示正規表達式比對到哪些文字,並把那串符號逐段翻成白話中文 —— 看懂、驗證、抓擷取群組。全程在你瀏覽器,測試文字不上傳。',
    keywords: ['正規表達式', '正則', '正規式', 'regex', 'regexp', '規則', '比對', '測試', '解讀', '說明', '驗證', '擷取', '群組', '比對文字', 'pattern', '樣式', '字串比對', '匹配', '正則表達式', '正規表示式'],
    icon: '🔤',
    loader: () => import('@/tools/regex-tester/Index.vue'),
  },
  {
    id: 'curl-convert',
    name: 'curl 指令轉換',
    category: 'workshop',
    description: '把 DevTools「Copy as cURL」或文件複製來的 curl,拆成 method / 網址 / 標頭 / body,並轉成 JavaScript fetch 與 Python requests 程式碼。支援 -X -H -d -F -u -G 等;curl 常含 API token,全程在你瀏覽器解析、不上傳。',
    keywords: ['curl', 'curl轉換', 'curl converter', 'copy as curl', 'fetch', 'requests', 'python', 'javascript', 'http', 'api', '請求', 'devtools', '轉程式碼', 'curl to fetch', 'curl to python', '網路請求', '標頭', 'header', '解析curl'],
    icon: '🌐',
    loader: () => import('@/tools/curl-convert/Index.vue'),
  },
  {
    id: 'regex-gen',
    name: '反向正則(產生範例字串)',
    category: 'workshop',
    description: '給一個正規表示式,倒過來產生一批「符合該樣式」的範例字串(09\\d{8}→一堆手機號)。造測試資料、確認自己寫的 regex 到底會吃到哪些字串時最好用。支援字元類別、量詞、選擇、群組;全程在你瀏覽器,不連網、不上傳。',
    keywords: ['反向正則', '正則產生', 'regex generator', 'reverse regex', 'randexp', '產生字串', '範例字串', '測試資料', 'test data', '正規表示式', '依正則', '符合樣式', '產生符合', '假資料', 'mock', '造資料', 'pattern', '正則範例'],
    icon: '🎲',
    loader: () => import('@/tools/regex-gen/Index.vue'),
  },
  {
    id: 'base-convert',
    name: '進位轉換器',
    category: 'workshop',
    description: '二進位、八進位、十進位、十六進位一次互轉,還支援任意 2–36 進位 —— 用 BigInt 運算,64 位元以上超大整數也不失真。全程在你瀏覽器計算,不上傳。',
    keywords: ['進位', '進位轉換', '二進位', '十六進位', '八進位', '十進位', 'binary', 'hex', 'hexadecimal', 'octal', 'decimal', 'bin', 'oct', 'dec', '0x', '0b', 'base', '基底', '位元', 'bit', '轉換', '進制', '進制轉換', '36進位', 'base36', 'base32'],
    icon: '🔢',
    loader: () => import('@/tools/base-convert/Index.vue'),
  },
  {
    id: 'bitwise',
    name: '位元運算計算機',
    category: 'workshop',
    description: 'AND / OR / XOR / NOT / NAND / NOR / XNOR、左右移,支援 8/16/32/64 位元固定寬度與二補數(有號/無號對照)—— 用 BigInt 運算,64 位元也不失真。全程在你瀏覽器計算,不上傳。',
    keywords: ['位元', '位元運算', '邏輯運算', 'bitwise', 'bit', 'and', 'or', 'xor', 'not', 'nand', 'nor', 'xnor', '及', '或', '互斥或', '反相', '左移', '右移', '位移', 'shift', '遮罩', 'mask', '旗標', 'flag', '二補數', '有號', '無號', 'signed', 'unsigned', '韌體', '嵌入式', '暫存器', 'register', '十六進位', 'hex'],
    icon: '🧮',
    loader: () => import('@/tools/bitwise/Index.vue'),
  },
  {
    id: 'base32-58',
    name: 'Base32 / Base58 編解碼',
    category: 'workshop',
    description:
      '把位元組串(文字或 hex)與 Base32(RFC 4648)/ Base58(Bitcoin / IPFS)互轉。Base32 用於 TOTP 兩步驟驗證金鑰、檔名安全字串;Base58 用於錢包位址、IPFS CID。與「進位轉換器」(數字 2–36 進位)不同,這支處理位元組編碼。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'base32',
      'base58',
      'rfc 4648',
      'rfc4648',
      '編碼',
      '解碼',
      'encode',
      'decode',
      'totp',
      '兩步驟驗證金鑰',
      'bitcoin',
      'btc',
      'ipfs',
      'cid',
      '錢包位址',
      'base58check',
      '位元組',
      'bytes',
      'hex',
      '前端',
    ],
    icon: '🔡',
    loader: () => import('@/tools/base32-58/Index.vue'),
  },
  {
    id: 'hex-view',
    name: 'Hex 檢視器',
    category: 'workshop',
    description: '把檔案或文字攤開成「位移 + 十六進位 + ASCII」三欄,像 xxd / hexdump,看清檔頭魔術位元組、編碼、夾帶內容;也能把十六進位字串還原成文字。全程在你瀏覽器讀取排版,不上傳。',
    keywords: ['hex', 'hexdump', 'xxd', '十六進位', '檢視', '檢視器', 'hex viewer', 'hex editor', '位元組', 'byte', 'bytes', '檔頭', '魔術位元組', 'magic', 'binary', '二進位檔', 'ascii', 'dump', '十六進位還原', '看檔案', '原始位元組', 'raw'],
    icon: '🔣',
    loader: () => import('@/tools/hex-view/Index.vue'),
  },
  {
    id: 'float-bits',
    name: 'IEEE 754 浮點數位元檢視器',
    category: 'workshop',
    description:
      '輸入十進位數字(或反過來貼 16 進位)拆解成電腦實際儲存的符號 / 指數 / 尾數位元,並用 BigInt 完整展開「真正存進去的精確十進位值」—— 看懂為何 0.1+0.2≠0.3、浮點誤差從何而來。可切 64 位元 double / 32 位元 float,支援 NaN、Infinity 與非正規數。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'ieee754',
      'ieee 754',
      '浮點',
      '浮點數',
      'float',
      'double',
      'single',
      '單精度',
      '雙精度',
      '尾數',
      '指數',
      'mantissa',
      'exponent',
      '位元',
      'bit',
      '浮點誤差',
      '0.1+0.2',
      'floating point',
      'binary float',
      'nan',
      'infinity',
      'subnormal',
      '精度',
      '前端',
    ],
    icon: '🧮',
    loader: () => import('@/tools/float-bits/Index.vue'),
  },
  {
    id: 'text-hash',
    name: '文字雜湊值',
    category: 'workshop',
    description: '把一段文字算出 MD5 / SHA-1 / SHA-256 / SHA-384 / SHA-512 / CRC32 —— MD5、CRC32 也能離線算(瀏覽器內建加密不提供)。比對內容、產生識別碼用;全程在你瀏覽器,連密碼也不上傳。',
    keywords: ['雜湊', '雜湊值', 'hash', 'md5', 'sha', 'sha1', 'sha256', 'sha512', 'sha-256', 'crc32', 'crc', '校驗', '檢查碼', 'checksum', '加密', '摘要', 'digest', '指紋', 'fingerprint', '文字雜湊', '比對', 'etag'],
    icon: '#️⃣',
    loader: () => import('@/tools/text-hash/Index.vue'),
  },
  {
    id: 'cidr-calc',
    name: 'CIDR / 子網計算機',
    category: 'workshop',
    description: '輸入 IPv4 CIDR(如 192.168.1.10/24),立刻算出網路位址、廣播位址、可用主機範圍、子網路遮罩、萬用遮罩、主機數量,並判斷私有位址與等級。設定路由器/防火牆/伺服器必備;全程在你瀏覽器計算,不上傳。',
    keywords: ['cidr', '子網', '子網路', '網段', 'subnet', '遮罩', '子網路遮罩', 'netmask', 'mask', 'ip', 'ipv4', '網路位址', '廣播位址', 'broadcast', 'network', '主機數', 'wildcard', '萬用遮罩', '網路計算', 'ip計算', '/24', '私有ip', 'rfc1918'],
    icon: '🌐',
    loader: () => import('@/tools/cidr-calc/Index.vue'),
  },
  {
    id: 'ipv6-tools',
    name: 'IPv6 展開 / 壓縮',
    category: 'workshop',
    description:
      '貼上任意寫法的 IPv6 位址,正規化成展開式(8 組各 4 位數)與 RFC 5952 標準壓縮式(小寫、去前導零、最長零段用 :: 取代),並判斷類型(loopback / link-local / ULA / 多播 / IPv4-mapped / global)。支援 :: 省略、內嵌 IPv4、%zone。補上 cidr-calc 的 IPv4 缺口。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'ipv6',
      'ip v6',
      'ipv6 展開',
      'ipv6 壓縮',
      '位址',
      'address',
      'rfc 5952',
      'rfc5952',
      '正規化',
      '縮寫',
      '::',
      'link-local',
      'fe80',
      'ula',
      'fc00',
      'multicast',
      'ipv4-mapped',
      '網路',
      'network',
      '前端',
    ],
    icon: '🌍',
    loader: () => import('@/tools/ipv6-tools/Index.vue'),
  },
  {
    id: 'chmod-calc',
    name: 'chmod 權限計算機',
    category: 'workshop',
    description: '把 Unix 檔案權限的八進位(755)和符號表示(rwxr-xr-x)雙向對照,勾選讀/寫/執行即時看到指令,支援 setuid/setgid/sticky 並附白話說明。不必死背 chmod 數字;全程在你瀏覽器計算,不上傳。',
    keywords: ['chmod', '權限', '檔案權限', 'permission', 'permissions', 'rwx', '755', '644', 'octal', '八進位', '符號', 'symbolic', 'setuid', 'setgid', 'sticky', 'umask', 'linux', 'unix', 'ls -l', '讀寫執行', 'mode'],
    icon: '🔐',
    loader: () => import('@/tools/chmod-calc/Index.vue'),
  },
  {
    id: 'json-schema',
    name: 'JSON Schema 產生器',
    category: 'workshop',
    description: '貼上範例 JSON,自動推斷出 JSON Schema(draft-07)—— 陣列合併所有元素結構、物件 required 取交集、可偵測 email/date/uri/uuid 格式。用於 API 合約與資料驗證;全程在你瀏覽器,不上傳。',
    keywords: ['json schema', 'jsonschema', 'schema', '結構', '驗證', 'validation', 'draft-07', 'api', '合約', 'contract', 'json', '產生 schema', '推斷', 'infer', 'openapi', '資料驗證', 'json 轉 schema'],
    icon: '📐',
    loader: () => import('@/tools/json-schema/Index.vue'),
  },
  {
    id: 'totp',
    name: 'TOTP 兩步驟驗證碼',
    category: 'workshop',
    description: '輸入 2FA 設定金鑰(base32)或 otpauth:// 連結,在本機算出當下的一次性驗證碼與倒數秒數(RFC 6238,等同 Google Authenticator)。手機不在身邊時臨時登入用 —— 密鑰是高度敏感資訊,本工具全程在你瀏覽器計算、不連網、不上傳、不儲存。',
    keywords: ['totp', '2fa', '兩步驟', '兩步驟驗證', '二階段驗證', '驗證碼', '一次性密碼', 'otp', 'hotp', 'google authenticator', 'authenticator', 'authy', 'otpauth', '動態密碼', 'mfa', '雙重認證', 'rfc6238', '驗證器', 'base32'],
    icon: '🔑',
    loader: () => import('@/tools/totp/Index.vue'),
  },
  {
    id: 'hmac',
    name: 'HMAC / Webhook 簽章驗證',
    category: 'workshop',
    description: '用密鑰對訊息算 HMAC-SHA1/256/512(十六進位 + Base64),驗證 webhook 是否真的來自服務方(GitHub / Stripe / LINE)。可貼收到的簽章定時比對,自動處理 sha256= 前綴。全程在你瀏覽器,密鑰與內容不上傳。',
    keywords: ['hmac', 'webhook', '簽章', '驗章', 'signature', '驗證', 'x-hub-signature', 'github', 'stripe', 'line', '簽名', 'sign', 'sha256', 'mac', '訊息鑑別', '密鑰雜湊', 'secret', '驗簽'],
    icon: '🔏',
    loader: () => import('@/tools/hmac/Index.vue'),
  },
  {
    id: 'markdown-toc',
    name: 'Markdown 目錄產生器',
    category: 'workshop',
    description: '從 Markdown 標題自動產生帶錨點連結的目錄(TOC),錨點採 GitHub 風格 slug(保留中文、重複自動加序號),貼回 README / Issue / Notion / HackMD 即可點擊跳轉。會略過程式碼區塊;全程在你瀏覽器,不上傳。',
    keywords: ['markdown', 'toc', '目錄', 'table of contents', '大綱', '索引', '錨點', 'anchor', 'readme', '文件', 'github', 'notion', 'hackmd', '標題', 'heading', 'slug', 'md 目錄', '自動目錄'],
    icon: '🔖',
    loader: () => import('@/tools/markdown-toc/Index.vue'),
  },
  {
    id: 'ndjson-convert',
    name: 'NDJSON / JSON Lines 轉換',
    category: 'workshop',
    description: '在「每行一個 JSON」(log、資料匯出、ML 資料集、串流 API)與「JSON 陣列」之間互轉,並逐行指出哪一行壞掉(一般編輯器看不出來)、可一鍵去空白行。全程在你瀏覽器,不上傳。',
    keywords: ['ndjson', 'json lines', 'jsonl', 'jsonlines', '每行一個', 'json陣列', '互轉', 'log', '日誌', '資料集', 'dataset', '串流', 'stream', '轉換', 'json line', '逐行', '壞行', '驗證', 'jq', '匯出'],
    icon: '📑',
    loader: () => import('@/tools/ndjson-convert/Index.vue'),
  },
  {
    id: 'json-query',
    name: 'JSONPath 查詢',
    category: 'workshop',
    description: '用路徑運算式從一大包 JSON 精準撈出欄位、過濾陣列、跨層級蒐集 —— $.store.book[?(@.price<10)].title。支援萬用 [*]、切片、遞迴 ..、過濾 [?(...)](== != < > && ||)。整理 API 回應、設定檔、log 最好用;全程在你瀏覽器,不上傳。',
    keywords: ['jsonpath', 'json path', 'json查詢', 'query', '查詢', '撈資料', '取值', '過濾', 'filter', 'json篩選', '路徑', 'path', 'goessner', 'jq', '陣列過濾', '遞迴', '萬用', 'wildcard', 'json擷取', 'extract', 'api回應', '設定檔'],
    icon: '🔍',
    loader: () => import('@/tools/json-query/Index.vue'),
  },
  {
    id: 'json-repair',
    name: 'JSON 修復 / 寬鬆解析',
    category: 'workshop',
    description: '把不嚴謹的 JSON 修成標準 JSON —— 單引號、未加引號的鍵、結尾多餘逗號、// 與 /* */ 註解、Python None/True/False、NaN/Infinity 都能容忍並還原。整理 LLM 輸出、JS 物件、log 片段最好用;全程在你瀏覽器,不上傳。',
    keywords: ['json', 'json修復', '修復', 'repair', 'fix json', '寬鬆', 'lenient', '單引號', '結尾逗號', 'trailing comma', '註解', 'comment', 'json5', 'jsonc', '格式化', 'format', '美化', 'beautify', 'parse', '解析', 'llm', '修正json'],
    icon: '🩹',
    loader: () => import('@/tools/json-repair/Index.vue'),
  },
  {
    id: 'unicode-normalize',
    name: 'Unicode 正規化 / 比對',
    category: 'workshop',
    description: '解決「兩段文字看起來一樣卻不相等」—— 同一個字可能由單一碼點或基底字＋組合符號組成。提供 NFC/NFD/NFKC/NFKD 四種正規化、兩段文字比對找出在哪種形式下相等與第一個差異點,並統計組合符/全形/零寬字元。全程在你瀏覽器,不上傳。',
    keywords: ['unicode', '正規化', 'normalize', 'nfc', 'nfd', 'nfkc', 'nfkd', '組合字', '附加符號', 'combining', '全形', '半形', '相容字', '比對', '不相等', '看起來一樣', '碼點', 'codepoint', '零寬', '正規化比對'],
    icon: '🔤',
    loader: () => import('@/tools/unicode-normalize/Index.vue'),
  },
  {
    id: 'url-parse',
    name: '網址解析 / 查詢字串編輯',
    category: 'workshop',
    description: '把網址拆成協定、主機、路徑、查詢參數,參數自動解碼列成表格可直接編輯,改完即時組回 —— 一鍵清掉 utm/fbclid 等追蹤碼。全程在你瀏覽器解析,不連網、不上傳。',
    keywords: ['網址', 'url', '解析', '查詢字串', 'query string', '參數', 'parameter', 'querystring', '編碼', '解碼', 'urldecode', 'urlencode', 'utm', 'fbclid', 'gclid', '追蹤碼', '拆解', '網址參數', '編輯', '組網址', 'parse'],
    icon: '🔗',
    loader: () => import('@/tools/url-parse/Index.vue'),
  },
  {
    id: 'qs-convert',
    name: 'JSON ↔ 查詢字串轉換',
    category: 'workshop',
    description: '查詢字串與 JSON 物件互轉,支援巢狀物件與陣列的方括號表示法(a[b][]=1)—— 對接 API、debug axios/qs 參數時好用。可選 brackets/indices/repeat/comma 陣列格式。純前端、不上傳。',
    keywords: ['查詢字串', 'query string', 'querystring', 'qs', 'json', '轉換', '參數', 'params', 'url編碼', 'urlencode', '方括號', '巢狀', 'axios', 'api', '表單', 'form-urlencoded', 'serialize', '序列化', '陣列參數'],
    icon: '🔀',
    loader: () => import('@/tools/qs-convert/Index.vue'),
  },
  {
    id: 'cookie-parse',
    name: 'Cookie 解析器',
    category: 'workshop',
    description:
      '把 Set-Cookie(回應)或 Cookie(請求)標頭拆成結構化欄位 —— 名稱、值、Domain、Path、Expires、Max-Age、Secure、HttpOnly、SameSite,並用白話說明存活時間、附安全性提醒(SameSite=None 需 Secure、缺 HttpOnly/Secure 等)。網頁除錯必備。全程在你瀏覽器解析,不上傳。',
    keywords: [
      'cookie',
      'set-cookie',
      'cookie 解析',
      '餅乾',
      'httponly',
      'secure',
      'samesite',
      'max-age',
      'expires',
      'domain',
      'path',
      'session',
      '網頁除錯',
      'header',
      '標頭',
      '安全',
      'xss',
      '前端',
    ],
    icon: '🍪',
    loader: () => import('@/tools/cookie-parse/Index.vue'),
  },
  {
    id: 'har-analyze',
    name: 'HAR 網路分析',
    category: 'workshop',
    description:
      '把瀏覽器開發者工具(Network 面板)匯出的 .har 檔彙整成可讀統計 —— 總請求數、總大小、總載入時間、依狀態碼/資源類型/網域分布、最慢與最大的請求、4xx/5xx 錯誤清單,快速找出網頁效能瓶頸。HAR 常含 cookie / 授權標頭等敏感資料,故全程在你瀏覽器解析、不上傳。',
    keywords: [
      'har',
      'har 分析',
      'har 檔',
      'network',
      '網路請求',
      '效能',
      '效能分析',
      '載入速度',
      '瀏覽器',
      'devtools',
      '開發者工具',
      'waterfall',
      '瀑布圖',
      '請求',
      'http',
      '狀態碼',
      '抓包',
      '前端',
      '網頁除錯',
      'performance',
    ],
    icon: '📊',
    loader: () => import('@/tools/har-analyze/Index.vue'),
  },
  {
    id: 'security-headers',
    name: 'HTTP 安全標頭稽核',
    category: 'workshop',
    description:
      '貼上網站的 HTTP 回應標頭(curl -I 或 DevTools 看到的那串),逐項檢查 HSTS、CSP、X-Content-Type-Options、防點擊劫持、Referrer-Policy、Permissions-Policy 等安全防護是否齊全、設定是否良好,並給 A+~F 總評分與改善建議。概念類似 securityheaders.com,但全程在你瀏覽器離線判讀、不連網、不上傳。',
    keywords: [
      'security headers',
      '安全標頭',
      'http 標頭',
      'csp',
      'content-security-policy',
      'hsts',
      'strict-transport-security',
      'x-frame-options',
      'nosniff',
      'referrer-policy',
      'permissions-policy',
      '資安',
      '網站安全',
      '弱點',
      '稽核',
      'securityheaders',
      '評分',
      'header',
      '前端',
      '網頁除錯',
    ],
    icon: '🔐',
    loader: () => import('@/tools/security-headers/Index.vue'),
  },
  {
    id: 'robots-tester',
    name: 'robots.txt 測試器',
    category: 'workshop',
    description:
      '貼上 robots.txt,輸入網址與爬蟲 User-agent,立刻判斷該頁能否被抓取 —— 依 Google 規範比對:符合的群組內以最長(最具體)規則勝出、同長度 Allow 勝 Disallow,支援 * 與 $ 萬用字元,並列出解析後的群組與 Sitemap。做 SEO、檢查為何某頁沒被索引時必備。全程在你瀏覽器判讀,不連網、不上傳。',
    keywords: [
      'robots',
      'robots.txt',
      'robots 測試',
      'seo',
      '爬蟲',
      '索引',
      'crawl',
      'disallow',
      'allow',
      'user-agent',
      'googlebot',
      'sitemap',
      '搜尋引擎',
      '不被索引',
      '禁止抓取',
      '網站',
      '網管',
    ],
    icon: '🤖',
    loader: () => import('@/tools/robots-tester/Index.vue'),
  },
  {
    id: 'og-meta',
    name: 'Open Graph / SEO 標籤產生器',
    category: 'workshop',
    description:
      '填標題、描述、預覽圖等欄位,一鍵產生完整的 Open Graph(FB / LINE / Slack 分享卡)、Twitter Card 與 SEO meta 標籤,並即時看社群分享預覽;也能反向貼上現有 HTML 自動解析出欄位來檢視 / 修改。附標題與描述長度、缺漏、絕對網址等健檢提醒。全程在你瀏覽器產生,不連網、不上傳。',
    keywords: [
      'open graph',
      'og',
      'og:image',
      'og:title',
      'meta',
      'meta 標籤',
      'seo',
      'twitter card',
      '分享預覽',
      '社群分享',
      'facebook',
      'line 預覽',
      '縮圖',
      '預覽圖',
      'head',
      '網頁',
      '前端',
      'sharing',
      '連結預覽',
    ],
    icon: '🔗',
    loader: () => import('@/tools/og-meta/Index.vue'),
  },
  {
    id: 'escape-text',
    name: '文字跳脫 / 還原',
    category: 'workshop',
    description: '把含換行、引號的文字轉成可貼進 JSON/程式碼的跳脫字串,或把含 \\n、\\uXXXX、\\xXX 的字串還原成原文 —— 全程在你瀏覽器,不連網、不上傳。',
    keywords: ['跳脫', '逸出', 'escape', 'unescape', '還原', 'json字串', '字串跳脫', '反斜線', '換行', '\\n', '\\uxxxx', 'unicode跳脫', 'unicode escape', '\\xxx', '碼位', 'codepoint', '轉跳脫', '解跳脫', '字串編碼', 'stringify'],
    icon: '⌨️',
    loader: () => import('@/tools/escape-text/Index.vue'),
  },
  {
    id: 'html-to-text',
    name: 'HTML 轉純文字',
    category: 'workshop',
    description: '把從網頁、HTML 電子報複製來的內容去掉標籤、解開 &amp;amp; 等實體,保留段落換行,洗成乾淨純文字 —— 全程在你瀏覽器,不連網、不上傳。',
    keywords: ['html', '純文字', '去標籤', '去除html', '移除標籤', 'strip', 'tag', '網頁轉文字', 'html轉文字', '實體', 'entity', '解碼', '電子報', '清理', '貼上', 'plain text', '抓文字', '去html', '原始碼'],
    icon: '📰',
    loader: () => import('@/tools/html-to-text/Index.vue'),
  },
  {
    id: 'id-gen',
    name: '隨機 ID 產生器',
    category: 'workshop',
    description: 'UUID v4、ULID(含時間可排序)、Nano ID 一次大量產生,用密碼學等級亂數 —— 全程在本機產生,不連網、不上傳、不記錄(線上產生器可能偷記你的 ID)。',
    keywords: ['uuid', 'guid', 'ulid', 'nanoid', 'nano id', 'id', '識別碼', '唯一識別碼', '隨機id', '產生id', '主鍵', 'primary key', '訂單編號', '亂數id', 'v4', '識別字串', 'token', '隨機字串', '產生器'],
    icon: '🆔',
    loader: () => import('@/tools/id-gen/Index.vue'),
  },
  {
    id: 'uuid-inspect',
    name: 'UUID 檢視器',
    category: 'workshop',
    description:
      '貼上 UUID,判斷版本(v1–v8)與變體,並對含時間的版本還原內嵌的建立時間:v1/v6(100 奈秒、自 1582 起算)與 v7(Unix 毫秒、可排序)。接受連字號 / 無連字號 / urn:uuid: / 大括號格式,辨識 Nil 與 Max UUID。與隨機 ID 產生器互補(這支專做反查)。純位元解析,不查詢任何資料。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'uuid',
      'guid',
      'uuid 解析',
      'uuid 版本',
      'uuid version',
      'uuidv7',
      'uuid v7',
      'uuidv1',
      'uuid v4',
      'v7',
      '變體',
      'variant',
      '建立時間',
      'rfc 9562',
      'rfc 4122',
      'nil uuid',
      'max uuid',
      '時間戳',
      '反查',
      '前端',
    ],
    icon: '🔍',
    loader: () => import('@/tools/uuid-inspect/Index.vue'),
  },
  {
    id: 'duration',
    name: '時間長度轉換',
    category: 'workshop',
    description: '在人話(1天2小時30分)、時鐘(01:30:00)、ISO 8601(PT1H30M)、總秒/分/時之間互轉 —— 影片時長、工時、計時換算用。全程在你瀏覽器計算,不上傳。',
    keywords: ['時間長度', '時長', '時間轉換', '秒', '分鐘', '小時', '時:分:秒', 'hh:mm:ss', 'iso8601', 'duration', 'pt1h30m', '影片長度', '工時', '通話時間', '計時', '換算秒數', '幾分鐘', '幾小時', '總秒數', '時分秒'],
    icon: '⏳',
    loader: () => import('@/tools/duration/Index.vue'),
  },
  {
    id: 'timestamp-convert',
    name: 'Unix 時間戳記轉換',
    category: 'workshop',
    description: '把 log/資料庫/API 裡的 Unix 時間戳記(自動分辨秒/毫秒/微秒)轉成看得懂的日期,同時給台灣時間、UTC、ISO 8601 與相對時間 —— 全程在你瀏覽器,不上傳。',
    keywords: ['unix', 'timestamp', '時間戳記', '時間戳', 'epoch', '紀元', '秒數', '毫秒', '微秒', '時間轉換', '日期轉換', '轉時間', 'iso8601', 'iso 8601', 'utc', '時間轉日期', '日期轉時間', 'log時間', '1970', '時區'],
    icon: '🕐',
    loader: () => import('@/tools/timestamp-convert/Index.vue'),
  },
  {
    id: 'jwt-decode',
    name: 'JWT 解碼 / 檢視',
    category: 'workshop',
    description: '把 JSON Web Token 解開看標頭與內容、判斷是否過期,並可用密鑰在本機驗證 HMAC 簽章 —— 別再把正式環境的 token 貼到 jwt.io 等線上網站(等於外洩登入憑證),這支全程在你瀏覽器、不上傳。',
    keywords: ['jwt', 'json web token', 'token', '權杖', '解碼', '解析', '檢視', 'decode', 'oauth', 'bearer', '登入', '授權', 'access token', 'id token', 'payload', 'header', '簽章', 'hmac', 'hs256', 'rs256', 'exp', '過期', '驗證', 'jwt解碼', 'jwt.io'],
    icon: '🪙',
    loader: () => import('@/tools/jwt-decode/Index.vue'),
  },
  {
    id: 'jwt-sign',
    name: 'JWT 簽發 / 產生',
    category: 'workshop',
    description: '在本機用密鑰簽出 HS256/384/512 的 JSON Web Token,可自動補 iat/exp/nbf 時間宣告 —— 測 API、後端串接、重現過期情境好用。別把密鑰貼到線上產生器(等於交出能偽造憑證的鑰匙),這支全程在你瀏覽器、不上傳。',
    keywords: ['jwt', 'json web token', 'token', '權杖', '簽發', '產生', '簽章', '製作', 'encode', 'sign', 'hs256', 'hs384', 'hs512', 'hmac', '密鑰', 'secret', 'iat', 'exp', '過期', 'nbf', 'payload', 'bearer', '授權', 'api測試', 'jwt產生', 'jwt簽發', 'jwt.io'],
    icon: '🖋️',
    loader: () => import('@/tools/jwt-sign/Index.vue'),
  },
  {
    id: 'ulid-inspect',
    name: 'ULID 解析器',
    category: 'workshop',
    description:
      '貼上 ULID(26 碼 Crockford Base32 識別碼),反推內嵌的建立時間(精確到毫秒)與 80 位元亂數欄位,並用顏色拆解 48+80 位元結構。與 id-gen(產生)互補,這支專做反查;純位元解析,不查詢任何資料。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'ulid',
      'ulid 解析',
      'ulid 解碼',
      '識別碼',
      '時間排序 id',
      'lexicographically sortable',
      'crockford',
      'base32 id',
      '建立時間',
      '時間戳',
      'id 反查',
      'uuid 替代',
      '可排序識別碼',
    ],
    icon: '🪪',
    loader: () => import('@/tools/ulid-inspect/Index.vue'),
  },
  {
    id: 'semver-tools',
    name: '語意化版本工坊',
    category: 'workshop',
    description:
      '解析 SemVer、比較版本先後(含 prerelease 優先序)、測試 npm 範圍是否符合(^ ~ x 連字號 ||),並把範圍展開成基本比較子看清「為什麼符合/不符合」,還能把一串版本由舊到新排序。除錯 package.json 依賴範圍必備。全程在你瀏覽器計算,不連網、不上傳。',
    keywords: [
      'semver',
      '語意化版本',
      '版本',
      '版本號',
      '版本比較',
      '版本範圍',
      'version',
      'version range',
      'npm',
      'package.json',
      'dependency',
      '依賴',
      'caret',
      'tilde',
      '插入符',
      '波浪號',
      'satisfies',
      '相容版本',
      '排序版本',
      'prerelease',
      'rc',
      'beta',
    ],
    icon: '🏷️',
    loader: () => import('@/tools/semver-tools/Index.vue'),
  },
  {
    id: 'snowflake-id',
    name: 'Snowflake ID 解析器',
    category: 'workshop',
    description:
      '貼上 Discord / Twitter(X)/ Instagram 等服務的 Snowflake ID,反推出內嵌的建立時間(精確到毫秒)與 worker / 序號等欄位,並用顏色拆解 64 位元結構。可自訂 epoch。純位元運算,不查詢任何帳號或內容。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'snowflake',
      'snowflake id',
      'discord',
      'discord id',
      'twitter',
      'twitter id',
      'x id',
      'instagram',
      'id 解析',
      'id 時間',
      '建立時間',
      '帳號建立時間',
      '訊息時間',
      'epoch',
      '時間戳',
      'worker',
      'sequence',
      '64 位元',
      'bigint',
      '前端',
    ],
    icon: '❄️',
    loader: () => import('@/tools/snowflake-id/Index.vue'),
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML 互轉',
    category: 'workshop',
    description: 'JSON 與 YAML 雙向互轉,k8s / docker-compose / GitHub Actions 等設定檔常含密鑰 —— 全程在你瀏覽器轉換,不上傳機密設定、無廣告。',
    keywords: ['json', 'yaml', 'yml', '轉換', '互轉', '設定檔', 'config', 'kubernetes', 'k8s', 'docker', 'docker-compose', 'compose', 'github actions', 'ci', '密鑰', '金鑰', '格式轉換', 'json轉yaml', 'yaml轉json'],
    icon: '🧾',
    loader: () => import('@/tools/json-yaml/Index.vue'),
  },
  {
    id: 'data-extract',
    name: '文字資料抽取',
    category: 'workshop',
    description: '從一大段文字裡一次抓出所有 Email、網址、台灣手機、有效統一編號(統編經檢查碼驗證),自動去重 —— 全程在你瀏覽器,不上傳。',
    keywords: ['抽取', '擷取', '抓', 'email', '信箱', '電子郵件', '網址', 'url', '連結', '手機', '電話', '統編', '統一編號', '名單', '整理', '撈', 'extract', '蒐集'],
    icon: '🧲',
    loader: () => import('@/tools/data-extract/Index.vue'),
  },
  {
    id: 'json-flatten',
    name: 'JSON 攤平轉表格',
    category: 'workshop',
    description: '把巢狀 JSON(物件裡有物件、陣列)壓平成路徑欄位(addr.city、tags[0]),一列一筆轉成 CSV 丟進 Excel —— 全程在你瀏覽器,不上傳。',
    keywords: ['json', '攤平', '扁平化', 'flatten', '巢狀', 'json轉csv', 'json轉excel', 'json轉表格', 'api', '展開', '結構', '轉表格', 'unnest'],
    icon: '🪺',
    loader: () => import('@/tools/json-flatten/Index.vue'),
  },
  {
    id: 'data-chart',
    name: '資料圖表產生器',
    category: 'workshop',
    description: '貼上 CSV/Excel 表格,選欄位即畫成長條圖、折線圖或圓餅圖,下載 SVG(向量,放大不模糊)或 PNG —— 全程在你瀏覽器繪製,含營業數字的資料不上傳、無廣告、無浮水印、免註冊。',
    keywords: ['圖表', '製圖', '畫圖', '長條圖', '柱狀圖', 'bar chart', '折線圖', '線圖', 'line chart', '圓餅圖', '圓形圖', '派圖', 'pie chart', '統計圖', '視覺化', 'chart', 'graph', '資料視覺化', 'csv轉圖表', 'excel圖表', '數據圖', '報表', '簡報圖表', '下載圖表', 'svg', 'png'],
    icon: '📊',
    loader: () => import('@/tools/data-chart/Index.vue'),
  },
  {
    id: 'table-stats',
    name: '表格統計 / 樞紐',
    category: 'workshop',
    description: '依某欄分組,馬上算出各組的筆數、加總、平均、最大最小 —— 等同 Excel 樞紐分析,免拉樞紐表;全程在你瀏覽器,資料不上傳。',
    keywords: ['樞紐', '樞紐分析', '統計', '分組', 'group by', '加總', '小計', '平均', '計數', '筆數', '彙總', '彙整', 'pivot', 'sum', 'count', 'csv', 'excel', '業績', '報表'],
    icon: '📊',
    loader: () => import('@/tools/table-stats/Index.vue'),
  },
  {
    id: 'table-merge',
    name: '表格合併 / VLOOKUP',
    category: 'workshop',
    description: '把兩份名單依共同欄位(Email、學號、統編)對起來併成一張,等同 Excel VLOOKUP,免寫公式 —— 全程在你瀏覽器,含個資的名單不上傳。',
    keywords: ['表格合併', '合併', 'vlookup', 'join', '對應', '比對合併', '兩個表格', '兩張表', 'csv', 'excel', '名單', '對起來', '查表', 'lookup', 'merge', '關聯'],
    icon: '🔗',
    loader: () => import('@/tools/table-merge/Index.vue'),
  },
  {
    id: 'table-clean',
    name: '表格清理工坊',
    category: 'workshop',
    description: '貼上 CSV/Excel 名單,一鍵去重複、刪空白列、篩選、排序、只留需要的欄,再匯出 CSV/JSON —— 全程在你瀏覽器,含個資的名單不上傳。',
    keywords: ['表格', '清理', 'csv', 'tsv', 'excel', '名單', '去重複', '重複', '篩選', '排序', '刪欄', '選欄', '整理', '去空白', '空列', '資料清理', 'dedupe', 'clean'],
    icon: '🧹',
    loader: () => import('@/tools/table-clean/Index.vue'),
  },
  {
    id: 'table-split',
    name: '表格拆分',
    category: 'workshop',
    description: '把一份大 CSV/Excel 名單拆成多份:按每 N 列平均切,或按某欄的值分組(依區域、業務、月份各自一份)—— 打包成 ZIP 或匯出單一多工作表 Excel。全程在你瀏覽器,含個資的名單不上傳。',
    keywords: ['表格', '拆分', '分割', '切割', '拆開', '分檔', '分組', '分群', 'csv', 'excel', 'xlsx', '名單', '訂單', '按欄位', '依欄位', '分區', '分業務', '每n列', '切成多份', 'split', '大檔', '分批'],
    icon: '📑',
    loader: () => import('@/tools/table-split/Index.vue'),
  },
  {
    id: 'list-compare',
    name: '名單比對 / 去重',
    category: 'workshop',
    description: '一份名單去重(找出重複幾次),或比對兩份名單的交集 / 差集 —— 對帳、找「誰還沒繳」最實用。全程在你瀏覽器,不上傳含個資的名單。',
    keywords: ['名單', '去重', '重複', '比對', '比較', '交集', '差集', '聯集', '對帳', '清單', 'email', '去除重複', '兩份', '找不同', '差異', '誰沒繳', '核對', 'dedupe', 'diff', '集合'],
    icon: '🗂️',
    loader: () => import('@/tools/list-compare/Index.vue'),
  },
  {
    id: 'vcard-maker',
    name: 'vCard 聯絡人產生器',
    category: 'workshop',
    description: '把單筆聯絡人,或一份 Excel/CSV 通訊錄,做成 .vcf 檔,直接匯入 iPhone / Android / Google / Apple / Outlook 聯絡人 —— 線上轉換器要你上傳含姓名電話的個資名單,本工具全程在你瀏覽器處理、不上傳。',
    keywords: ['vcard', 'vcf', '聯絡人', '通訊錄', '名片', '電話簿', '匯入聯絡人', 'contacts', '聯絡資訊', '匯入手機', 'google聯絡人', 'iphone聯絡人', 'csv轉vcard', 'excel轉聯絡人', '批次', '名單', '電話', '同學會', '社團'],
    icon: '👤',
    loader: () => import('@/tools/vcard-maker/Index.vue'),
  },
  {
    id: 'fake-data',
    name: '測試假資料產生器',
    category: 'workshop',
    description: '一鍵產生大量「擬真但完全虛構」的台灣個資(姓名、身分證、統編、手機、地址、Email…),身分證/統編檢查碼正確、能過格式驗證,但不對應任何真人 —— 開發測試別再拿真客戶資料,全程在你瀏覽器產生、不上傳,可指定種子重現、匯出 CSV/JSON。',
    keywords: ['假資料', '測試資料', '假個資', '假身分證', '假統編', '隨機資料', '範例資料', '示範資料', '亂數姓名', '產生器', '填表測試', 'mock', 'fake', 'dummy', 'test data', 'sample', '身分證產生', '假名單', '塞資料', '測資'],
    icon: '🧪',
    loader: () => import('@/tools/fake-data/Index.vue'),
  },
  {
    id: 'mail-merge',
    name: '合併列印 / 套印',
    category: 'workshop',
    description: '一份範本({{姓名}} 等佔位符)+ 一份名單,幫每個人各產生一段填好內容的文字 —— 年節祝福、開會通知、繳費提醒、邀請函不用一個個改名字。可直接貼 Excel,全程在你瀏覽器,名單不上傳。',
    keywords: ['合併列印', '套印', '範本', '樣板', '佔位符', '群發', '批次', '通知', '祝福', '邀請函', '名單', '客製', 'mail merge', 'template', '個人化', '繳費提醒', 'excel'],
    icon: '📨',
    loader: () => import('@/tools/mail-merge/Index.vue'),
  },
  {
    id: 'zip-studio',
    name: 'ZIP 工坊',
    category: 'workshop',
    description: '把多個檔案打包成一個 .zip,或把收到的 .zip 在本機解開檢視/取檔 —— 全程在你瀏覽器,不上傳、無廣告、不限檔數大小。',
    keywords: ['zip', '壓縮', '解壓', '解壓縮', '打包', '封存', 'archive', 'compress', 'extract', 'unzip', '附件', '多檔', '資料夾', '合併檔案'],
    icon: '🗜️',
    loader: () => import('@/tools/zip-studio/Index.vue'),
  },
  {
    id: 'batch-rename',
    name: '批次檔案改名',
    category: 'workshop',
    description: '一次替整批照片/文件改名:加前後綴、流水號(可補零)、改大小寫、把檔名裡某段文字換掉 —— 即時預覽舊→新,打包成 ZIP 下載。全程在你瀏覽器,檔案不上傳。',
    keywords: ['改名', '重新命名', '批次改名', '檔名', '重命名', '改檔名', '流水號', '編號', '序號', '前綴', '後綴', '取代', '大小寫', '照片改名', 'rename', 'batch', '一次改', '整批', '相片命名'],
    icon: '🔤',
    loader: () => import('@/tools/batch-rename/Index.vue'),
  },
  {
    id: 'file-split',
    name: '檔案分割 / 合併',
    category: 'workshop',
    description: '大檔寄不出去?把任何檔案切成小份分批傳(email/LINE/雲端有大小限制),收到後再合併還原 —— 全程在你瀏覽器處理,不上傳、無廣告。用標準 .001 命名,對方也能用內建指令合併。',
    keywords: ['分割', '切割', '合併', '切檔', '分檔', '大檔', '檔案太大', '太大', '寄不出去', '上傳限制', '附件太大', 'split', 'join', 'merge', '001', 'hjsplit', '分卷', '拆檔', '影片太大', '備份'],
    icon: '🪓',
    loader: () => import('@/tools/file-split/Index.vue'),
  },
  {
    id: 'screenshot-beautify',
    name: '截圖美化',
    category: 'workshop',
    description: '幫螢幕截圖加上漸層背景、圓角、陰影與 Mac 風格視窗列,貼進簡報、社群、部落格立刻變專業 —— 可直接 Ctrl+V 貼上,選好輸出比例(IG/YT 縮圖)。全程在你瀏覽器合成,圖片不上傳、無廣告、無浮水印。',
    keywords: ['截圖', '美化', '截圖美化', '背景', '漸層', '圓角', '陰影', '視窗列', '產品圖', '社群', 'ig', 'instagram', '簡報', '封面', '縮圖', 'mockup', 'beautify', 'screenshot', '加背景', '邊框', '截圖加框'],
    icon: '🖼️',
    loader: () => import('@/tools/screenshot-beautify/Index.vue'),
  },
  {
    id: 'image-stitch',
    name: '圖片拼接(長圖)',
    category: 'workshop',
    description: '把多張截圖、收據、對話接成一張長圖或長條 —— 縱向/橫向、可調間距對齊,全程在你瀏覽器合成,不上傳、無廣告、無浮水印。',
    keywords: ['拼接', '拼圖', '長圖', '合併圖片', '接圖', '截圖', '對話', 'line對話', '收據', '併圖', '組圖', '直向', '橫向', '長截圖', '合成', 'stitch', '對比圖'],
    icon: '🧩',
    loader: () => import('@/tools/image-stitch/Index.vue'),
  },
  {
    id: 'image-crop',
    name: '圖片裁切 / 旋轉',
    category: 'workshop',
    description: '把拍歪的照片轉正、裁掉多餘背景或框出重點 —— 旋轉、翻轉、拖曳裁切,全程在你瀏覽器處理,不上傳、無廣告、無浮水印,可隨時復原。',
    keywords: ['裁切', '裁剪', '剪裁', '旋轉', '轉正', '翻轉', '鏡像', '剪掉', '去背景', '框選', '照片', '圖片', '相片', 'crop', 'rotate', '橫的', '直的', '拍歪'],
    icon: '✂️',
    loader: () => import('@/tools/image-crop/Index.vue'),
  },
  {
    id: 'image-grid',
    name: 'IG 九宮格切圖',
    category: 'workshop',
    description: '把一張大圖切成九宮格,依序發到 Instagram 主頁就拼成一整張大圖牆 —— 自動算好發文順序、置中裁切,全程在你瀏覽器處理,圖片不上傳、無廣告、無浮水印。',
    keywords: ['九宮格', '切圖', '切割', 'ig', 'instagram', '主頁', '大圖', 'banner', '拼圖', '網格', 'grid', '分割圖片', '一張切多張', '版面', '個人檔案', '照片牆', '切九宮格'],
    icon: '⊞',
    loader: () => import('@/tools/image-grid/Index.vue'),
  },
  {
    id: 'id-photo',
    name: '證件照排版(4×6)',
    category: 'workshop',
    description: '把一張大頭照排成一張 4×6 相片紙的多張一吋/二吋證件照,300 DPI 可直接拿去沖洗 —— 全程在你瀏覽器處理,臉部照片不上傳、無廣告、無浮水印,免上傳到陌生網站或花錢請相館。',
    keywords: ['證件照', '大頭照', '一吋', '二吋', '證件', '護照照片', '身分證照片', '排版', '相片紙', '4x6', '4×6', '沖洗', '沖印', '大頭貼', '駕照照片', '履歷照', 'id photo', '證件相'],
    icon: '📸',
    loader: () => import('@/tools/id-photo/Index.vue'),
  },
  {
    id: 'text-table',
    name: '等寬純文字表格',
    category: 'workshop',
    description: '把 CSV/TSV(可從 Excel 整塊複製貼上)轉成在等寬字型下對齊的純文字表格(框線 / ASCII / 簡潔),貼進純文字 email、程式碼註解、Slack、README —— 純前端,不上傳。',
    keywords: ['純文字表格', 'ascii表格', 'ascii table', '等寬表格', '對齊', '文字表格', 'box drawing', '框線表格', 'plain text', 'csv轉表格', 'tsv', '程式碼註解', 'slack表格', 'readme', '終端機', '表格對齊'],
    icon: '📐',
    loader: () => import('@/tools/text-table/Index.vue'),
  },
  {
    id: 'dup-photos',
    name: '重複 / 相似照片偵測',
    category: 'workshop',
    description: '一次選多張照片,用感知雜湊找出重複或近似(改過尺寸、重新存檔、輕微壓縮)的照片,幫你清理相簿 —— 全程在你瀏覽器比對,照片不上傳。',
    keywords: ['重複照片', '相似照片', '找重複', '重複圖片', '清理相簿', '整理照片', '去重', '重複檔案', 'duplicate', '近似圖', '感知雜湊', 'phash', 'dhash', '相似度', '照片整理', '釋放空間'],
    icon: '🖼️',
    loader: () => import('@/tools/dup-photos/Index.vue'),
  },
  {
    id: 'ini-convert',
    name: 'INI / 設定檔 ↔ JSON',
    category: 'workshop',
    description: '把 INI 設定檔(含區段、註解)轉成 JSON,或把 JSON 物件倒成 INI —— 設定常含金鑰密碼,全程在你瀏覽器處理,不上傳。',
    keywords: ['ini', '設定檔', 'config', 'conf', '組態', '區段', 'section', 'json', '互轉', '轉換', '金鑰', '密碼', '設定轉json', 'desktop entry', 'cfg'],
    icon: '⚙️',
    loader: () => import('@/tools/ini-convert/Index.vue'),
  },
  {
    id: 'dotenv-convert',
    name: '.env ↔ JSON / shell 轉換',
    category: 'workshop',
    description: '把 .env 設定檔轉成 JSON 物件或 shell export,反之亦然;支援註解、引號與跳脫 —— .env 常含金鑰密碼,全程在你瀏覽器處理,不上傳。',
    keywords: ['env', '.env', 'dotenv', '環境變數', 'environment', 'json', 'shell', 'export', '設定檔', 'config', '金鑰', '密碼', 'ci', '互轉', '轉換'],
    icon: '🔑',
    loader: () => import('@/tools/dotenv-convert/Index.vue'),
  },
  {
    id: 'toml-convert',
    name: 'TOML ↔ JSON 互轉',
    category: 'workshop',
    description: '把 Cargo.toml / pyproject.toml / netlify.toml 等 TOML 設定檔轉成 JSON,或把 JSON 倒回 TOML —— 支援巢狀表、陣列表、inline table、點分鍵。設定常含金鑰密碼,全程在你瀏覽器處理,不上傳。',
    keywords: ['toml', 'json', '互轉', '轉換', 'cargo.toml', 'pyproject.toml', 'pyproject', 'netlify.toml', 'config.toml', '設定檔', 'config', 'rust', 'python', '金鑰', '密碼', 'toml轉json', 'json轉toml', '陣列表', 'inline table'],
    icon: '🦀',
    loader: () => import('@/tools/toml-convert/Index.vue'),
  },
  {
    id: 'properties-convert',
    name: 'Java .properties ↔ JSON',
    category: 'workshop',
    description: '把 Java / Spring / Android 的 .properties 設定檔、語系檔轉成 JSON,或倒回 .properties —— 正確處理 \\uXXXX 萬國碼、=/:/空白 分隔、反斜線續行與跳脫。設定常含金鑰密碼,全程在你瀏覽器處理,不上傳。',
    keywords: ['properties', '.properties', 'java', 'spring', 'springboot', 'android', 'i18n', '語系', '語系檔', '在地化', 'messages', 'application.properties', 'json', '互轉', '轉換', '設定檔', 'config', '金鑰', '密碼', 'unicode', 'uXXXX', '萬國碼', '跳脫', '續行'],
    icon: '☕',
    loader: () => import('@/tools/properties-convert/Index.vue'),
  },
  {
    id: 'bg-color-key',
    name: '去純色背景 → 透明',
    category: 'workshop',
    description: '點一下背景色,把白底、綠幕、純色背景變透明,輸出透明 PNG —— 即時、免下載 AI 模型,最適合 logo、掃描的簽名/印章、線稿。全程在你瀏覽器,圖片不上傳。',
    keywords: ['去背', '去白底', '去背景', '純色去背', '綠幕', '去綠幕', '透明背景', '退底', '摳圖', 'logo去背', '簽名去背', '印章', '線稿', 'chroma', 'png', '背景變透明', '吸色'],
    icon: '🪄',
    loader: () => import('@/tools/bg-color-key/Index.vue'),
  },
  {
    id: 'color-scale',
    name: '色階產生器',
    category: 'workshop',
    description: '從一個主色生出 50~950 的明暗色階(設計系統色板),一鍵複製成 CSS 變數 / Tailwind 設定 / JSON —— 純前端計算,不連網、不上傳。',
    keywords: ['色階', '色板', '配色', '調色盤', 'palette', 'shade', 'tint', 'color scale', '主題色', '設計系統', 'tailwind', 'css變數', '深淺', '色票', '明暗', '50 900', 'design system'],
    icon: '🌈',
    loader: () => import('@/tools/color-scale/Index.vue'),
  },
  {
    id: 'palette-extract',
    name: '圖片調色盤萃取',
    category: 'workshop',
    description: '上傳一張圖,用 median cut 量化取出最具代表性的 4–12 個主色,附每色佔比與可直接貼用的 HEX / RGB / CSS 變數 / JSON。做設計取色、配色參考用 —— 全程在你的瀏覽器以 canvas 運算,圖片不上傳、不連網。',
    keywords: ['調色盤', '配色', '取色', '主色', 'palette', 'color palette', 'extract', '圖片取色', '色票', '從圖片', 'dominant color', '主題色', '量化', 'median cut', 'coolors', 'eyedropper', '吸色', '色彩', '設計取色', 'hex'],
    icon: '🎨',
    loader: () => import('@/tools/palette-extract/Index.vue'),
  },
  {
    id: 'color-mix',
    name: '色彩混合器',
    category: 'workshop',
    description:
      '兩種模式:混色(兩色依比例在 sRGB 內插,等同 CSS color-mix,並列出色階)與疊色(把帶透明度的前景疊在背景上,算出最終看到的實色)。解析 #hex / #hexa / rgb() / rgba(),輸出 HEX 與 RGB。補齊色彩工坊系列。全程在你瀏覽器計算,不上傳。',
    keywords: [
      '混色',
      '色彩混合',
      'color mix',
      'color-mix',
      '疊色',
      '透明度',
      'alpha',
      'rgba',
      '半透明',
      '合成',
      'compositing',
      '混合顏色',
      '兩色',
      '中間色',
      '內插',
      '配色',
      '顏色',
      'css',
      '前端',
    ],
    icon: '🧪',
    loader: () => import('@/tools/color-mix/Index.vue'),
  },
  {
    id: 'ua-parser',
    name: 'User-Agent 解析器',
    category: 'workshop',
    description:
      '貼上 User-Agent 字串,拆出瀏覽器、版本、排版引擎、作業系統與裝置類型(桌機/手機/平板/爬蟲)。看 server log、分析流量、debug 相容性時很常用,可一鍵帶入自己的瀏覽器。全程在你的瀏覽器解析,不連網、不上傳。',
    keywords: [
      'user agent',
      'user-agent',
      'ua',
      'ua 解析',
      'useragent',
      '瀏覽器偵測',
      '裝置偵測',
      '作業系統',
      '排版引擎',
      'webkit',
      'blink',
      'gecko',
      'chrome',
      'safari',
      'firefox',
      'edge',
      '爬蟲',
      'bot',
      'log',
      '流量分析',
      '前端',
    ],
    icon: '🕵️',
    loader: () => import('@/tools/ua-parser/Index.vue'),
  },
  {
    id: 'svg-to-png',
    name: 'SVG → PNG / 點陣圖匯出',
    category: 'workshop',
    description: '把向量 SVG 在任意解析度轉成 PNG / JPG / WebP,可指定寬高、背景與品質 —— 全程在你瀏覽器用 canvas 繪製,SVG 不上傳、無廣告、無浮水印。',
    keywords: ['svg', 'svg轉png', 'svg轉圖', '向量轉點陣', '向量轉圖', 'png', 'jpg', 'webp', 'svg轉檔', 'svg匯出', '高解析', '放大不模糊', 'rasterize', '圖示轉png', 'logo轉png', 'icon'],
    icon: '🖌️',
    loader: () => import('@/tools/svg-to-png/Index.vue'),
  },
  {
    id: 'image-base64',
    name: 'Base64 / Data URI 圖片互轉',
    category: 'workshop',
    description: '把圖片轉成 Base64 / Data URI 字串(內嵌進 HTML/CSS/Markdown,附現成片段),或把 Data URI / Base64 還原成可下載的圖片 —— 全程在你瀏覽器,圖片不上傳。',
    keywords: ['base64', 'data uri', 'datauri', 'data url', '圖片轉base64', 'base64轉圖片', '內嵌圖片', '圖片編碼', '圖片解碼', '轉字串', 'img', 'css background', 'inline image', '簽名檔', 'email圖片', '編碼', '解碼'],
    icon: '🔤',
    loader: () => import('@/tools/image-base64/Index.vue'),
  },
  {
    id: 'favicon-gen',
    name: '網站圖示 / Favicon 產生器',
    category: 'workshop',
    description: '上傳一張圖,輸出 favicon.ico(內含 16/32/48 多尺寸)、apple-touch-icon 與 PWA 圖示(192/512),附可直接貼上的 HTML —— 全程在你瀏覽器處理,logo 不上傳、無廣告、不綁追蹤。',
    keywords: ['favicon', 'ico', '網站圖示', '圖示', 'icon', '網站小圖', '分頁圖示', 'apple-touch-icon', 'pwa', '網站logo', 'logo轉ico', '製作favicon', '圖轉ico', '網頁圖示'],
    icon: '🌐',
    loader: () => import('@/tools/favicon-gen/Index.vue'),
  },
  {
    id: 'audio-studio',
    name: '音訊工坊',
    category: 'workshop',
    description: '載入音檔,裁剪片段(做鈴聲)、淡入淡出、調音量、轉單聲道,匯出無失真 WAV —— 全程在你瀏覽器,音檔不上傳、無廣告、無浮水印、不限時長。',
    keywords: ['音訊', '音樂', '音檔', '聲音', '剪輯', '裁剪', '剪音樂', '剪歌', '鈴聲', '來電鈴聲', '截取', '淡入', '淡出', '音量', '正規化', '轉單聲道', 'mp3', 'wav', 'm4a', '剪音訊', '音訊剪輯', 'audio', 'trim'],
    icon: '🎵',
    loader: () => import('@/tools/audio-studio/Index.vue'),
  },
  {
    id: 'subtitle-studio',
    name: '字幕工坊(SRT/VTT)',
    category: 'workshop',
    description: 'SRT ↔ WebVTT 互轉、整體平移對時(字幕快/慢幾秒)、速率縮放、自動重新編號 —— 全程在你瀏覽器處理,字幕內容不上傳、無廣告、免註冊。',
    keywords: ['字幕', 'srt', 'vtt', 'webvtt', '字幕轉檔', '字幕格式', '對時', '平移', '時間軸', '同步', '不同步', '快了', '慢了', '延遲', '影片字幕', '電影字幕', '轉換', '字幕檔'],
    icon: '🎬',
    loader: () => import('@/tools/subtitle-studio/Index.vue'),
  },
  {
    id: 'text-diff',
    name: '文字差異比對',
    category: 'workshop',
    description: '比對合約改版、條款、規格新舊兩版,逐行加逐字標出改了哪裡 —— 全程在你瀏覽器,不上傳機密文字、無廣告。',
    keywords: ['比對', '差異', '差別', '比較', 'diff', '兩份', '新舊', '改版', '版本', '合約', '條款', '對照', '哪裡不同', '逐字', '文字比對', 'compare', '異動'],
    icon: '📝',
    loader: () => import('@/tools/text-diff/Index.vue'),
  },
  {
    id: 'unified-diff',
    name: 'Unified diff / patch 產生器',
    category: 'workshop',
    description:
      '把兩段文字比對,輸出標準的 unified diff(統一差異)—— 含 --- / +++ 與 @@ 區塊,可一鍵複製或下載成 .patch,直接用 git apply / patch 套用,或貼進 PR 說明。可調上下文行數、忽略大小寫/行尾空白。與「文字差異比對」互補(那支視覺逐行對照,這支產出可機器套用的 patch)。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'diff',
      'patch',
      'unified diff',
      '統一差異',
      'git diff',
      'git apply',
      '.patch',
      '修補檔',
      '差異',
      '補丁',
      'code review',
      '程式碼審查',
      'pr',
      '版本',
      '比對',
      'diff -u',
      '開發',
    ],
    icon: '🩹',
    loader: () => import('@/tools/unified-diff/Index.vue'),
  },
  {
    id: 'image-redact',
    name: '圖片遮蔽(塗黑/馬賽克)',
    category: 'workshop',
    description: '分享截圖前,把身分證、地址、帳號等個資塗黑或打馬賽克 —— 全程在你瀏覽器,不上傳、真的把像素塗掉、無廣告。',
    keywords: ['遮蔽', '塗黑', '馬賽克', '打碼', '去碼', '隱私', '個資', '截圖', '遮住', '隱藏', '模糊', '身分證', '帳號', '保護'],
    icon: '🌫️',
    loader: () => import('@/tools/image-redact/Index.vue'),
  },
  {
    id: 'text-redact',
    name: '文字個資遮蔽',
    category: 'anti-scam',
    description: '貼上對話/單據文字,自動找出身分證、手機、信用卡、Email 並打碼 —— 轉貼客服對話、分享截圖文字前先遮個資。全程在你瀏覽器以規則比對,不上傳;身分證/信用卡會驗證檢查碼避免誤判。',
    keywords: ['個資', '遮蔽', '打碼', '去識別', '隱私', '身分證', '手機', '信用卡', '卡號', 'email', '電子郵件', '遮個資', '對話', '客服', '截圖文字', '保護個資', '去除個資', '罩'],
    icon: '🕵️',
    loader: () => import('@/tools/text-redact/Index.vue'),
  },
  {
    id: 'image-watermark',
    name: '證件浮水印加註',
    category: 'workshop',
    description: '交付證件影本前,斜向重複加註用途(例:僅供開戶使用)防盜用 —— 全程在你瀏覽器,文字直接燒進像素、不上傳、無廣告、可批次。',
    keywords: ['浮水印', '證件', '影本', '加註', '防盜用', '身分證', '開戶', '門號', '租屋', '影印', '騎縫', '劃線', '保護', '批次', 'watermark'],
    icon: '🖋️',
    loader: () => import('@/tools/image-watermark/Index.vue'),
  },
  {
    id: 'qr-generate',
    name: 'QR Code 產生器',
    category: 'workshop',
    description: '把網址、WiFi 連線、聯絡資訊做成 QR Code,可下載 PNG —— 直接編碼你的原始內容,不像多數線上產生器偷塞追蹤短網址轉址。全程在你瀏覽器,不上傳。',
    keywords: ['qr', 'qrcode', 'qr code', '二維碼', '條碼', '產生', '製作', 'wifi', '無線網路', '聯絡', '名片', 'vcard', '網址', '連結', '掃描'],
    icon: '🔳',
    loader: () => import('@/tools/qr-generate/Index.vue'),
  },
  {
    id: 'qr-batch',
    name: '批次 QR Code',
    category: 'workshop',
    description: '一份清單一次做成很多個 QR Code(每行一筆),打包成 ZIP 圖片或排成可直接列印的 A4 標籤頁 —— 活動桌號、財產編號、商品連結用。全程在你瀏覽器產生,清單不上傳、不轉址、不追蹤。',
    keywords: ['qr', 'qrcode', 'qr code', '二維碼', '批次', '大量', '一次', '清單', '名單', '桌號', '座位', '財產編號', '標籤', '列印', 'a4', '貼紙', '菜單', '問卷', 'batch', '多個', '產生'],
    icon: '🔳',
    loader: () => import('@/tools/qr-batch/Index.vue'),
  },
  {
    id: 'barcode-generate',
    name: '條碼產生器',
    category: 'workshop',
    description: '把料號、商品編號、書本 ISBN 做成一維條碼(CODE128 / EAN-13 / EAN-8 / UPC / CODE39 / ITF-14),可下載向量 SVG 或高解析 PNG 印標籤 —— 全程在你瀏覽器產生,不上傳、無廣告、不偷塞追蹤,輸入少打檢查碼自動補上。',
    keywords: ['條碼', '一維條碼', 'barcode', 'code128', 'ean', 'ean13', 'ean-13', 'ean8', 'upc', 'code39', 'itf', '商品條碼', '料號', '貨號', '標籤', '印標籤', 'isbn', '書號', '產生條碼', '製作條碼', '檢查碼'],
    icon: '🏷️',
    loader: () => import('@/tools/barcode-generate/Index.vue'),
  },
  {
    id: 'text-clean',
    name: '文字清理工坊',
    category: 'workshop',
    description: '從 PDF/網頁/LINE 貼上的文字常夾帶看不見的零寬字元、全形英數、多餘空白 —— 一鍵清乾淨,即時統計字數。全程在你瀏覽器,不上傳、無廣告。',
    keywords: ['文字', '清理', '整理', '去空白', '空行', '零寬', '不可見字元', '全形', '半形', '大小寫', '字數統計', '字數', '計數', '去重', '貼上', '格式化'],
    icon: '🧹',
    loader: () => import('@/tools/text-clean/Index.vue'),
  },
  {
    id: 'char-inspect',
    name: '隱形字元 / Unicode 檢視器',
    category: 'workshop',
    description: '貼上文字,逐字揪出看不見的零寬字元、異常空白、文字方向控制字元,以及長得像 ASCII 的形近字(釣魚網址、假冒帳號常用)—— 解決「兩個字串看起來一樣卻不相等」,也能防冒名。全程在你瀏覽器,不上傳。',
    keywords: ['隱形字元', '看不見的字元', '零寬', 'zero width', '零寬字元', 'unicode', '碼位', 'codepoint', '字元', '形近字', '混淆', 'confusable', '同形異字', 'homograph', '釣魚', '假冒', '冒名', '方向字元', 'bidi', 'rlo', '亂碼', '比對', '不相等', '隱藏字元', '全形空格', 'nbsp', '不斷行空格', '字數', '檢視', '檢測'],
    icon: '🔎',
    loader: () => import('@/tools/char-inspect/Index.vue'),
  },
  {
    id: 'text-stats',
    name: '文字統計 / 字數統計',
    category: 'workshop',
    description: '貼上文章,正確算出中文字數(逐字計,不像多數工具用空白切詞而把中文算錯)、英文單字、字元、行/段/句、UTF-8 位元組與預估閱讀時間,還能設字數上限即時倒數 —— 作文、自傳、書審、貼文字數限制好用。全程在你瀏覽器,不上傳。',
    keywords: ['字數', '字數統計', '文字統計', '算字數', '計字數', '幾個字', '字數限制', '字數上限', '中文字數', '英文單字', 'word count', '字元數', '行數', '段落', '句數', '閱讀時間', '作文', '自傳', '書審', '報告', '貼文', '字數計算', '統計字數'],
    icon: '🔢',
    loader: () => import('@/tools/text-stats/Index.vue'),
  },
  {
    id: 'line-tools',
    name: '清單加工(每行轉清單)',
    category: 'workshop',
    description: '把貼上的一欄資料(每行一筆,常從 Excel 複製)變成可直接貼用的清單:SQL IN 清單 (\'a\',\'b\')、逗號清單、JSON 字串陣列、Markdown/編號清單 —— 可去空白行、去重、加引號(自動逸出)、加前後綴。全程在你瀏覽器,不上傳內部名單/ID。',
    keywords: ['清單', '每行', '一欄', '逗號清單', 'sql in', 'in 清單', '陣列', 'json 陣列', '加引號', '前綴', '後綴', '編號', 'markdown 清單', '去重', '換行', '串成一行', '逗號分隔', '一行一筆', '貼上', '加工', 'list'],
    icon: '📋',
    loader: () => import('@/tools/line-tools/Index.vue'),
  },
  {
    id: 'case-convert',
    name: '命名格式轉換(camelCase/snake_case)',
    category: 'workshop',
    description:
      '把變數名/欄位名/詞句在 camelCase、PascalCase、snake_case、CONSTANT_CASE、kebab-case、Title Case 等命名慣例之間互轉,自動辨識原本格式並拆字;支援多行批次(每行一筆),一次轉一整欄。全程在你瀏覽器,不上傳。',
    keywords: [
      '命名',
      '命名慣例',
      '命名規則',
      '大小寫',
      '大小寫轉換',
      'camelCase',
      '駝峰',
      '小駝峰',
      '大駝峰',
      'PascalCase',
      'snake_case',
      '蛇形',
      '底線命名',
      'kebab-case',
      '連字號',
      'CONSTANT_CASE',
      '常數命名',
      '全大寫',
      'Title Case',
      '變數名',
      '欄位名',
      'case converter',
      '格式轉換',
    ],
    icon: '🔡',
    loader: () => import('@/tools/case-convert/Index.vue'),
  },
  {
    id: 'lorem-ipsum',
    name: '假文 / Lorem Ipsum 產生器',
    category: 'workshop',
    description:
      '做版面/設計稿時要填的「假內文」—— 拉丁 Lorem Ipsum(可選經典開頭)＋中文假文(多數線上工具只有拉丁文,這裡能產生中文版面用的佔位文字)。可選段落/句子/字數量,固定種子可重現同一批。全程在你瀏覽器,不上傳。',
    keywords: [
      '假文',
      '假內文',
      '佔位文字',
      '佔位符',
      'placeholder',
      'lorem',
      'lorem ipsum',
      '亂數文字',
      '範例文字',
      '填充文字',
      '中文假文',
      '排版',
      '版面',
      '設計稿',
      'mockup',
      'dummy text',
      'filler',
      '亂文',
    ],
    icon: '📃',
    loader: () => import('@/tools/lorem-ipsum/Index.vue'),
  },
  {
    id: 'box-shadow',
    name: 'CSS 陰影產生器(box-shadow)',
    category: 'workshop',
    description:
      '視覺化調出 CSS box-shadow —— 多層陰影、X/Y 位移、模糊、擴散、顏色＋透明度、內陰影(inset),即時預覽方塊效果,一鍵複製可直接貼用的 CSS。附柔和卡片/懸浮/內凹/霓虹範本。補齊漸層/色階視覺工坊系列。全程在你瀏覽器,不上傳。',
    keywords: [
      'box-shadow',
      '陰影',
      'css 陰影',
      '投影',
      '陰影產生器',
      'shadow',
      'drop shadow',
      'inset',
      '內陰影',
      '霓虹',
      '光暈',
      'glow',
      '卡片陰影',
      '懸浮',
      'css 產生器',
      '前端',
      'ui',
    ],
    icon: '🌒',
    loader: () => import('@/tools/box-shadow/Index.vue'),
  },
  {
    id: 'cubic-bezier',
    name: 'CSS 緩動曲線編輯器(cubic-bezier)',
    category: 'workshop',
    description:
      '拖動兩個控制點即時調出 CSS 動畫節奏 —— 自訂 cubic-bezier 緩動曲線,右側方塊用瀏覽器真實 transition 重播預覽,支援回彈/過衝,一鍵複製函式或完整 CSS。可貼上既有曲線載入。附 ease/ease-in-out/回彈等範本。補齊漸層/陰影/色階視覺工坊系列。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'cubic-bezier',
      '緩動',
      '緩動曲線',
      '動畫曲線',
      'easing',
      'ease',
      'ease-in',
      'ease-out',
      'ease-in-out',
      'transition',
      'transition-timing-function',
      'css 動畫',
      'animation',
      '貝茲曲線',
      'bezier',
      '回彈',
      '過衝',
      '彈跳',
      'css 產生器',
      '前端',
      'ui',
    ],
    icon: '📈',
    loader: () => import('@/tools/cubic-bezier/Index.vue'),
  },
  {
    id: 'clamp-generator',
    name: 'CSS clamp() 流體字級產生器',
    category: 'workshop',
    description:
      '給小螢幕與大螢幕各自的字級/間距,自動算出隨視窗寬度平滑縮放的 clamp() CSS(中間用 vw、兩端夾住),免手刻流體排版公式。附互動預覽:拖動模擬視窗寬度看實際解析尺寸。可選 rem/px、自訂根字級、套用到 font-size/padding/margin 等。補齊漸層/陰影/緩動視覺工坊系列。全程在你瀏覽器計算,不上傳。',
    keywords: [
      'clamp',
      'css clamp',
      '流體字級',
      '流體排版',
      'fluid typography',
      '響應式字級',
      'responsive',
      'rwd',
      'vw',
      '字級縮放',
      'font-size',
      '響應式間距',
      'utopia',
      'css 產生器',
      '前端',
      'ui',
    ],
    icon: '🔠',
    loader: () => import('@/tools/clamp-generator/Index.vue'),
  },
  {
    id: 'css-specificity',
    name: 'CSS 選擇器優先級計算器',
    category: 'workshop',
    description:
      '貼上一或多個 CSS 選擇器,算出每個的 (a, b, c) 優先級並由高到低排名,看清「為什麼這條 CSS 沒套用、誰覆蓋誰」。正確處理 :is()/:not()/:has() 取最高引數、:where() 為 0、虛擬元素 vs 虛擬類別、屬性與通用選擇器。全程在你瀏覽器解析,不上傳。',
    keywords: [
      'specificity',
      'css 優先級',
      '優先級',
      '優先序',
      '權重',
      'css 權重',
      '選擇器',
      'selector',
      'css 沒套用',
      '覆蓋',
      'override',
      ':is',
      ':where',
      ':not',
      ':has',
      '虛擬類別',
      '虛擬元素',
      'css 除錯',
      '前端',
    ],
    icon: '🎯',
    loader: () => import('@/tools/css-specificity/Index.vue'),
  },
  {
    id: 'glob-tester',
    name: 'Glob 樣式比對測試器',
    category: 'workshop',
    description:
      '填 glob 樣式(每行一個)與要測的路徑,即時看每個路徑符合哪些樣式,並顯示樣式編譯出的正規表達式。驗證 tsconfig include/exclude、CI path filter、.gitignore/.dockerignore 樣式對不對。支援 *、**、?、[abc]、{a,b}、不分大小寫。全程在你瀏覽器解析,不上傳。',
    keywords: [
      'glob',
      'glob 比對',
      '萬用字元',
      'wildcard',
      'minimatch',
      'gitignore',
      'dockerignore',
      'tsconfig',
      'include',
      'exclude',
      'path filter',
      '路徑比對',
      '樣式比對',
      'pattern',
      '星號',
      'globstar',
      '前端',
      '工具',
    ],
    icon: '🗂️',
    loader: () => import('@/tools/glob-tester/Index.vue'),
  },
  {
    id: 'slugify',
    name: '網址代稱 / Slug 產生器',
    category: 'workshop',
    description:
      '把文章標題/任意文字洗成適合放進網址的 slug —— 去除重音符號(café→cafe)、標點空白轉連字號、收斂去頭尾,可選小寫、保留中文、長度上限。部落格/CMS 文章網址、錨點 id 用。支援多行批次。全程在你瀏覽器,不上傳。',
    keywords: [
      'slug',
      'slugify',
      '網址代稱',
      '網址友善',
      '網址',
      'url',
      '永久連結',
      'permalink',
      '錨點',
      'anchor',
      'id',
      '文章網址',
      '部落格',
      'cms',
      '去重音',
      '標題轉網址',
      'seo',
      '連字號',
    ],
    icon: '🔗',
    loader: () => import('@/tools/slugify/Index.vue'),
  },
  {
    id: 'pangu-spacing',
    name: '中文排版(中英自動加空格)',
    category: 'workshop',
    description:
      '在中日韓文字與英文字母/數字之間自動補上半形空格(俗稱「盤古之白」),讓中英混排的文章、貼文、文件更易讀 —— 「在GitHub上有100顆星」→「在 GitHub 上有 100 顆星」。可重複套用結果不變、保留標點與換行。全程在你瀏覽器,不上傳。',
    keywords: [
      '盤古之白',
      '盤古',
      'pangu',
      '中英空格',
      '中英文空格',
      '加空格',
      '空格',
      '中文排版',
      '排版',
      '中英混排',
      '中英文',
      '自動空格',
      '中文英文之間',
      '可讀性',
      '文案',
      '貼文',
      '盤古之白加空格',
    ],
    icon: '🈳',
    loader: () => import('@/tools/pangu-spacing/Index.vue'),
  },
  {
    id: 'text-speech',
    name: '文字朗讀',
    category: 'life',
    description: '把貼上的文字用語音唸出來,給視力不便、眼睛累或想「用聽的」的長輩與家人 —— 用瀏覽器內建語音,全程在你的裝置發聲,文字不上傳、免帳號。速度音調可調。',
    keywords: ['朗讀', '唸出來', '念出來', '語音', '讀文章', '聽', '文字轉語音', 'tts', '報讀', '視障', '老花', '長輩', '念', '發音', 'speak', 'text to speech', '有聲'],
    icon: '🔊',
    loader: () => import('@/tools/text-speech/Index.vue'),
  },
  {
    id: 'exif-viewer',
    name: '照片隱私檢視器(EXIF)',
    category: 'anti-scam',
    description: '分享照片前先看它偷偷夾帶了什麼:拍攝時間、手機型號,甚至 GPS 拍攝地點 —— 含定位的照片會洩漏你家位置。全程在你瀏覽器解析,照片不上傳。',
    keywords: ['exif', '照片', '隱私', 'gps', '定位', '地點', '拍攝資訊', '中繼資料', 'metadata', '洩漏', '位置', '跟蹤', '相機', '型號', '去exif', '檢視'],
    icon: '📍',
    loader: () => import('@/tools/exif-viewer/Index.vue'),
  },
  {
    id: 'exif-strip',
    name: '照片個資清除(去 EXIF)',
    category: 'anti-scam',
    description: '不重新壓縮、畫質完全不變,直接移除照片夾帶的 EXIF/GPS 定位/拍攝時間/相機型號 —— 上傳社群或二手交易前先清掉,避免洩漏住家位置。全程在你瀏覽器處理,照片不上傳、可批次。',
    keywords: ['exif', '去exif', '去除exif', '個資', '隱私', 'gps', '定位', '位置', '住家', '中繼資料', 'metadata', '拍攝資訊', '清除', '移除', '照片', '相片', 'jpg', 'png', '二手', '社群', '洩漏', 'xmp', '不壓縮', '畫質不變', '批次'],
    icon: '🧹',
    loader: () => import('@/tools/exif-strip/Index.vue'),
  },
  {
    id: 'qr-decode',
    name: 'QR Code 解碼(看網址)',
    category: 'anti-scam',
    description: '把含 QR Code 的截圖或照片解出裡面的內容 —— 陌生 QR 直接掃容易被導到釣魚網站,先看清楚網址再決定要不要開。全程在你瀏覽器解碼,圖片不上傳。',
    keywords: ['qr', 'qrcode', 'qr code', '二維碼', '掃描', '解碼', '解析', '讀取', '讀qr', '看網址', '可疑', '釣魚', '停車單', '假帳單', 'decode', 'scan'],
    icon: '📷',
    loader: () => import('@/tools/qr-decode/Index.vue'),
  },
  {
    id: 'link-check',
    name: '可疑網址檢查器',
    category: 'anti-scam',
    description: '收到怪怪的連結?貼上來,馬上看出假冒網域、釣魚、短網址等詐騙特徵。',
    keywords: ['詐騙', '可疑', '網址', '連結', '釣魚', '假網站', '簡訊', '安全', '查證', '假冒', '釣魚網站'],
    icon: '🛡️',
    loader: () => import('@/tools/link-check/Index.vue'),
  },
  {
    id: 'url-clean',
    name: '網址清理 / 看穿轉址',
    category: 'anti-scam',
    description: '把 google.com/url、Facebook l.php、Outlook safelinks 等「轉址包裝」一層層拆開,先看清楚連結最後連去哪;順手清掉 utm、fbclid 等追蹤參數讓分享連結更乾淨。全程在你瀏覽器,不連網、不上傳。',
    keywords: ['網址', '連結', '轉址', '跳轉', '重新導向', '看穿', '真正連到', '追蹤', '追蹤碼', 'utm', 'fbclid', 'gclid', '清理', '乾淨', '縮網址', '展開', '參數', '隱私', 'redirect', '釣魚', '安全連結'],
    icon: '🔗',
    loader: () => import('@/tools/url-clean/Index.vue'),
  },
  {
    id: 'punycode',
    name: 'Punycode / IDN 網域檢視',
    category: 'anti-scam',
    description: '把 xn-- 開頭的網域解回真正顯示的文字,揪出用西里爾/希臘字母假冒英文(例 apple→аpple)的形近字釣魚網域 —— 全程在你瀏覽器解析,不連網、不上傳。',
    keywords: ['punycode', 'idn', 'xn--', '網域', '網址', '釣魚', '假網站', '假冒', '形近字', '同形異字', 'homograph', '西里爾', 'cyrillic', '混淆', 'confusable', '國際化網域', '解碼', '看穿', '假網域', '詐騙網址', 'idna'],
    icon: '🌐',
    loader: () => import('@/tools/punycode/Index.vue'),
  },
  {
    id: 'domain-twist',
    name: '相似網域產生(防仿冒)',
    category: 'anti-scam',
    description: '輸入你常用的真實網域(銀行、購物、政府),列出詐騙集團常拿來假冒它的形近 / 錯字網域樣式(少打多打、相鄰對調、l↔1 o↔0 形近字、插連字號、換 TLD…),認得仿冒網域長什麼樣。dnstwist 風格;只在你瀏覽器產生字串,不連網、不查詢任何網域。',
    keywords: ['相似網域', '仿冒網域', '假網域', '釣魚網域', 'typosquatting', 'dnstwist', '搶註', '形近網域', '錯字網域', '假冒', '仿冒', '防詐騙', '網域', '網址', 'phishing', '盜版網站', '山寨', 'homoglyph', 'tld', '品牌保護'],
    icon: '🎭',
    loader: () => import('@/tools/domain-twist/Index.vue'),
  },
  {
    id: 'sms-check',
    name: '詐騙簡訊檢查',
    category: 'anti-scam',
    description: '把可疑的簡訊或 LINE 訊息貼上來,辨識常見詐騙話術,並自動檢查裡面的連結。',
    keywords: ['詐騙', '簡訊', 'LINE', '訊息', '話術', '可疑', '假冒', '解除分期', '包裹', '中獎', '查證'],
    icon: '💬',
    loader: () => import('@/tools/sms-check/Index.vue'),
  },
  {
    id: 'email-check',
    name: '郵件來源檢視 / 防冒名',
    category: 'anti-scam',
    description: '貼上可疑信件的郵件原始碼/標頭,解析寄件網域、回覆地址與 SPF/DKIM/DMARC 驗證,標出冒名詐騙破綻。全程在你瀏覽器判讀、不上傳。',
    keywords: ['email', '郵件', '信件', '電子郵件', '標頭', 'header', '原始碼', '寄件者', '冒名', '偽冒', '釣魚', 'phishing', 'spf', 'dkim', 'dmarc', '網域', '退信', '回覆地址', '詐騙信', '假信'],
    icon: '📧',
    loader: () => import('@/tools/email-check/Index.vue'),
  },
  {
    id: 'scam-guide',
    name: '常見詐騙手法圖鑑',
    category: 'anti-scam',
    description: '解除分期、假投資、假檢警、包裹簡訊…一次看懂常見詐騙怎麼運作、破綻在哪、該怎麼做。轉給長輩看最有用。',
    keywords: ['詐騙', '手法', '圖鑑', '防詐', '反詐騙', '165', '假投資', '假檢警', '解除分期', '包裹', '一頁式', '假交友', '人頭帳戶', '懶人包', '長輩'],
    icon: '📖',
    loader: () => import('@/tools/scam-guide/Index.vue'),
  },
  {
    id: 'deal-risk',
    name: '網購交易詐騙風險評估',
    category: 'anti-scam',
    description:
      '下單前先勾選——價格過低、要你加 LINE 私下匯款、催你限時、要你操作 ATM 或給驗證碼…工具用加權題庫即時算出這筆交易的詐騙風險等級,並針對每個勾選項目給具體提醒。只要出現「操作 ATM、索驗證碼、退回多付款」等關鍵警訊就直接判為極高風險。轉給長輩當下單前的把關清單最有用。全程在你瀏覽器計算,不上傳。',
    keywords: [
      '網購',
      '詐騙',
      '風險',
      '評估',
      '交易',
      '賣家',
      '可疑',
      '網拍',
      '一頁式',
      '假網拍',
      '購物詐騙',
      '檢查清單',
      '把關',
      '165',
      '解除分期',
      '匯款',
      '訂金',
      '長輩',
      '防詐',
      '安全',
    ],
    icon: '🛒',
    loader: () => import('@/tools/deal-risk/Index.vue'),
  },
  {
    id: 'phone-check',
    name: '電話號碼檢視 / 防詐',
    category: 'anti-scam',
    description: '接到陌生來電?貼上號碼,看清楚它是手機、市話、免付費還是「付費語音」,並標出常見詐騙警訊(國際來電卻自稱國內機構、回撥被收高額費用等)。全程在你瀏覽器判讀、不上傳,附 165 官方查證連結。',
    keywords: ['電話', '號碼', '來電', '陌生來電', '可疑電話', '詐騙電話', '騷擾', '手機', '市話', '0204', '付費語音', '0800', '+886', '國際來電', '回撥', '查號', '165', '防詐'],
    icon: '📞',
    loader: () => import('@/tools/phone-check/Index.vue'),
  },
  {
    id: 'file-type',
    name: '檔案真實類型檢測',
    category: 'anti-scam',
    description: '讀檔頭「魔術位元組」判斷檔案實際是什麼格式,並和副檔名比對 —— 抓出把惡意程式改名成 .jpg、.pdf 的偽裝(詐騙常見手法)。副檔名能亂改,檔頭騙不了人。全程在你瀏覽器讀取,不上傳檔案。',
    keywords: ['檔案類型', '副檔名', '偽裝', '假檔', '惡意程式', '病毒', 'exe', '改副檔名', '魔術位元組', 'magic number', '真實格式', '附件', '可疑檔案', '掉包', '騙', '辨識檔案', 'file type'],
    icon: '🔬',
    loader: () => import('@/tools/file-type/Index.vue'),
  },
  {
    id: 'file-checksum',
    name: '檔案校驗碼 / 完整性驗證',
    category: 'anti-scam',
    description: '下載安裝檔後,算出 SHA-256/SHA-1/SHA-512 雜湊值,和官方公布的校驗碼比對,確認檔案沒被掉包或植入惡意程式 —— 全程在你瀏覽器計算,檔案不上傳。',
    keywords: ['校驗碼', '雜湊', 'hash', 'sha256', 'sha-256', 'sha1', 'sha512', '完整性', '驗證', '驗檔', '檔案指紋', '竄改', '掉包', '安裝檔', '校驗', 'checksum', '指紋', '比對'],
    icon: '🔐',
    loader: () => import('@/tools/file-checksum/Index.vue'),
  },
  {
    id: 'card-check',
    name: '信用卡卡號檢核',
    category: 'anti-scam',
    description: '用 Luhn 檢查碼驗證信用卡/金融卡卡號有沒有打對(抓少打、多打、錯一碼),並判斷發卡組織(Visa/Mastercard/JCB…)。全程本機計算、不上傳、不儲存,並提醒卡號+期限+末三碼湊齊就會被盜刷。',
    keywords: ['信用卡', '卡號', '金融卡', '檢核', '驗證', 'luhn', '檢查碼', '打錯', 'visa', 'mastercard', '萬事達', 'jcb', '美國運通', 'amex', '銀聯', 'unionpay', '卡別', '盜刷', '發卡組織', 'card'],
    icon: '💳',
    loader: () => import('@/tools/card-check/Index.vue'),
  },
  {
    id: 'severance-pay',
    name: '資遣費試算',
    category: 'labor',
    description: '輸入年資與平均工資,算出新制/舊制資遣費,並標明法規依據。',
    keywords: ['資遣費', '資遣', '遣散費', '被資遣', '裁員', '解僱', '離職金', '勞退', '年資'],
    icon: '💼',
    loader: () => import('@/tools/severance-pay/Index.vue'),
  },
  {
    id: 'annual-leave',
    name: '特休天數計算',
    category: 'labor',
    description: '依到職日與年資,算出依勞基法第38條應有的特別休假天數。',
    keywords: ['特休', '特別休假', '年假', '休假天數', '可以休幾天', '年資', '勞基法38'],
    icon: '🏖️',
    loader: () => import('@/tools/annual-leave/Index.vue'),
  },
  {
    id: 'overtime-pay',
    name: '加班費計算',
    category: 'labor',
    description: '依勞基法第24條,計算平日與休息日加班的加給金額。',
    keywords: ['加班費', '加班', 'OT', '延長工時', '休息日加班', '時薪', '勞基法24'],
    icon: '⏰',
    loader: () => import('@/tools/overtime-pay/Index.vue'),
  },
  {
    id: 'work-hours',
    name: '工時時數表',
    category: 'labor',
    description: '加總多段班別的工時,自動處理跨午夜夜班、扣除休息時間,可選填時薪估算原始工資 —— 打工/排班族對帳薪資、報工時用。全程在你瀏覽器計算,不上傳班表。',
    keywords: ['工時', '時數', '上班時間', '打卡', '排班', '班表', '加總', '幾小時', '夜班', '跨午夜', '休息', '打工', '兼職', '時薪', '報工時', '上班', '下班', '工作時間'],
    icon: '⏱️',
    loader: () => import('@/tools/work-hours/Index.vue'),
  },
  {
    id: 'leave-deduction',
    name: '請假扣薪試算',
    category: 'labor',
    description: '請事假、病假會被扣多少薪水?選假別、填天數,馬上算出應扣金額與仍可領的工資。',
    keywords: ['請假', '扣薪', '事假', '病假', '生理假', '婚假', '喪假', '特休', '家庭照顧假', '半薪', '無薪', '日薪', '時薪', '薪水'],
    icon: '🗓️',
    loader: () => import('@/tools/leave-deduction/Index.vue'),
  },
  {
    id: 'income-tax',
    name: '綜所稅速算',
    category: 'health-tax',
    description: '輸入綜合所得淨額,用財政部速算公式算出應納所得稅與有效稅率。',
    keywords: ['所得稅', '綜所稅', '報稅', '稅額', '級距', '速算', '繳稅', '綜合所得'],
    icon: '🧮',
    loader: () => import('@/tools/income-tax/Index.vue'),
  },
  {
    id: 'nhi-supplement',
    name: '二代健保補充保費',
    category: 'health-tax',
    description: '計算獎金、租金、股利、利息等收入要扣的二代健保補充保費。',
    keywords: ['二代健保', '補充保費', '健保', '獎金', '股利', '租金', '利息', '兼職'],
    icon: '🩺',
    loader: () => import('@/tools/nhi-supplement/Index.vue'),
  },
  {
    id: 'loan-calc',
    name: '貸款試算',
    category: 'finance',
    description: '房貸、車貸的每月應繳、總利息試算,支援本息/本金均攤與寬限期。',
    keywords: ['貸款', '房貸', '車貸', '利息', '每月還款', '月付', '本息均攤', '本金均攤', '寬限期'],
    icon: '🏠',
    loader: () => import('@/tools/loan-calc/Index.vue'),
  },
  {
    id: 'savings-interest',
    name: '定存複利試算',
    category: 'finance',
    description: '輸入本金、年利率、年數與複利次數,算出到期本利和與總利息。',
    keywords: ['定存', '複利', '利息', '存款', '本利和', '年利率', '理財', '單利'],
    icon: '🏦',
    loader: () => import('@/tools/savings-interest/Index.vue'),
  },
  {
    id: 'labor-pension-self',
    name: '勞退自提節稅試算',
    category: 'finance',
    description: '試算勞退自願提繳(上限 6%)金額,以及可省下的所得稅。',
    keywords: ['勞退', '自提', '自願提繳', '退休金', '節稅', '6%', '勞工退休金'],
    icon: '🐷',
    loader: () => import('@/tools/labor-pension-self/Index.vue'),
  },
  {
    id: 'labor-pension-annuity',
    name: '勞保老年年金試算',
    category: 'finance',
    description: '退休後勞保每月能領多少?輸入平均投保薪資與年資,兩式擇優算出月領金額,含提前/延後請領調整。',
    keywords: ['勞保', '老年年金', '退休金', '退休', '月退', '勞保年金', '請領', '投保薪資', '年資', '老年給付', '勞保老年'],
    icon: '👵',
    loader: () => import('@/tools/labor-pension-annuity/Index.vue'),
  },
  {
    id: 'installment-apr',
    name: '分期實際利率(APR)',
    category: 'finance',
    description: '「分期 0 利率」其實不便宜?輸入手續費,算出信用卡/分期付款的真實年利率。',
    keywords: ['分期', '利率', 'APR', '手續費', '信用卡', '免利率', '零利率', '實質利率', '年利率', '分期付款', '免息'],
    icon: '💳',
    loader: () => import('@/tools/installment-apr/Index.vue'),
  },
  {
    id: 'tw-id-check',
    name: '身分證字號檢核',
    category: 'life',
    description: '用內政部檢查碼規則驗算身分證字號是否格式正確,抓出打錯一碼或亂編的假號碼,並顯示初領縣市。全程本機計算、不上傳、不儲存。',
    keywords: ['身分證', '字號', '檢核', '驗證', '檢查碼', '格式', '真假', '假號碼', '初領', '縣市', 'id', '身份證', '檢查'],
    icon: '🪪',
    loader: () => import('@/tools/tw-id-check/Index.vue'),
  },
  {
    id: 'tw-vat-check',
    name: '統一編號檢核',
    category: 'life',
    description: '依財政部檢查碼規則,驗算公司統一編號(8 碼)是否正確 —— 抓出打錯一碼或亂編的假統編(假發票、人頭公司常見),可批次整理名單。全程本機計算、不上傳,並附財政部官方查詢連結。',
    keywords: ['統一編號', '統編', '營業稅籍', '公司', '行號', '檢核', '驗證', '檢查碼', '發票', '假發票', '人頭公司', '對帳', '廠商', 'vat', '8碼', '營利事業', '稅籍'],
    icon: '🏢',
    loader: () => import('@/tools/tw-vat-check/Index.vue'),
  },
  {
    id: 'isbn-check',
    name: 'ISBN 檢核 / 轉換',
    category: 'life',
    description: '驗證書籍 ISBN-10 / ISBN-13 檢查碼有沒有打對,並在兩種格式間互相轉換(978 開頭可轉,979 不可)。可批次對整批書單。全程本機計算、不上傳。',
    keywords: ['isbn', '國際標準書號', '書號', '書籍', '書', 'isbn10', 'isbn13', '檢查碼', '檢核', '驗證', '轉換', 'ean', '978', '979', '圖書', '書單', '出版'],
    icon: '📚',
    loader: () => import('@/tools/isbn-check/Index.vue'),
  },
  {
    id: 'gtin-check',
    name: '商品條碼檢查碼',
    category: 'life',
    description:
      '驗證 EAN-13 / UPC-A / EAN-8 / GTIN-14 商品條碼的 GS1 mod-10 檢查碼有沒有打對,或由前置碼自動補上檢查碼,並解讀 EAN-13 的國別 / 用途前置碼(如 471 = 臺灣)。只做數學驗證,不查詢商品資料;全程本機計算、不上傳。',
    keywords: [
      '條碼',
      '商品條碼',
      '檢查碼',
      'gtin',
      'ean',
      'ean13',
      'ean-13',
      'ean8',
      'upc',
      'upc-a',
      'itf-14',
      'barcode',
      '貨號',
      '料號',
      '商品編號',
      '驗證',
      '補檢查碼',
      'gs1',
      '國別碼',
      '471',
      '產地',
    ],
    icon: '🔖',
    loader: () => import('@/tools/gtin-check/Index.vue'),
  },
  {
    id: 'iban-check',
    name: 'IBAN 國際帳號驗證',
    category: 'workshop',
    description:
      '驗證歐洲 / 中東等地跨國匯款用的 IBAN 國際銀行帳號 —— 檢查國別代碼、長度與 mod-97 檢查碼,拆解國別/檢查碼/銀行帳號各欄位。收海外款項(自由接案、跨國匯款)前先驗一下,少打一碼就會匯錯。全程本機計算、不上傳。',
    keywords: [
      'iban',
      '國際銀行帳號',
      '跨國匯款',
      '海外匯款',
      '國際匯款',
      '銀行帳號驗證',
      '帳號檢查',
      'mod 97',
      'iso 13616',
      '接案收款',
      '歐元匯款',
      'swift',
      'bban',
      '檢查碼',
      '驗證帳號',
    ],
    icon: '🏦',
    loader: () => import('@/tools/iban-check/Index.vue'),
  },
  {
    id: 'password-gen',
    name: '本機密碼產生器',
    category: 'life',
    description: '用瀏覽器密碼學亂數產生高強度密碼,全程在你電腦、不連網、不記錄 —— 線上產生器可能偷偷記下你的密碼,這種工具就該在本機跑。',
    keywords: ['密碼', '產生', '產生器', '亂數', '隨機', 'password', '強密碼', '安全', '帳號', '兩步驟', '隨機密碼', '長密碼'],
    icon: '🔑',
    loader: () => import('@/tools/password-gen/Index.vue'),
  },
  {
    id: 'password-strength',
    name: '密碼強度檢測',
    category: 'anti-scam',
    description:
      '在本機即時估算密碼有多容易被破解:依字元種類算理論亂度,再因常見密碼、生日、連續、重複、鍵盤順序等弱點扣分,給出強度等級、離線/線上破解時間估計與具體改進建議。密碼是高敏資訊——全程在你的瀏覽器計算,絕不連網、不上傳、不儲存。',
    keywords: [
      '密碼強度',
      '密碼檢測',
      '密碼安全',
      'password strength',
      '強度',
      '破解時間',
      '亂度',
      'entropy',
      '弱密碼',
      '常見密碼',
      '帳號安全',
      '資安',
      '防駭',
      '密碼',
      'password',
    ],
    icon: '🔐',
    loader: () => import('@/tools/password-strength/Index.vue'),
  },
  {
    id: 'bmi',
    name: 'BMI 計算',
    category: 'life',
    description: '輸入身高體重,算出 BMI 與國健署體位分級,並給理想體重範圍。',
    keywords: ['bmi', '身體質量指數', '體重', '身高', '肥胖', '過重', '理想體重', '健康'],
    icon: '⚖️',
    loader: () => import('@/tools/bmi/Index.vue'),
  },
  {
    id: 'tdee',
    name: '每日熱量需求(TDEE)',
    category: 'life',
    description: '依身高體重年齡活動量,用 Mifflin-St Jeor 公式算出基礎代謝與每日該吃多少熱量。',
    keywords: ['熱量', 'tdee', 'bmr', '基礎代謝', '減重', '減肥', '卡路里', '大卡', '增肌', '飲食', '代謝率'],
    icon: '🔥',
    loader: () => import('@/tools/tdee/Index.vue'),
  },
  {
    id: 'unit-convert',
    name: '單位換算',
    category: 'life',
    description: '長度、重量、面積、溫度換算,含台灣常用的坪、台斤、台尺。',
    keywords: ['單位', '換算', '坪', '平方公尺', '台斤', '台尺', '公斤', '公里', '溫度', '攝氏', '華氏'],
    icon: '📐',
    loader: () => import('@/tools/unit-convert/Index.vue'),
  },
  {
    id: 'due-date',
    name: '預產期計算',
    category: 'life',
    description: '輸入最後一次月經第一天(LMP),推算預產期與目前懷孕週數。',
    keywords: ['預產期', '懷孕', '週數', '生產', 'LMP', '末次月經', '孕期'],
    icon: '🤰',
    loader: () => import('@/tools/due-date/Index.vue'),
  },
  {
    id: 'fuel-cost',
    name: '油錢試算',
    category: 'life',
    description: '輸入距離、油耗、油價,算出整趟油錢,還能直接除以人數算每人分攤。',
    keywords: ['油錢', '油費', '汽油', '加油', '里程', '油耗', '旅程', '開車', '分攤', '高速公路', '電車', '電費'],
    icon: '⛽',
    loader: () => import('@/tools/fuel-cost/Index.vue'),
  },
  {
    id: 'split-bill',
    name: '旅費分帳',
    category: 'life',
    description: '聚餐、旅遊一筆錢幾個人均分,可加服務費,馬上算出每人該付多少。',
    keywords: ['分帳', '均分', '平分', 'AA', '聚餐', '旅遊', '服務費', '每人', '攤錢'],
    icon: '🧮',
    loader: () => import('@/tools/split-bill/Index.vue'),
  },
  {
    id: 'invoice-lottery',
    name: '發票對獎',
    category: 'life',
    description: '輸入發票號碼,比對統一發票中獎號碼,自動算出中獎金額。',
    keywords: ['發票', '對獎', '中獎', '統一發票', '雲端發票', '對發票', '幾獎'],
    icon: '🧾',
    loader: () => import('@/tools/invoice-lottery/Index.vue'),
  },
  {
    id: 'einvoice-qr',
    name: '電子發票 QR 解析',
    category: 'life',
    description:
      '把電子發票證明聯「左方」QR 條碼掃出的那串文字貼進來,依財政部二維條碼規格拆解成發票號碼、開立日期(民國轉西元)、隨機碼、未稅銷售額與含稅總計額(自動把十六進位金額換算成台幣)、買賣方統一編號等,方便核對與記帳。全程在你瀏覽器解析,不連網、不上傳。',
    keywords: [
      '電子發票',
      '發票',
      'qr',
      '發票 qr',
      '二維條碼',
      '掃發票',
      '發票號碼',
      '隨機碼',
      '統一編號',
      '統編',
      '記帳',
      '報帳',
      '財政部',
      '證明聯',
      '銷售額',
      '核對發票',
    ],
    icon: '🧾',
    loader: () => import('@/tools/einvoice-qr/Index.vue'),
  },
  {
    id: 'morse-code',
    name: '摩斯密碼轉換',
    category: 'life',
    description:
      '文字與摩斯密碼(Morse code)互轉,依 ITU 國際標準碼表(A–Z、0–9、常用標點)。可調速播放嗶聲(PARIS 標準 WPM)、一鍵對調與複製,無法對應的字元會明確回報。全程在你瀏覽器計算與發聲,不連網、不上傳。',
    keywords: [
      '摩斯',
      '摩斯密碼',
      '摩斯電碼',
      'morse',
      'morse code',
      '電碼',
      '點劃',
      'sos',
      '密碼',
      '滴答',
      '嗶嗶',
      '電報',
      '訊號',
      '解碼',
      '編碼',
      '摩斯轉換',
    ],
    icon: '📡',
    loader: () => import('@/tools/morse-code/Index.vue'),
  },
  {
    id: 'num-to-chinese',
    name: '金額大寫互轉',
    category: 'life',
    description: '阿拉伯數字 ↔ 中文大寫雙向轉換:數字轉壹貳參…元角分整(支票/合約防竄改),也能把中文大寫金額反查回阿拉伯數字核對。全程在你瀏覽器換算,不上傳。',
    keywords: ['大寫', '國字', '金額', '數字轉中文', '中文數字', '中文轉數字', '大寫轉數字', '支票', '本票', '合約', '收據', '壹貳參', '元角分', '整', '銀行', '票據', '萬', '億', '阿拉伯數字', '核對', 'capital'],
    icon: '💴',
    loader: () => import('@/tools/num-to-chinese/Index.vue'),
  },
  {
    id: 'roman-numeral',
    name: '羅馬數字轉換',
    category: 'life',
    description: '阿拉伯數字(1–3999)↔ 標準羅馬數字雙向轉換,採減法記號(IV/IX/XL/XC/CD/CM)。讀懂時鐘、書本章節、版權年(MMXXIV=2024);解析時嚴格驗證,擋下 IIII、IC 等非規範寫法。全程在你瀏覽器,不上傳。',
    keywords: ['羅馬數字', 'roman', 'roman numeral', '羅馬', '數字轉換', 'mmxxiv', 'i v x l c d m', '減法記號', '章節', '時鐘', '版權年', '大綱編號', '轉換'],
    icon: 'Ⅶ',
    loader: () => import('@/tools/roman-numeral/Index.vue'),
  },
  {
    id: 'amount-english',
    name: '英文金額大寫',
    category: 'life',
    description: '把金額轉成英文文字寫法(例:USD ONE THOUSAND TWO HUNDRED THIRTY-FOUR AND 56/100 ONLY),供外銷發票、外幣支票、信用狀、英文合約使用 —— 與中文金額大寫互補。全程在你瀏覽器換算,不上傳。',
    keywords: ['英文金額', '金額英文', '大寫', '支票', 'cheque', 'check', '發票', 'invoice', '外銷', '出口', '信用狀', 'lc', '英文合約', 'dollars', 'cents', 'usd', '美金', '數字轉英文', 'amount in words', 'say', 'only'],
    icon: '💵',
    loader: () => import('@/tools/amount-english/Index.vue'),
  },
  {
    id: 'event-ics',
    name: '行事曆事件產生',
    category: 'life',
    description: '填好活動時間地點,下載 .ics 檔直接匯入 Google / Apple / Outlook 行事曆 —— 不必授權任何 App 存取你的行事曆。全程在你瀏覽器產生,不上傳。',
    keywords: ['行事曆', '日曆', '活動', '事件', 'ics', 'icalendar', '提醒', '邀請', 'google calendar', 'outlook', '匯入', '加到行事曆', '約會', '會議', '生日', '備忘', 'event', 'calendar'],
    icon: '📅',
    loader: () => import('@/tools/event-ics/Index.vue'),
  },
  {
    id: 'age-calc',
    name: '年齡計算',
    category: 'datetime',
    description: '輸入出生日期,算出實歲、虛歲、人壽保險年齡,還有已活天數與生日倒數。',
    keywords: ['年齡', '幾歲', '實歲', '足歲', '虛歲', '保險年齡', '生日', '倒數', '出生', '活了幾天', '歲數'],
    icon: '🎂',
    loader: () => import('@/tools/age-calc/Index.vue'),
  },
  {
    id: 'roc-year',
    name: '民國年換算',
    category: 'datetime',
    description: '民國年、西元年、日本年號(令和/平成/昭和)即時互換。',
    keywords: ['民國', '西元', '年份', '換算', '日本年號', '令和', '平成', '昭和', '幾年'],
    icon: '📆',
    loader: () => import('@/tools/roc-year/Index.vue'),
  },
  {
    id: 'ganzhi',
    name: '干支生肖納音',
    category: 'datetime',
    description:
      '輸入西元或民國年,算出該年的天干地支(六十甲子)、十二生肖、納音五行與六十甲子序。純數學換算、不上傳;以西曆年為準(年初春節/立春前出生者會提醒以前一年判讀)。與民國年換算、年齡計算互補。',
    keywords: [
      '干支',
      '天干地支',
      '六十甲子',
      '生肖',
      '十二生肖',
      '屬什麼',
      '納音',
      '納音五行',
      '甲子',
      '甲辰',
      '龍年',
      '蛇年',
      '農曆年',
      '生肖年',
      '年柱',
      'ganzhi',
      'zodiac',
      '五行',
      '紀年',
    ],
    icon: '🐉',
    loader: () => import('@/tools/ganzhi/Index.vue'),
  },
  {
    id: 'date-calc',
    name: '日期計算機',
    category: 'datetime',
    description: '算兩個日期相差幾天、從某天加減 N 天是哪天(可只算工作日)、兩日期間有幾個上班日 —— 契約、退貨鑑賞期、繳費、交期、請款到期日推算。工作日可自填國定假日/公司休假與補班日,把工作天算準。全程在你瀏覽器計算,不上傳。',
    keywords: ['日期', '天數', '相差', '幾天', '倒數', '到期日', '加天數', '減天數', '工作日', '工作天', '營業日', '上班日', '週末', '國定假日', '假日', '補班', '交期', '請款', '契約', '退貨', '鑑賞期', '繳費期限', '幾天後', '幾天前', 'date', '日數', '推算'],
    icon: '🗓️',
    loader: () => import('@/tools/date-calc/Index.vue'),
  },
]

export const toolMap: Record<string, ToolDef> = Object.fromEntries(
  tools.map((t) => [t.id, t]),
)

export function toolsByCategory(categoryId: string): ToolDef[] {
  return tools.filter((t) => t.category === categoryId)
}
